import {NextResponse} from 'next/server';import {createClient as svc} from '@supabase/supabase-js';import {createClient} from '../../../../lib/supabase/server';import {isAdminEmail} from '../../../../lib/admin';
async function db(){const a=createClient();const {data:{user}}=await a.auth.getUser();if(!user||!isAdminEmail(user.email))return null;return svc(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}})}
export async function GET(){const x=await db();if(!x)return NextResponse.json({error:'Unauthorized'},{status:401});const [{data:media},{data:schedule},{data:rotations}]=await Promise.all([x.from('radio_media').select('*').order('created_at',{ascending:false}),x.from('radio_schedule').select('*,radio_media(*)').order('starts_at'),x.from('radio_rotations').select('*,radio_rotation_items(*,radio_media(*))').order('created_at')]);return NextResponse.json({media:media||[],schedule:schedule||[],rotations:rotations||[]},{headers:{'cache-control':'no-store'}})}
export async function POST(req:Request){const x=await db();if(!x)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();const action=String(b.action||'');
 if(action==='media'){const p=b.payload||{};if(!p.title||!p.audio_url)return NextResponse.json({error:'Title and audio URL are required.'},{status:400});const {error}=await x.from('radio_media').insert({kind:p.kind,title:p.title,artist_or_host:p.artist_or_host||null,audio_url:p.audio_url,artwork_url:p.artwork_url||null,duration_seconds:Number(p.duration_seconds)||null});if(error)return NextResponse.json({error:error.message},{status:400})}
 else if(action==='schedule'){const p=b.payload||{};const start=new Date(p.starts_at),end=new Date(p.ends_at);if(!p.title||!p.event_type||isNaN(+start)||isNaN(+end)||end<=start)return NextResponse.json({error:'Enter a title and valid start/end time.'},{status:400});const {data:overlap}=await x.from('radio_schedule').select('id,title').eq('active',true).lt('starts_at',end.toISOString()).gt('ends_at',start.toISOString()).limit(1);if(overlap?.length)return NextResponse.json({error:`Schedule conflict with “${overlap[0].title}”.`},{status:409});const {error}=await x.from('radio_schedule').insert({media_id:p.media_id||null,title:p.title,event_type:p.event_type,starts_at:start.toISOString(),ends_at:end.toISOString(),recurrence:p.recurrence||'none',notes:p.notes||null});if(error)return NextResponse.json({error:error.message},{status:400})}
 else if(action==='rotation'){const p=b.payload||{};if(!p.name)return NextResponse.json({error:'Rotation name required.'},{status:400});const {error}=await x.from('radio_rotations').insert({name:p.name,description:p.description||null,weight:Number(p.weight)||1});if(error)return NextResponse.json({error:error.message},{status:400})}
 else if(action==='delete_schedule'){await x.from('radio_schedule').delete().eq('id',b.id)}
 else return NextResponse.json({error:'Unknown action.'},{status:400});return NextResponse.json({ok:true})}
