create extension if not exists pgcrypto;

create table if not exists public.reward_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  status text not null default 'phone_pending' check (status in ('phone_pending','active','locked','suspended','closed')),
  phone_hash text unique,
  phone_last4 text,
  phone_verified_at timestamptz,
  age_attested_at timestamptz,
  terms_version text,
  terms_accepted_at timestamptz,
  privacy_version text,
  privacy_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_terms_acceptances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.reward_profiles(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  user_agent text,
  ip_hash text,
  unique(user_id, terms_version, privacy_version)
);

create table if not exists public.reward_phone_otps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  phone_hash text not null,
  phone_last4 text not null,
  otp_hash text not null,
  expires_at timestamptz not null,
  attempt_count integer not null default 0,
  max_attempts integer not null default 5,
  consumed_at timestamptz,
  last_sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.reward_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_token_hash text not null,
  platform text,
  user_agent text,
  status text not null default 'trusted' check (status in ('trusted','review','blocked')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(user_id, device_token_hash)
);

create table if not exists public.reward_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists reward_terms_acceptances_profile_idx on public.reward_terms_acceptances(profile_id);
create index if not exists reward_phone_otps_user_created_idx on public.reward_phone_otps(user_id, created_at desc);
create index if not exists reward_phone_otps_phone_created_idx on public.reward_phone_otps(phone_hash, created_at desc);
create index if not exists reward_devices_hash_idx on public.reward_devices(device_token_hash);
create index if not exists reward_audit_events_user_created_idx on public.reward_audit_events(user_id, created_at desc);

create or replace function public.set_reward_profile_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reward_profiles_set_updated_at on public.reward_profiles;
create trigger reward_profiles_set_updated_at
before update on public.reward_profiles
for each row execute function public.set_reward_profile_updated_at();

alter table public.reward_profiles enable row level security;
alter table public.reward_terms_acceptances enable row level security;
alter table public.reward_phone_otps enable row level security;
alter table public.reward_devices enable row level security;
alter table public.reward_audit_events enable row level security;

revoke all on table public.reward_profiles from anon, authenticated;
revoke all on table public.reward_terms_acceptances from anon, authenticated;
revoke all on table public.reward_phone_otps from anon, authenticated;
revoke all on table public.reward_devices from anon, authenticated;
revoke all on table public.reward_audit_events from anon, authenticated;

drop policy if exists "reward_profiles_select_own" on public.reward_profiles;
create policy "reward_profiles_select_own"
on public.reward_profiles for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "reward_terms_select_own" on public.reward_terms_acceptances;
create policy "reward_terms_select_own"
on public.reward_terms_acceptances for select
to authenticated
using ((select auth.uid()) = user_id);

grant select on table public.reward_profiles to authenticated;
grant select on table public.reward_terms_acceptances to authenticated;

comment on table public.reward_profiles is 'One Watch & Earn rewards identity per authenticated Indie Cut viewer.';
comment on table public.reward_phone_otps is 'Short-lived hashed phone verification challenges. Service-role access only.';
comment on table public.reward_devices is 'Server-hashed browser device tokens used for rewards abuse detection.';
comment on table public.reward_audit_events is 'Append-only security and rewards identity audit trail.';
