'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
type Ad={_id:string;advertiser:string;title:string;creative_url:string;creative_media_type:string;destination_url:string;cta_text?:string;require_full_watch?:boolean;skip_after_seconds?:number};
type BreakMode='none'|'interval'|'custom';type Mode='program'|'ad';
function parseTimestamp(v:string){const p=v.trim().split(':').map(Number);if(p.some(n=>!Number.isFinite(n)))return null;if(p.length===2)return p[0]*60+p[1];if(p.length===3)return p[0]*3600+p[1]*60+p[2];return null}
function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export default function AdSupportedVideo({src,poster,breakMode='interval',intervalMinutes=6,customBreaks=''}:{src:string;poster?:string;breakMode?:BreakMode;intervalMinutes?:number;customBreaks?:string}){
 const playerRef=useRef<HTMLDivElement>(null),videoRef=useRef<HTMLVideoElement>(null),adsRef=useRef<Ad[]>([]),cursorRef=useRef(0),activeRef=useRef(false),modeRef=useRef<Mode>('program'),resumeAtRef=useRef(0),breakKeyRef=useRef<string|null>(null),playedRef=useRef(new Set<string>()),preRef=useRef(false);
 const [ads,setAds]=useState<Ad[]>([]),[activeAd,setActiveAd]=useState<Ad|null>(null),[mode,setMode]=useState<Mode>('program'),[remaining,setRemaining]=useState(0),[elapsed,setElapsed]=useState(0),[fullscreen,setFullscreen]=useState(false),[loading,setLoading]=useState(false);
 const interval=Math.max(1,Number(intervalMinutes)||6)*60;const customTimes=useMemo(()=>customBreaks.split(',').map(parseTimestamp).filter((n):n is number=>n!==null&&n>0).sort((a,b)=>a-b),[customBreaks]);
 useEffect(()=>{let off=false;fetch(`/api/public/ads?placement=video-midroll&t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()).then((j:unknown)=>{if(off)return;const payload=j as {ads?:unknown};const raw:Array<Partial<Ad>>=Array.isArray(payload?.ads)?payload.ads as Array<Partial<Ad>>:[];const eligible:Ad[]=raw.filter((a):a is Ad=>Boolean(a&&a._id&&a.advertiser&&a.title&&a.creative_url&&a.destination_url&&String(a.creative_media_type||'').startsWith('video/')));const rows:Ad[]=shuffle<Ad>(eligible);adsRef.current=rows;setAds(rows)}).catch(()=>{});return()=>{off=true}},[]);
 useEffect(()=>{const fn=()=>setFullscreen(document.fullscreenElement===playerRef.current);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn)},[]);
 function nextAd(){const r=adsRef.current;if(!r.length)return null;const ad=r[cursorRef.current%r.length];cursorRef.current=(cursorRef.current+1)%r.length;return ad}
 function startBreak(key:string){if(activeRef.current||playedRef.current.has(key)||!adsRef.current.length)return false;const v=videoRef.current;if(!v)return false;activeRef.current=true;breakKeyRef.current=key;resumeAtRef.current=key==='pre:0'?0:v.currentTime;v.pause();const ad=nextAd();if(!ad){resume();return false}setActiveAd(ad);setElapsed(0);setRemaining(0);setLoading(true);modeRef.current='ad';setMode('ad');v.controls=false;v.removeAttribute('poster');v.src=ad.creative_url;v.load();v.play().catch(()=>resume());return true}
 function resume(){const v=videoRef.current,key=breakKeyRef.current;if(key)playedRef.current.add(key);breakKeyRef.current=null;activeRef.current=false;modeRef.current='program';setMode('program');setActiveAd(null);setLoading(false);setElapsed(0);if(!v)return;v.pause();v.controls=true;v.src=src;if(poster)v.poster=poster;v.load();const go=()=>{try{v.currentTime=resumeAtRef.current}catch{}v.play().catch(()=>{})};if(v.readyState>=1)go();else v.addEventListener('loadedmetadata',go,{once:true})}
 function onPlay(){if(modeRef.current==='program'&&!activeRef.current&&!preRef.current&&adsRef.current.length){preRef.current=true;startBreak('pre:0')}}
 function checkBreak(){const v=videoRef.current;if(!v||modeRef.current!=='program'||activeRef.current||!ads.length||breakMode==='none')return;const t=v.currentTime;if(breakMode==='interval'){const n=Math.floor(t/interval);if(n>=1&&!playedRef.current.has(`i:${n}`))startBreak(`i:${n}`)}else for(const at of customTimes){const k=`c:${at}`;if(t>=at&&!playedRef.current.has(k)){startBreak(k);break}}}
 function onTime(){const v=videoRef.current;if(!v)return;if(modeRef.current==='program'){checkBreak();return}setElapsed(v.currentTime);if(Number.isFinite(v.duration))setRemaining(Math.max(0,Math.ceil(v.duration-v.currentTime)))}
 const skipAfter=Math.max(0,Number(activeAd?.skip_after_seconds??30)||0);const canSkip=Boolean(activeAd&&!activeAd.require_full_watch&&elapsed>=skipAfter);
 async function toggleFs(){try{if(document.fullscreenElement)await document.exitFullscreen();else await playerRef.current?.requestFullscreen()}catch{}}
 const cta=activeAd?.cta_text?.trim()||'Learn More';
 return <div ref={playerRef} style={{position:'relative',width:'100%',height:fullscreen?'100vh':'auto',background:'#000',overflow:'hidden',display:'grid',placeItems:'center'}}><video ref={videoRef} src={src} poster={poster} controls={mode==='program'} controlsList="nofullscreen" disablePictureInPicture playsInline preload="metadata" onPlay={onPlay} onPlaying={()=>setLoading(false)} onTimeUpdate={onTime} onSeeked={checkBreak} onEnded={()=>{if(modeRef.current==='ad')resume()}} onError={()=>{if(modeRef.current==='ad')resume()}} style={{width:'100%',height:fullscreen?'100%':'auto',aspectRatio:fullscreen?undefined:'16/9',maxHeight:fullscreen?'100vh':720,background:'#000',objectFit:'contain',display:'block'}}/>{mode==='program'&&<button type="button" onClick={toggleFs} style={{position:'absolute',right:12,bottom:fullscreen?18:48,zIndex:50,width:42,height:38,background:'rgba(0,0,0,.78)',color:'#fff',border:'1px solid #777',cursor:'pointer'}}>{fullscreen?'↙':'⛶'}</button>}{mode==='ad'&&activeAd&&<div style={{position:'absolute',inset:0,zIndex:60,pointerEvents:'none'}}><div style={{position:'absolute',left:14,top:12,padding:'6px 9px',background:'rgba(0,0,0,.72)',color:'#fff',fontSize:12,fontWeight:800,borderRadius:999}}>ADVERTISEMENT{remaining>0?` · ${remaining}s`:loading?' · LOADING…':''}</div>{canSkip&&<button type="button" onClick={resume} style={{pointerEvents:'auto',position:'absolute',right:16,top:12,padding:'9px 15px',background:'rgba(0,0,0,.82)',color:'#fff',border:'1px solid rgba(255,255,255,.65)',borderRadius:4,fontWeight:900,cursor:'pointer'}}>SKIP AD ›</button>}{!activeAd.require_full_watch&&!canSkip&&<div style={{position:'absolute',right:16,top:12,padding:'8px 12px',background:'rgba(0,0,0,.65)',color:'#fff',fontSize:12}}>Skip in {Math.max(0,Math.ceil(skipAfter-elapsed))}s</div>}{activeAd.destination_url&&<a href={activeAd.destination_url} target="_blank" rel="noopener noreferrer sponsored" style={{pointerEvents:'auto',position:'absolute',right:16,bottom:16,padding:'12px 20px',borderRadius:999,background:'#fff',color:'#111',fontSize:13,fontWeight:900,textDecoration:'none'}}>{cta} ↗</a>}</div>}</div>
}
