import PublicHeader from '../PublicHeader';
import PublicFooter from '../PublicFooter';
import AdSupportedVideo from './AdSupportedVideo';
import WatchGate from './WatchGate';
import {createClient as createServiceClient} from '@supabase/supabase-js';

export const revalidate=0;
function db(){return createServiceClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
function youtubeEmbed(url?:string){const s=String(url||'');let id='';try{const u=new URL(s);if(u.hostname.includes('youtu.be'))id=u.pathname.replace(/^\//,'').split('/')[0];else if(u.hostname.includes('youtube.com'))id=u.searchParams.get('v')||u.pathname.match(/\/shorts\/([^/?]+)/)?.[1]||''}catch{}return id?`https://www.youtube.com/embed/${id}`:''}
function label(v:any){const t=String(v.media_type||'video');if(t==='video')return v.artist_name?'SERIES / EPISODE':'INDIE CUT ORIGINAL';return t.replaceAll('_',' ').toUpperCase()}
function Player({v}:{v:any}){const yt=youtubeEmbed(v.media_url);return yt?<div style={{position:'relative',paddingBottom:'56.25%',height:0,overflow:'hidden',background:'#000'}}><iframe src={yt} title={v.title||'Video'} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen style={{position:'absolute',inset:0,width:'100%',height:'100%',border:0}}/></div>:<AdSupportedVideo src={v.media_url} poster={v.cover_url||undefined} breakMode={(v.ad_break_mode||'none') as any} intervalMinutes={Number(v.ad_break_interval_minutes||6)} customBreaks={String(v.custom_ad_breaks||'')}/>}
export default async function VideosPage(){
 const {data}=await db().from('media_items').select('*').in('media_type',['video','trailer','interview','clip','music_video']).order('created_at',{ascending:false});const videos=data||[],featured=videos.find((v:any)=>v.featured)||videos[0],episodes=videos.filter((v:any)=>v.media_type==='video'),interviews=videos.filter((v:any)=>v.media_type==='interview'),trailers=videos.filter((v:any)=>v.media_type==='trailer'||v.media_type==='clip'),music=videos.filter((v:any)=>v.media_type==='music_video');
 const Row=({title,items}:{title:string;items:any[]})=>items.length?<section style={{marginTop:42}}><h2 style={{fontSize:24,margin:'0 0 16px'}}>{title}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:20}}>{items.map((v:any)=><article key={v.id} style={{background:'#111217',border:'1px solid #24262d',overflow:'hidden'}}><Player v={v}/><div style={{padding:'15px 16px 18px'}}><div style={{fontSize:10,fontWeight:900,letterSpacing:'.12em',color:'#8d909a'}}>{label(v)}</div><h3 style={{fontSize:20,margin:'6px 0 4px'}}>{v.title}</h3>{v.artist_name&&<div style={{color:'#bbb',fontSize:13}}>{v.artist_name}</div>}</div></article>)}</div></section>:null;
 return <main style={{background:'#090a0d',color:'#fff',minHeight:'100vh'}}><PublicHeader/><WatchGate/>{featured&&<section style={{minHeight:'58vh',display:'flex',alignItems:'end',position:'relative',background:featured.cover_url?`linear-gradient(90deg,rgba(7,8,11,.98) 0%,rgba(7,8,11,.72) 48%,rgba(7,8,11,.22) 100%),url(${featured.cover_url}) center/cover`:'#111',padding:'clamp(42px,7vw,86px) max(22px,calc((100vw - 1180px)/2))'}}><div style={{maxWidth:650}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.18em'}}>INDIE CUT WATCH · FEATURED</div><h1 style={{fontSize:'clamp(44px,7vw,86px)',lineHeight:.92,margin:'12px 0 18px'}}>{featured.title}</h1>{featured.artist_name&&<strong>{featured.artist_name}</strong>}{featured.description&&<p style={{fontSize:17,lineHeight:1.6,color:'#ddd',maxWidth:590}}>{featured.description}</p>}<a href="#watch-now" style={{display:'inline-block',marginTop:10,padding:'13px 20px',background:'#fff',color:'#090909',fontWeight:900,textDecoration:'none'}}>▶ WATCH NOW</a></div></section>}<section id="watch-now" style={{maxWidth:1180,margin:'0 auto',padding:'38px 22px 80px'}}><div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:8}}>{['Shows & Episodes','Films & Trailers','Interviews','Music Videos'].map(x=><span key={x} style={{padding:'8px 12px',border:'1px solid #30323a',fontSize:12,fontWeight:800}}>{x}</span>)}</div>{videos.length===0?<div style={{padding:'40px 0'}}>New Indie Cut programming is coming soon.</div>:<><Row title="Shows & Episodes" items={episodes}/><Row title="Films, Trailers & Clips" items={trailers}/><Row title="Interviews" items={interviews}/><Row title="Music Videos" items={music}/>{videos.filter((v:any)=>!['video','trailer','clip','interview','music_video'].includes(v.media_type)).length>0&&<Row title="More on Indie Cut" items={videos}/>}</>}</section><PublicFooter/></main>
}
