'use client';
import {useEffect,useState} from 'react';

export default function WatchGate(){
 const [open,setOpen]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState('');
 useEffect(()=>{try{setOpen(localStorage.getItem('indiecut_watch_access')!=='1')}catch{setOpen(true)}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!email.trim())return;try{localStorage.setItem('indiecut_watch_access','1');localStorage.setItem('indiecut_watch_viewer',JSON.stringify({name:name.trim(),email:email.trim(),created_at:new Date().toISOString()}))}catch{}setOpen(false);fetch('/api/watch/viewer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name.trim(),email:email.trim()})}).catch(()=>{});}
 if(!open)return null;
 return <div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(5,5,8,.94)',display:'grid',placeItems:'center',padding:22,backdropFilter:'blur(10px)'}}><form onSubmit={submit} style={{width:'min(520px,100%)',background:'#111218',color:'#fff',padding:'clamp(26px,5vw,46px)',border:'1px solid #292b33',boxShadow:'0 30px 90px rgba(0,0,0,.55)'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.18em',color:'#aaa'}}>INDIE CUT WATCH</div><h2 style={{fontSize:'clamp(32px,6vw,52px)',lineHeight:.95,margin:'12px 0'}}>WATCH FREE.</h2><p style={{color:'#bbb',lineHeight:1.6}}>Enter your name and email once to unlock Indie Cut shows, films, interviews and original programming. No password required.</p><div style={{display:'grid',gap:12,marginTop:24}}><input aria-label="Name" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required style={{padding:'15px 16px',fontSize:16,border:'1px solid #343640',background:'#191a20',color:'#fff'}}/><input aria-label="Email" type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required style={{padding:'15px 16px',fontSize:16,border:'1px solid #343640',background:'#191a20',color:'#fff'}}/><button style={{padding:'15px 18px',border:0,background:'#fff',color:'#080808',fontWeight:900,fontSize:14,letterSpacing:'.08em'}}>START WATCHING</button></div><p style={{fontSize:11,color:'#777',marginTop:14}}>Free access. Your information helps Indie Cut understand and grow its audience.</p></form></div>
}
