import {NextResponse} from 'next/server';
import {createClient as createServiceClient} from '@supabase/supabase-js';
import {createClient} from '../../../../lib/supabase/server';
import {isAdminEmail} from '../../../../lib/admin';

export const dynamic='force-dynamic';
export const maxDuration=180;

function textFromResponse(json:any){if(typeof json?.output_text==='string')return json.output_text;const parts:string[]=[];for(const item of json?.output||[])for(const c of item?.content||[])if(typeof c?.text==='string')parts.push(c.text);return parts.join('\n').trim()}
function parseJson(text:string){const t=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim();const s=t.indexOf('{'),e=t.lastIndexOf('}');if(s<0||e<s)throw new Error('Invalid JSON');return JSON.parse(t.slice(s,e+1))}
function cleanSlug(value:string){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function safeUrl(v:any){const s=String(v||'').trim();return /^https?:\/\//i.test(s)?s:''}
function titleWords(v:string){return new Set(String(v||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(w=>w.length>2&&!['the','and','for','with','from','that','this','into','over','after','before'].includes(w)))}
function titleSimilarity(a:string,b:string){const x=titleWords(a),y=titleWords(b);if(!x.size||!y.size)return 0;let hit=0;for(const w of x)if(y.has(w))hit++;return hit/Math.max(x.size,y.size)}
function normalized(value:any){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function likelySameSubject(story:any,row:any){const subject=normalized(story?.subject_name);const priorSubject=normalized(row?.subject_name);const priorHeadline=normalized(row?.headline);if(subject&&priorSubject&&(subject===priorSubject||subject.includes(priorSubject)||priorSubject.includes(subject)))return true;if(subject){const tokens=subject.split(/\s+/).filter((x:string)=>x.length>2);if(tokens.length&&tokens.every((x:string)=>priorHeadline.includes(x)))return true}return titleSimilarity(String(story?.headline||''),String(row?.headline||''))>=0.28}
function shortlistCoverage(story:any,rows:any[]){return (rows||[]).filter((row:any)=>likelySameSubject(story,row)).slice(0,24).map((row:any)=>({headline:String(row?.headline||''),subheadline:String(row?.subheadline||''),subject_name:String(row?.subject_name||''),published_at:String(row?.published_at||row?.created_at||''),body_excerpt:String(row?.body||'').replace(/\s+/g,' ').slice(0,700)}))}
async function runCoverageGate(apiKey:string,story:any,rows:any[]){const prior=shortlistCoverage(story,rows);if(!prior.length)return {decision:'new_story',reason:'No closely related prior Indie Cut coverage found.',matched_headline:''};const prompt=`You are Indie Cut's coverage editor. Decide whether a proposed story repeats prior Indie Cut coverage. This is a STORY/EVENT check, not a PERSON-NAME check. The same artist, actor or celebrity may be covered many times when something genuinely different happens.\n\nDefinitions:\n- duplicate: same underlying event, announcement, allegation, release, ruling, interview angle or situation already covered, even if headline wording or source is different. Another outlet repeating the same facts is NOT new.\n- material_update: same continuing situation, but a genuinely new factual development happened afterward and advances the story, such as a new court ruling/filing, arrest/release, official decision, confirmed casting/release change, new result, new announcement or other concrete development. A rewrite, new commentary or another source repeating old facts is NOT a material update.\n- new_story: meaningfully different event or angle about the same person/subject, or a different subject.\n\nPROPOSED STORY:\n${JSON.stringify({headline:story?.headline,subheadline:story?.subheadline,subject_name:story?.subject_name,body_excerpt:String(story?.body||'').replace(/\s+/g,' ').slice(0,1400),sources:story?.sources})}\n\nRECENT RELATED INDIE CUT COVERAGE:\n${JSON.stringify(prior)}\n\nReturn ONLY valid JSON: {"decision":"new_story|material_update|duplicate","reason":"brief explanation","matched_headline":"closest prior headline or blank"}.`;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:prompt,max_output_tokens:500})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||'Coverage check failed');const parsed=parseJson(textFromResponse(j));const decision=String(parsed?.decision||'').toLowerCase();if(!['new_story','material_update','duplicate'].includes(decision))throw new Error('Invalid coverage decision');return {decision,reason:String(parsed?.reason||'').trim(),matched_headline:String(parsed?.matched_headline||'').trim()}}catch{const hardDuplicate=prior.find((row:any)=>cleanSlug(row.headline)===cleanSlug(story?.headline)||titleSimilarity(row.headline,String(story?.headline||''))>=0.78);return hardDuplicate?{decision:'duplicate',reason:'Fallback duplicate check matched prior Indie Cut coverage.',matched_headline:hardDuplicate.headline}:{decision:'new_story',reason:'Semantic coverage check unavailable; no hard duplicate matched.',matched_headline:''}}}

export async function POST(request:Request){
 const auth=createClient();const {data:{user}}=await auth.auth.getUser();
 if(!user||!isAdminEmail(user.email))return NextResponse.json({error:'Unauthorized'},{status:401});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,apiKey=process.env.OPENAI_API_KEY;
 if(!url||!key)return NextResponse.json({error:'Supabase admin credentials missing'},{status:503});
 if(!apiKey)return NextResponse.json({error:'OPENAI_API_KEY is not configured.'},{status:503});
 const db=createServiceClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const input=await request.json().catch(()=>({}));const lead=input?.lead||{};const publish=Boolean(input?.publish);
 const headline=String(lead.headline||'').trim();const seedSources=(Array.isArray(lead.sources)?lead.sources:[]).map(safeUrl).filter(Boolean);
 if(!headline||seedSources.length<1)return NextResponse.json({error:'A headline and at least one source are required.'},{status:400});
 const {data:existing}=await db.from('articles').select('id,headline,slug,subheadline,subject_name,body,created_at,published_at').order('created_at',{ascending:false}).limit(300);
 const slug=cleanSlug(headline);if((existing||[]).some((x:any)=>cleanSlug(x.slug||x.headline)===slug||String(x.headline||'').trim().toLowerCase()===headline.toLowerCase()))return NextResponse.json({error:'Indie Cut already appears to have this exact story.'},{status:409});

 const prompt=`You are Indie Cut's breaking-news editor. Re-check this entertainment lead using live web search and create a publish-ready article ONLY if the central claim remains verified. Use the supplied sources as starting points and add stronger sources when available. Never invent quotes, dates, casting, legal details, health claims, deaths, relationships, numbers or context. If the central claim cannot be corroborated by at least two credible sources, or one authoritative primary source plus a credible corroborating report, return verification_status not_verified. Write original journalism, not copied source language.\n\nFRESHNESS RULE: The same person may be covered again, but not the same underlying event, situation or angle unless a concrete new factual development has happened since Indie Cut's earlier coverage. Another outlet repeating the same facts is not a new story.\n\nLEAD HEADLINE: ${headline}\nLEAD SUMMARY: ${String(lead.summary||'')}\nWHY BREAKING: ${String(lead.why_breaking||'')}\nSUBJECT: ${String(lead.subject_name||'')}\nSTARTING SOURCES: ${seedSources.join(' | ')}\n\nReturn ONLY valid JSON: {"verification_status":"verified|not_verified","verification_note":"","headline":"strong accurate Indie Cut headline","subheadline":"","category":"movies|tv|music|culture|independent|celebrity","subject_name":"","body":"4-7 substantial paragraphs, current and factual","sources":["https://...","https://..."],"featured_image_url":"optional trustworthy image URL or blank","featured_image_source_url":"optional source page URL or blank"}.`;
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',tools:[{type:'web_search'}],input:prompt,max_output_tokens:8000})});
 const j=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:j?.error?.message||'Verification request failed'},{status:502});
 let parsed:any;try{parsed=parseJson(textFromResponse(j))}catch{return NextResponse.json({error:'The verification model returned invalid data.'},{status:502})}
 if(String(parsed?.verification_status||'').toLowerCase()!=='verified')return NextResponse.json({error:parsed?.verification_note||'The lead could not be re-verified.'},{status:409});
 const finalHeadline=String(parsed?.headline||headline).trim();const finalSlug=cleanSlug(finalHeadline);
 if((existing||[]).some((x:any)=>cleanSlug(x.slug||x.headline)===finalSlug||String(x.headline||'').trim().toLowerCase()===finalHeadline.toLowerCase()))return NextResponse.json({error:'Indie Cut already appears to have this exact story.'},{status:409});
 const sources=(Array.isArray(parsed?.sources)?parsed.sources:[]).map(safeUrl).filter(Boolean);const imageUrl=safeUrl(parsed?.featured_image_url),imageSource=safeUrl(parsed?.featured_image_source_url);if(imageSource&&!sources.includes(imageSource))sources.push(imageSource);
 if(sources.length<2)return NextResponse.json({error:'The re-check did not produce two credible sources.'},{status:409});
 const candidate={headline:finalHeadline,subheadline:String(parsed?.subheadline||''),subject_name:String(parsed?.subject_name||lead.subject_name||''),body:String(parsed?.body||''),sources};
 const coverage=await runCoverageGate(apiKey,candidate,existing||[]);
 if(coverage.decision==='duplicate')return NextResponse.json({error:'Indie Cut already covered this same story and no material update was found.',matched_headline:coverage.matched_headline,coverage_reason:coverage.reason},{status:409});
 const now=new Date().toISOString();
 const payload={headline:finalHeadline,slug:finalSlug,subheadline:String(parsed?.subheadline||'').trim()||null,category:String(parsed?.category||lead.category||'culture').trim().toLowerCase(),subject_name:String(parsed?.subject_name||lead.subject_name||'').trim()||null,body:String(parsed?.body||'').trim(),featured_media_url:imageUrl||null,sources,verification_status:'verified',status:publish?'published':'draft',published_at:publish?now:null};
 if(!payload.body)return NextResponse.json({error:'The verified article came back without article copy.'},{status:502});
 const {data:created,error}=await db.from('articles').insert(payload).select('id,headline,slug,status').single();if(error)return NextResponse.json({error:error.message},{status:500});
 return NextResponse.json({ok:true,id:created.id,headline:created.headline,slug:created.slug,status:created.status,sources:sources.length,coverage_decision:coverage.decision,coverage_reason:coverage.reason,matched_headline:coverage.matched_headline});
}