'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '../../lib/supabase/browser';

type Tab='dashboard'|'articles'|'artists'|'media'|'agent';
const emptyArticle={headline:'',subheadline:'',category:'culture',subject_name:'',body:'',featured_media_url:'',author_name:'Indie Cut Editorial',sources:'',verification_status:'verified',status:'draft'};
const emptyArtist={name:'',kind:'artist',bio:'',image_url:'',website_url:'',instagram_url:'',featured:false};
const emptyMedia={title:'',media_type:'music',artist_name:'',description:'',media_url:'',cover_url:'',featured:false};

export default function AdminClient(){
 const router=useRouter();
 const [tab,setTab]=useState<Tab>('dashboard');
 const [articles,setArticles]=useState<any[]>([]);const [artists,setArtists]=useState<any[]>([]);const [media,setMedia]=useState<any[]>([]);
 const [article,setArticle]=useState<any>(emptyArticle);const [artist,setArtist]=useState<any>(emptyArtist);const [mediaForm,setMediaForm]=useState<any>(emptyMedia);
 const [topic,setTopic]=useState('Find the strongest verified trending entertainment story involving a Black actor, musician, filmmaker, TV personality, or independent creator.');
 const [count,setCount]=useState(3);const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');
 async function api(url:string,options:any={}){const res=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data}
 async function load(){try{const data=await api('/api/admin/content');setArticles(data.articles||[]);setArtists(data.artists||[]);setMedia(data.media||[])}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(kind:string,payload:any){setLoading(true);setMessage('');try{await api('/api/admin/content',{method:'POST',body:JSON.stringify({kind,payload})});setMessage(`${kind} saved.`);if(kind==='article')setArticle(emptyArticle);if(kind==='artist')setArtist(emptyArtist);if(kind==='media')setMediaForm(emptyMedia);await load()}catch(e:any){setMessage(e.message)}finally{setLoading(false)}}
 async function remove(kind:string,id:string){if(!confirm('Delete this item?'))return;try{await api('/api/admin/content',{method:'DELETE',body:JSON.stringify({kind,id})});await load()}catch(e:any){setMessage(e.message)}}
 async function changeArticle(id:string,status:string){try{await api('/api/admin/content',{method:'PATCH',body:JSON.stringify({kind:'article',id,payload:{status,published_at:status==='published'?new Date().toISOString():null}})});await load()}catch(e:any){setMessage(e.message)}}
 async function runAgent(){setLoading(true);setResult(null);setMessage('');try{const res=await api('/api/content-agent/run',{method:'POST',body:JSON.stringify({topic,count})});setResult(res);await load()}catch(e:any){setMessage(e.message)}finally{setLoading(false)}}
 async function logout(){const supabase=createClient();await supabase.auth.signOut();router.replace('/admin/login');router.refresh()}
 const nav=(id:Tab,label:string)=><button onClick={()=>setTab(id)} style={{background:tab===id?'#111':'#fff',color:tab===id?'#fff':'#111',border:'1px solid #111',padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>{label}</button>;
 return <main className="admin">
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><div className="kicker">EDITORIAL CONTROL ROOM</div><h1 style={{margin:'6px 0'}}>Indie Cut Back Office</h1></div><button onClick={logout}>SIGN OUT</button></div>
  <div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'20px 0'}}>{nav('dashboard','Dashboard')}{nav('articles','Articles')}{nav('artists','Artists & People')}{nav('media','Music & Video')}{nav('agent','AI Content Agent')}</div>
  {message&&<div className="panel" style={{borderColor:'#111'}}><strong>{message}</strong></div>}
  {tab==='dashboard'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14}}><div className="panel"><div className="kicker">ARTICLES</div><h2>{articles.length}</h2><p>{articles.filter(x=>x.status==='draft').length} drafts · {articles.filter(x=>x.status==='published').length} published</p></div><div className="panel"><div className="kicker">ARTISTS / PEOPLE</div><h2>{artists.length}</h2><p>Profiles in your entertainment database</p></div><div className="panel"><div className="kicker">MUSIC / VIDEO</div><h2>{media.length}</h2><p>Tracks, videos, trailers and clips</p></div></div><div className="panel"><h2>Quick Start</h2><p>Use Articles to write or publish a story, Artists & People to build profiles, Music & Video to add entertainment media, or ask the AI Content Agent to research a current verified story.</p></div></>}
  {tab==='articles'&&<><div className="panel"><h2>Create Article</h2><label>Headline</label><input value={article.headline} onChange={e=>setArticle({...article,headline:e.target.value})}/><label>Subheadline</label><input value={article.subheadline} onChange={e=>setArticle({...article,subheadline:e.target.value})}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><label>Category</label><select value={article.category} onChange={e=>setArticle({...article,category:e.target.value})}><option>movies</option><option>tv</option><option>music</option><option>culture</option><option>independent</option><option>celebrity</option></select></div><div><label>Subject / Person</label><input value={article.subject_name} onChange={e=>setArticle({...article,subject_name:e.target.value})}/></div></div><label>Featured image or video URL</label><input value={article.featured_media_url} onChange={e=>setArticle({...article,featured_media_url:e.target.value})}/><label>Article body</label><textarea rows={12} value={article.body} onChange={e=>setArticle({...article,body:e.target.value})}/><label>Source URLs — one per line</label><textarea rows={4} value={article.sources} onChange={e=>setArticle({...article,sources:e.target.value})}/><button disabled={loading||!article.headline} onClick={()=>save('article',article)}>SAVE ARTICLE</button></div><div className="panel"><h2>All Articles</h2>{articles.map(a=><div key={a.id} style={{borderTop:'1px solid #ddd',padding:'14px 0'}}><strong>{a.headline}</strong><div style={{fontSize:13,margin:'6px 0'}}>{a.category} · {a.verification_status} · {a.status}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{a.status!=='published'&&<button onClick={()=>changeArticle(a.id,'published')}>PUBLISH</button>}{a.status==='published'&&<button onClick={()=>changeArticle(a.id,'draft')}>MOVE TO DRAFT</button>}<button onClick={()=>remove('article',a.id)}>DELETE</button></div></div>)}</div></>}
  {tab==='artists'&&<><div className="panel"><h2>Add Artist / Actor / Creator</h2><label>Name</label><input value={artist.name} onChange={e=>setArtist({...artist,name:e.target.value})}/><label>Type</label><select value={artist.kind} onChange={e=>setArtist({...artist,kind:e.target.value})}><option>artist</option><option>actor</option><option>musician</option><option>filmmaker</option><option>creator</option><option>comedian</option><option>personality</option></select><label>Bio</label><textarea rows={6} value={artist.bio} onChange={e=>setArtist({...artist,bio:e.target.value})}/><label>Photo URL</label><input value={artist.image_url} onChange={e=>setArtist({...artist,image_url:e.target.value})}/><label>Website</label><input value={artist.website_url} onChange={e=>setArtist({...artist,website_url:e.target.value})}/><label>Instagram</label><input value={artist.instagram_url} onChange={e=>setArtist({...artist,instagram_url:e.target.value})}/><label><input style={{width:'auto',marginRight:8}} type="checkbox" checked={artist.featured} onChange={e=>setArtist({...artist,featured:e.target.checked})}/>Featured</label><br/><button disabled={loading||!artist.name} onClick={()=>save('artist',artist)}>SAVE PROFILE</button></div><div className="panel"><h2>Artists & People</h2>{artists.map(a=><div key={a.id} style={{borderTop:'1px solid #ddd',padding:'12px 0',display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{a.name}</strong><div>{a.kind}</div></div><button onClick={()=>remove('artist',a.id)}>DELETE</button></div>)}</div></>}
  {tab==='media'&&<><div className="panel"><h2>Add Music / Video</h2><label>Title</label><input value={mediaForm.title} onChange={e=>setMediaForm({...mediaForm,title:e.target.value})}/><label>Media type</label><select value={mediaForm.media_type} onChange={e=>setMediaForm({...mediaForm,media_type:e.target.value})}><option value="music">Music</option><option value="video">Video</option><option value="trailer">Trailer</option><option value="interview">Interview</option><option value="clip">Clip</option></select><label>Artist / Creator</label><input value={mediaForm.artist_name} onChange={e=>setMediaForm({...mediaForm,artist_name:e.target.value})}/><label>Music or video URL</label><input value={mediaForm.media_url} onChange={e=>setMediaForm({...mediaForm,media_url:e.target.value})}/><label>Cover / thumbnail URL</label><input value={mediaForm.cover_url} onChange={e=>setMediaForm({...mediaForm,cover_url:e.target.value})}/><label>Description</label><textarea rows={5} value={mediaForm.description} onChange={e=>setMediaForm({...mediaForm,description:e.target.value})}/><label><input style={{width:'auto',marginRight:8}} type="checkbox" checked={mediaForm.featured} onChange={e=>setMediaForm({...mediaForm,featured:e.target.checked})}/>Featured</label><br/><button disabled={loading||!mediaForm.title||!mediaForm.media_url} onClick={()=>save('media',mediaForm)}>SAVE MEDIA</button></div><div className="panel"><h2>Music & Video Library</h2>{media.map(m=><div key={m.id} style={{borderTop:'1px solid #ddd',padding:'12px 0',display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{m.title}</strong><div>{m.media_type}{m.artist_name?` · ${m.artist_name}`:''}</div></div><button onClick={()=>remove('media',m.id)}>DELETE</button></div>)}</div></>}
  {tab==='agent'&&<div className="panel"><h2>Verified Entertainment Research Agent</h2><p>Ask it for a trending story. It searches the live web, vets the reporting, rejects rumors and creates only verified drafts.</p><label>Assignment</label><textarea rows={7} value={topic} onChange={e=>setTopic(e.target.value)}/><label>Number of drafts</label><input type="number" min={1} max={5} value={count} onChange={e=>setCount(Number(e.target.value)||1)}/><button onClick={runAgent} disabled={loading}>{loading?'RESEARCHING & VERIFYING…':'FIND VERIFIED STORIES'}</button>{result&&<pre style={{whiteSpace:'pre-wrap',marginTop:20,background:'#f5f5f5',padding:16,overflow:'auto'}}>{JSON.stringify(result,null,2)}</pre>}</div>}
 </main>
}
