'use client';

import {useEffect,useState} from 'react';
import {createClient as createBrowserClient} from '../../lib/supabase/browser';
import {compressVideoForUpload} from './VideoUploadGuard';

type Ad={_id?:string;advertiser:string;title:string;creative_url:string;creative_media_type:string;destination_url:string;placement:string;start_date:string;end_date:string;active:boolean;created_at?:string;target_mode:'global'|'local';target_zip:string;target_city:string;target_region:string;radius_miles:number;target_latitude:string;target_longitude:string};
const empty:Ad={advertiser:'',title:'',creative_url:'',creative_media_type:'',destination_url:'',placement:'right-rail',start_date:'',end_date:'',active:true,target_mode:'global',target_zip:'',target_city:'',target_region:'',radius_miles:20,target_latitude:'',target_longitude:''};

export default function AdvertisingManager(){
 const [rows,setRows]=useState<Ad[]>([]);const [form,setForm]=useState<Ad>({...empty});const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState('');const [preview,setPreview]=useState('');
 async function load(){const r=await fetch('/api/admin/data?section=advertising');const t=await r.text();let j:any={};try{j=JSON.parse(t)}catch{};if(r.ok)setRows((j.rows||[]).map((x:any)=>({...empty,...x,target_mode:x.target_mode==='local'?'local':'global'})));else setMessage(j.error||t||'Unable to load ads')}
 useEffect(()=>{load()},[]);
 async function upload(file?:File){if(!file)return;setUploading(true);setMessage('Preparing media…');setPreview(URL.createObjectURL(file));try{
   let prepared:File=file;
   if(file.type.startsWith('video/'))prepared=await compressVideoForUpload(file,setMessage);
   const mediaType=prepared.type||file.type||'application/octet-stream';
   const signRes=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:prepared.name||file.name,mime:mediaType,size:prepared.size})});
   const signText=await signRes.text();let signed:any={};try{signed=JSON.parse(signText)}catch{throw new Error(signText||'Unable to prepare upload')};if(!signRes.ok)throw new Error(signed.error||'Unable to prepare upload');
   setMessage('Uploading ad creative…');const supabase=createBrowserClient();const {error}=await supabase.storage.from(signed.bucket).uploadToSignedUrl(signed.path,signed.token,prepared,{contentType:mediaType});if(error)throw error;
   setForm(f=>({...f,creative_url:signed.publicUrl,creative_media_type:mediaType}));setPreview(signed.publicUrl);setMessage('Upload complete. Click SAVE AD.');
 }catch(e:any){setMessage(e?.message||'Upload failed');setForm(f=>({...f,creative_url:'',creative_media_type:''}))}finally{setUploading(false)}}
 async function lookupZip(){if(!form.target_zip.trim())return setMessage('Enter the ZIP code you want to target.');setBusy(true);setMessage('Looking up ZIP center…');try{const r=await fetch(`/api/admin/geocode?zip=${encodeURIComponent(form.target_zip.trim())}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'ZIP lookup failed');setForm(f=>({...f,target_zip:j.zip||f.target_zip,target_city:j.city||'',target_region:j.region||'',target_latitude:String(j.latitude),target_longitude:String(j.longitude)}));setMessage(`Target center set to ${j.city}, ${j.region} ${j.zip}. The radius will be measured from this point.`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();if(uploading){setMessage('Wait for the video upload to finish before saving.');return}if(!form.creative_url){setMessage('Upload the ad image or video first.');return}if(form.target_mode==='local'&&(!form.target_zip||!form.target_latitude||!form.target_longitude)){setMessage('For local targeting, enter a ZIP code and click LOOK UP ZIP before saving.');return}setBusy(true);setMessage('Saving advertisement…');try{const r=await fetch('/api/admin/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({section:'advertising',data:form})});const t=await r.text();let j:any={};try{j=JSON.parse(t)}catch{};if(!r.ok)throw new Error(j.error||t||'Save failed');setForm({...empty});setPreview('');setMessage('Advertisement saved and activated.');await load()}catch(e:any){setMessage(e?.message||'Save failed')}finally{setBusy(false)}}
 async function remove(id?:string){if(!id||!confirm('Delete this ad?'))return;const r=await fetch(`/api/admin/data?section=advertising&id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok){setMessage('Delete failed');return}await load()}
 const isVideo=(form.creative_media_type||'').startsWith('video/');
 const audience=(r:any)=>r.target_mode==='local'?`${r.target_zip||r.target_city||'Local'} +${Number(r.radius_miles)||20} mi`:'Global';
 return <section className="ic-module-panel"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:18}}><div><h2 style={{margin:0}}>Advertising</h2><p style={{margin:'6px 0 0',maxWidth:900}}>Run global campaigns everywhere or geo-target a local advertiser by ZIP-code radius. Local campaigns are served only when the visitor is inside the selected area, with global inventory as the fallback.</p></div></div>
 <form onSubmit={save} style={{display:'grid',gap:14}}>
  <label>Advertiser<input value={form.advertiser} onChange={e=>setForm({...form,advertiser:e.target.value})} required/></label>
  <label>Campaign / Ad title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
  <div><label>Ad creative — image or video</label>{preview&&<div style={{margin:'8px 0 12px',maxWidth:720}}>{isVideo||preview.startsWith('blob:')?<video src={preview} controls playsInline style={{width:'100%',maxHeight:420,background:'#000'}}/>:<img src={preview} alt="Ad preview" style={{maxWidth:'100%',maxHeight:420,objectFit:'contain'}}/>}</div>}<label style={{display:'inline-block',padding:'11px 15px',background:'#111',color:'#fff',fontWeight:800,cursor:'pointer'}}>{uploading?'UPLOADING…':'UPLOAD IMAGE / VIDEO'}<input type="file" accept="image/*,video/*" style={{display:'none'}} disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label></div>
  <label>Destination URL<input type="url" value={form.destination_url} onChange={e=>setForm({...form,destination_url:e.target.value})}/></label>
  <label>Placement<select value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}><option value="sitewide">Sitewide — all eligible ad slots</option><option value="right-rail">Right rail</option><option value="homepage">Homepage</option><option value="article-inline">Article inline</option><option value="article-top">Article top</option><option value="battle-artist">Battle artist voting page</option><option value="battle-room">Live Battle Room sponsor</option></select></label>
  <div style={{padding:16,border:'1px solid #d6d6d6',background:'#fafafa',display:'grid',gap:12}}><div><strong style={{display:'block',marginBottom:4}}>Audience targeting</strong><span style={{fontSize:12,color:'#666'}}>Use Global for everyone, or Local to serve this campaign only inside a geographic radius.</span></div><label>Audience<select value={form.target_mode} onChange={e=>setForm({...form,target_mode:e.target.value as 'global'|'local'})}><option value="global">Global — show wherever this placement runs</option><option value="local">Local — target a ZIP-code radius</option></select></label>{form.target_mode==='local'&&<><div style={{display:'grid',gridTemplateColumns:'1.1fr .8fr auto',gap:10,alignItems:'end'}}><label>Target ZIP code<input value={form.target_zip} onChange={e=>setForm({...form,target_zip:e.target.value,target_latitude:'',target_longitude:''})} placeholder="06702" maxLength={10}/></label><label>Radius (miles)<input type="number" min="1" max="250" value={form.radius_miles} onChange={e=>setForm({...form,radius_miles:Math.max(1,Number(e.target.value)||20)})}/></label><button type="button" onClick={lookupZip} disabled={busy} style={{height:42}}>LOOK UP ZIP</button></div><div style={{fontSize:12,color:'#555',padding:'10px 12px',background:'#fff',border:'1px solid #e1e1e1'}}>{form.target_latitude&&form.target_longitude?<><strong>Target center:</strong> {form.target_city||form.target_zip}{form.target_region?`, ${form.target_region}`:''} · {form.target_zip} · {form.radius_miles} mile radius</>:<>Enter a ZIP code and click <strong>LOOK UP ZIP</strong>. Indie Cut will save the center point and automatically compare it with each visitor's approximate location.</>}</div></>}</div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>Start date<input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>End date<input type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label></div>
  <label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active campaign</label>
  <button type="submit" disabled={busy||uploading} style={{width:150}}>{busy?'SAVING…':'SAVE AD'}</button>
  {message&&<div className="ic-message">{message}</div>}
 </form>
 <div style={{marginTop:34,borderTop:'1px solid #ddd',paddingTop:20}}><h2>Existing Ad Units</h2>{rows.map(r=><article key={r._id} style={{display:'grid',gridTemplateColumns:'110px 1fr auto',gap:16,alignItems:'center',padding:'14px 0',borderBottom:'1px solid #eee'}}>{r.creative_url?<div>{String(r.creative_media_type||'').startsWith('video/')?<video src={r.creative_url} muted playsInline style={{width:100,height:70,objectFit:'cover',background:'#000'}}/>:<img src={r.creative_url} alt="" style={{width:100,height:70,objectFit:'cover'}}/>}</div>:<div/>}<div><strong>{r.title||r.advertiser||'Advertisement'}</strong><div style={{fontSize:12,color:'#666',marginTop:4}}>{r.placement} · {r.active?'Active':'Inactive'} · {r.creative_media_type||'media'}</div><div style={{fontSize:12,fontWeight:800,marginTop:5,color:r.target_mode==='local'?'#b54000':'#155724'}}>{audience(r)}</div></div><button type="button" onClick={()=>remove(r._id)}>Delete</button></article>)}</div>
 </section>
}
