// @ts-nocheck
'use client';
import {useEffect,useMemo,useState} from 'react';
import styles from './AutomationBuilder.module.css';

const item=(id,label,category,description,requires=null,native=true)=>({id,label,category,description,requires,native});
const TRIGGERS=[
 item('manual','Manual Enrollment','Contacts','Start manually'),item('contact_created','Contact Created','Contacts','New CRM contact created'),item('contact_updated','Contact Changed','Contacts','Tracked contact field changed'),item('status_changed','Contact Status Changed','Contacts','CRM status changed'),item('tag_added','Contact Tag Added','Contacts','Tag added'),item('tag_removed','Contact Tag Removed','Contacts','Tag removed'),item('contact_dnd','Contact DND','Contacts','DND setting changed'),item('birthday_reminder','Birthday Reminder','Contacts','Runs on contact birthday'),item('custom_date_reminder','Custom Date Reminder','Contacts','Runs from a contact custom date'),item('note_added','Note Added','Contacts','CRM note added'),item('task_added','Task Added','Contacts','CRM task created'),item('task_reminder','Task Reminder','Contacts','CRM task due'),item('contact_engagement_score','Contact Engagement Score','Contacts','Engagement score changed'),
 item('webhook_received','Inbound Webhook','Forms & Web','External event reaches Indie Cut'),item('form_submitted','Form Submitted','Forms & Web','Connected Indie Cut form submitted'),item('scheduled','Scheduler','Logic & Time','Run once or on a recurring schedule'),
 item('appointment_created','Customer Booked Appointment','Appointments','Native Indie Cut appointment created'),item('appointment_changed','Appointment Status / Changed','Appointments','Native Indie Cut appointment changed'),item('service_booking','Service Booking','Appointments','Native service booking event'),item('rental_booking','Rental Booking','Appointments','Native rental booking event'),
 item('opportunity_created','Opportunity Created','Opportunities','Native opportunity created'),item('opportunity_changed','Opportunity Changed','Opportunities','Native opportunity changed'),item('pipeline_stage_changed','Pipeline Stage Changed','Opportunities','Native opportunity stage changed'),item('stale_opportunities','Stale Opportunities','Opportunities','Opportunity has not moved for a set period'),
 item('payment_received','Payment Received','Payments','Payment succeeds','payments',false),item('payment_failed','Payment Failed','Payments','Payment fails','payments',false),item('refund_issued','Refund Issued','Payments','Refund issued','payments',false),item('subscription','Subscription Event','Payments','Subscription changed','payments',false),
 item('meta_lead','Facebook / Instagram Lead Form','Social','Meta lead form submission','meta_leads',false),item('tiktok_lead','TikTok Lead Form','Social','TikTok lead form submission','tiktok_leads',false),item('social_message','Social Message Received','Social','Connected social inbox message','social_messaging',false),item('facebook_comment','Facebook Comment','Social','Comment on Facebook post','meta_messaging',false),item('instagram_comment','Instagram Comment','Social','Comment on Instagram post','meta_messaging',false),item('tiktok_comment','TikTok Comment','Social','Comment on TikTok video','tiktok_messaging',false),
 item('battle_submission_received','Battle Submission Received','Indie Cut Battles','Artist submits music'),item('battle_submission_approved','Battle Submission Approved','Indie Cut Battles','Submission approved'),item('battle_submission_rejected','Battle Submission Rejected','Indie Cut Battles','Submission rejected'),item('vote_received','Vote Received','Indie Cut Battles','Verified fan vote received'),item('artist_advanced','Artist Advanced','Indie Cut Battles','Artist advances'),item('battle_started','Battle Started','Indie Cut Battles','Battle goes live'),item('battle_ended','Battle Ended','Indie Cut Battles','Battle completes'),item('winner_selected','Winner Selected','Indie Cut Battles','Champion selected')
];
const ACTIONS=[
 item('send_email','Send Email','Communication','Send through Resend','email'),item('send_sms','Send SMS','Communication','Send through TextGrid','textgrid'),item('internal_email','Internal Email Notification','Communication','Notify a team member','email'),item('send_slack','Send Slack Message','Communication','Send a Slack message','slack',false),item('call','Call','Communication','Place a voice call','voice',false),item('messenger','Facebook Messenger','Communication','Send Messenger message','meta_messaging',false),item('instagram_dm','Instagram DM','Communication','Send Instagram message','meta_messaging',false),item('whatsapp','WhatsApp','Communication','Send WhatsApp message','whatsapp',false),item('reply_comment','Reply in Comments','Communication','Reply to social comment','social_messaging',false),
 item('if_else','If / Else','Logic','Split into YES / NO branches'),item('wait','Wait','Logic','Pause for a duration'),item('wait_until','Wait Until','Logic','Pause until a date/time'),item('go_to','Go To','Logic','Jump to another workflow step'),item('stop_workflow','Stop Workflow','Logic','Stop this enrollment'),item('enroll_workflow','Add to Workflow','Logic','Enroll in another workflow'),item('remove_from_workflow','Remove from Workflow','Logic','Stop another workflow enrollment'),
 item('update_contact','Update Contact Field','CRM','Update CRM contact data'),item('add_tag','Add Contact Tag','CRM','Add a tag'),item('remove_tag','Remove Contact Tag','CRM','Remove a tag'),item('update_status','Update Status','CRM','Change CRM status'),item('assign_user','Assign to User','CRM','Assign an owner'),item('remove_assigned_user','Remove Assigned User','CRM','Clear contact owner'),item('set_dnd','Enable / Disable DND','CRM','Change DND'),item('engagement_score','Modify Engagement Score','CRM','Set engagement score'),item('add_note','Add Note','CRM','Append CRM note'),item('create_task','Create Task','CRM','Create follow-up task'),item('copy_contact','Create / Copy Contact','CRM','Create another CRM contact'),item('delete_contact','Delete Contact','CRM','Delete current contact'),item('update_custom_value','Update Custom Value','CRM','Set a custom value'),item('text_formatter','Text Formatter','CRM','Transform text'),
 item('outbound_webhook','Webhook / Custom Webhook','Send Data','Send workflow data to another system'),item('google_sheets','Google Sheets','Send Data','Write a row to Google Sheets','google_sheets',false),
 item('ai_generate','AI Prompt','Workflow AI','Generate workflow text','openai'),item('ai_decision','AI Decision Maker','Workflow AI','Make a workflow decision','openai'),item('ai_detect_intent','AI Intent Detection','Workflow AI','Classify intent','openai'),item('ai_summarize','AI Summarize','Workflow AI','Summarize context','openai'),item('ai_translate','AI Translate','Workflow AI','Translate text','openai'),item('ai_extract','AI Extract Data','Workflow AI','Extract structured facts','openai'),
 item('create_appointment','Create Appointment','Appointments','Create a native Indie Cut appointment'),item('update_appointment','Update Appointment','Appointments','Update a native Indie Cut appointment'),item('create_opportunity','Create Opportunity','Opportunities','Create a native Indie Cut opportunity'),item('update_opportunity','Move / Update Opportunity','Opportunities','Move or update a native opportunity'),
 item('create_payment_link','Create Payment Link','Payments','Create processor-hosted payment request','payments',false),item('refund_payment','Refund Payment','Payments','Refund through payment processor','payments',false),item('stripe_charge','Stripe One-Time Charge','Payments','Charge through Stripe','stripe',false),item('send_documents','Send Document / Contract','Documents','Send signature document','documents',false),item('voicemail_drop','Voicemail Drop','Calls','Send voicemail','voice',false),
 item('facebook_audience_add','Add to Meta Custom Audience','Advertising','Add contact to Meta audience','meta_ads',false),item('facebook_audience_remove','Remove from Meta Custom Audience','Advertising','Remove contact from Meta audience','meta_ads',false),item('facebook_capi','Meta Conversion API','Advertising','Send server-side Meta event','meta_ads',false),item('tiktok_audience','TikTok Audience Action','Advertising','Manage TikTok audience','tiktok_ads',false)
];
const STATUSES=['lead','pending','approved','active','rejected','inactive'];
const FIELDS=[['artist_name','Artist name'],['full_name','Full name'],['email','Email'],['phone','Phone'],['genre','Genre'],['city','City / State'],['source','Source'],['notes','Notes'],['birthday','Birthday'],['engagement_score','Engagement score']];
const COND=[['status','Status'],['genre','Genre'],['tag','Tag'],['city','City / State'],['source','Source'],['email_opt_in','Email opt-in'],['sms_opt_in','SMS opt-in'],['dnd','DND'],['email','Email'],['phone','Phone'],['engagement_score','Engagement score']];
const OPS=[['equals','Equals'],['not_equals','Does not equal'],['contains','Contains'],['not_contains','Does not contain'],['exists','Exists'],['not_exists','Does not exist'],['gt','Greater than'],['gte','Greater or equal'],['lt','Less than'],['lte','Less or equal']];
const blank={name:'Untitled Workflow',description:'',trigger_type:'manual',trigger_config:{},status:'draft'};
const groups=list=>Array.from(new Set(list.map(x=>x.category)));
const find=(list,id)=>list.find(x=>x.id===id);
const ready=(x,integrations)=>!!x&&x.native!==false&&(!x.requires||!!integrations?.[x.requires]);
const cfg=type=>type==='send_sms'?{message:''}:type==='send_email'?{subject:'',message:''}:type==='internal_email'?{to:'',subject:'Indie Cut workflow notification',message:''}:type==='if_else'?{field:'status',operator:'equals',value:'approved',yes_steps:[],no_steps:[]}:type==='wait'?{amount:1,unit:'hours'}:type==='wait_until'?{datetime:''}:['add_tag','remove_tag'].includes(type)?{tag:''}:type==='update_status'?{status:'active'}:type==='update_contact'?{field:'genre',value:''}:type==='assign_user'?{user:''}:type==='set_dnd'?{value:true}:type==='engagement_score'?{value:0}:type==='add_note'?{note:''}:type==='create_task'?{title:'Follow up with {{artist_name}}',notes:'',due_hours:24}:type==='copy_contact'?{artist_name:'{{artist_name}} Copy',email:'',phone:''}:['enroll_workflow','remove_from_workflow'].includes(type)?{workflow_id:''}:type==='go_to'?{step_index:0}:type==='outbound_webhook'?{url:'',method:'POST',secret:'',body_template:''}:type==='update_custom_value'?{key:'',value:''}:type==='text_formatter'?{input:'',operation:'trim'}:type.startsWith('ai_')?{input:'{{notes}}',instruction:'',save_to:'notes',language:'Spanish'}:['create_appointment','update_appointment'].includes(type)?{title:'Appointment',status:'scheduled',starts_at:''}:['create_opportunity','update_opportunity'].includes(type)?{title:'Opportunity',status:'open',stage:'new',amount:''}:{};
async function req(action,extra={}){const r=await fetch('/api/admin/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Automation request failed');return j}

export default function AutomationBuilderV4(){
 const[data,setData]=useState({workflows:[],steps:[],contacts:[],enrollments:[],smsStats:{},integrations:{}}),[tags,setTags]=useState([]),[tab,setTab]=useState('builder'),[workflow,setWorkflow]=useState({...blank}),[steps,setSteps]=useState([]),[selected,setSelected]=useState(null),[insertAt,setInsertAt]=useState(0),[msg,setMsg]=useState(''),[busy,setBusy]=useState(''),[newTag,setNewTag]=useState(''),[historyWorkflow,setHistoryWorkflow]=useState(''),[enrollContact,setEnrollContact]=useState(''),[directSms,setDirectSms]=useState({contactId:'',message:''});
 async function load(){try{const[r,t]=await Promise.all([fetch('/api/admin/automation',{cache:'no-store'}),fetch('/api/admin/tags',{cache:'no-store'})]),j=await r.json(),tj=await t.json();if(!r.ok)throw new Error(j.error);setData(j);setTags(tj.tags||[]);if(!workflow.id&&j.workflows?.length)open(j.workflows[0],j)}catch(e){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 function open(w,source=data){const list=(source.steps||[]).filter(x=>x.workflow_id===w.id).sort((a,b)=>a.step_order-b.step_order).map(x=>({step_type:x.step_type,step_config:x.step_config||{}}));setWorkflow({...w,trigger_config:w.trigger_config||{}});setSteps(list);setSelected(null);setInsertAt(list.length)}
 async function run(key,action,extra={}){setBusy(key);setMsg('');try{const j=await req(action,extra);setData(j);return j}catch(e){setMsg(e.message)}finally{setBusy('')}}
 async function save(){const j=await run('save','save_workflow',{workflow,steps});if(j){const w=(j.workflows||[]).find(x=>x.name===workflow.name)||j.workflows?.[0];if(w)open(w,j);setMsg('Workflow saved.')}}
 async function publish(){if(!workflow.id)return setMsg('Save the workflow first.');const j=await run('publish','publish_workflow',{workflowId:workflow.id,publish:workflow.status!=='published'});if(j){const w=(j.workflows||[]).find(x=>x.id===workflow.id);if(w)open(w,j)}}
 function add(type){const x=find(ACTIONS,type);if(!ready(x,data.integrations))return setMsg(`${x?.label||type} needs ${x?.requires||'its outside provider/module'} connected first.`);const i=Math.max(0,Math.min(insertAt,steps.length)),next={step_type:type,step_config:cfg(type)};setSteps(v=>{const c=[...v];c.splice(i,0,next);return c});setSelected(i);setInsertAt(i+1)}
 function patch(i,p){setSteps(v=>v.map((s,n)=>n===i?{...s,step_config:{...(s.step_config||{}),...p}}:s))}
 const current=selected===null||selected<0?null:steps[selected],history=useMemo(()=>historyWorkflow?(data.enrollments||[]).filter(e=>e.workflow_id===historyWorkflow):(data.enrollments||[]),[data.enrollments,historyWorkflow]);
 return <section className={styles.shell}>
  <div className={styles.topbar}><div className={styles.topTitle}><h2>Indie Cut Workflows</h2><span className={`${styles.badge} ${!data.integrations?.textgrid?styles.badgeOff:''}`}>{data.integrations?.textgrid?'TEXTGRID CONNECTED':'TEXTGRID NOT CONNECTED'}</span></div><div className={styles.tabs}>{[['builder','Builder'],['library','Trigger + Action Library'],['tags',`Tags (${tags.length})`],['sms','SMS'],['history',`Enrollment History (${history.length})`]].map(([id,label])=><button key={id} className={`${styles.tab} ${tab===id?styles.tabActive:''}`} onClick={()=>setTab(id)}>{label}</button>)}</div></div>
  {msg&&<div className={styles.message}>{msg}</div>}
  {tab==='builder'&&<div className={styles.workspace}>
   <aside className={styles.left}><div className={styles.leftHead}><strong>WORKFLOWS</strong><button className={styles.newButton} onClick={()=>{setWorkflow({...blank});setSteps([]);setSelected(null)}}>＋ New</button></div><div className={styles.workflowList}>{(data.workflows||[]).map(w=><button key={w.id} className={`${styles.workflowItem} ${workflow.id===w.id?styles.workflowActive:''}`} onClick={()=>open(w)}><span className={styles.workflowName}>{w.name}</span><span className={styles.workflowMeta}><span>{find(TRIGGERS,w.trigger_type)?.label||w.trigger_type}</span><span>{w.status}</span></span></button>)}</div></aside>
   <main className={styles.canvasWrap}><div className={styles.canvasHead}><div><input className={styles.nameInput} value={workflow.name||''} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/><div className={styles.tiny}>{workflow.status==='published'?'PUBLISHED — LIVE AUTOMATION':'DRAFT — NOT RUNNING'}</div></div><div className={styles.actions}><button className={styles.ghost} onClick={save}>{busy==='save'?'Saving…':'Save'}</button><button className={styles.primary} onClick={publish}>{workflow.status==='published'?'Unpublish':'Publish'}</button></div></div><div className={styles.flow}>
    <div className={`${styles.node} ${styles.nodeTrigger}`} onClick={()=>setSelected(-1)}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={`${styles.icon} ${styles.triggerIcon}`}>⚡</span><div><div className={styles.nodeTitle}>Trigger</div><div className={styles.nodeSub}>{find(TRIGGERS,workflow.trigger_type)?.label||workflow.trigger_type}</div></div></div></div></div>
    {steps.map((s,i)=><div key={i} style={{width:'100%',display:'flex',flexDirection:'column',alignItems:'center'}}><div className={styles.connector}/><button className={styles.plus} onClick={()=>{setInsertAt(i);setSelected(null)}}>+</button><div className={styles.connector}/><div className={`${styles.node} ${styles.nodeAction}`} onClick={()=>{setSelected(i);setInsertAt(i+1)}}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={styles.icon}>•</span><div><div className={styles.nodeTitle}>{find(ACTIONS,s.step_type)?.label||s.step_type}</div><div className={styles.nodeSub}>{summary(s)}</div></div></div><button className={styles.danger} onClick={e=>{e.stopPropagation();setSteps(v=>v.filter((_,n)=>n!==i));setSelected(null)}}>×</button></div></div></div>)}
    <div className={styles.connector}/><button className={styles.plus} onClick={()=>{setInsertAt(steps.length);setSelected(null)}}>+</button><div className={styles.connector}/><div className={styles.tiny}>END</div>
   </div></main>
   <aside className={styles.right}>{selected===-1?<TriggerEditor workflow={workflow} setWorkflow={setWorkflow} tags={tags} integrations={data.integrations}/>:current?<StepEditor step={current} tags={tags} workflows={data.workflows||[]} onChange={p=>patch(selected,p)}/>:<Picker data={data} add={add} workflow={workflow} enrollContact={enrollContact} setEnrollContact={setEnrollContact} onEnroll={async()=>{if(workflow.id&&enrollContact){await run('enroll','enroll_contact',{workflowId:workflow.id,contactId:enrollContact});setEnrollContact('')}}}/>}</aside>
  </div>}
  {tab==='library'&&<div className={styles.smsGrid}><Catalog title="All Triggers" list={TRIGGERS} integrations={data.integrations}/><Catalog title="All Actions" list={ACTIONS} integrations={data.integrations}/></div>}
  {tab==='tags'&&<div className={styles.smsGrid}><div className={styles.panel} style={{gridColumn:'1 / -1'}}><h3>CRM Tags</h3><div style={{display:'flex',gap:8}}><input className={styles.input} value={newTag} onChange={e=>setNewTag(e.target.value)} placeholder="e.g. finalist, VIP"/><button className={styles.primary} onClick={async()=>{if(!newTag.trim())return;const r=await fetch('/api/admin/tags',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create_tag',name:newTag.trim()})}),j=await r.json();if(r.ok){setTags(j.tags||[]);setNewTag('')}}}>Create Tag</button></div>{tags.map(t=><div className={styles.row} key={t.id}><strong>{t.name}</strong><button className={styles.danger} onClick={async()=>{const r=await fetch('/api/admin/tags',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete_tag',id:t.id})}),j=await r.json();if(r.ok)setTags(j.tags||[])}>Delete</button></div>)}</div></div>}
  {tab==='sms'&&<div className={styles.smsGrid}><div className={styles.panel}><h3>Direct Text Message</h3><label className={styles.label}>Contact<select className={styles.select} value={directSms.contactId} onChange={e=>setDirectSms({...directSms,contactId:e.target.value})}><option value="">Choose contact…</option>{(data.contacts||[]).filter(c=>c.sms_opt_in&&c.phone).map(c=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.phone}</option>)}</select></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={6} value={directSms.message} onChange={e=>setDirectSms({...directSms,message:e.target.value})}/></label><button className={styles.primary} disabled={!data.integrations?.textgrid} onClick={async()=>{await run('sms','send_sms',{contactId:directSms.contactId,message:directSms.message});setDirectSms({contactId:'',message:''})}}>Send Text</button></div><div className={styles.panel}><div className={styles.statGrid}><div className={styles.stat}><b>{data.smsStats?.queued||0}</b><span>Queued</span></div><div className={styles.stat}><b>{data.smsStats?.sent||0}</b><span>Sent</span></div><div className={styles.stat}><b>{data.smsStats?.failed||0}</b><span>Failed</span></div></div></div></div>}
  {tab==='history'&&<div className={styles.smsGrid}><div className={styles.panel} style={{gridColumn:'1 / -1'}}><h3>Workflow Enrollment History</h3><label className={styles.label}>Workflow<select className={styles.select} value={historyWorkflow} onChange={e=>setHistoryWorkflow(e.target.value)}><option value="">All workflows</option>{(data.workflows||[]).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{history.map(e=>{const c=(data.contacts||[]).find(x=>x.id===e.contact_id),w=(data.workflows||[]).find(x=>x.id===e.workflow_id);return <div className={styles.row} key={e.id}><div><strong>{c?.artist_name||c?.full_name||c?.email||'Unknown contact'}</strong><div className={styles.tiny}>{w?.name} · {e.context?.trigger_type||w?.trigger_type} · step {e.current_step||0}</div>{e.last_error&&<div className={styles.tiny} style={{color:'#b42318'}}>{e.last_error}</div>}</div><span className={styles.badge}>{e.status}</span></div>})}</div></div>}
 </section>
}

function summary(s){const c=s.step_config||{};if(s.step_type==='send_email')return c.subject||'Compose email';if(s.step_type==='send_sms')return c.message||'Compose SMS';if(s.step_type==='if_else')return `If ${c.field||'status'} ${c.operator||'equals'} ${c.value??''}`;if(s.step_type==='wait')return `${c.amount||1} ${c.unit||'hours'}`;if(s.step_type==='wait_until')return c.datetime||'Choose date/time';if(['add_tag','remove_tag'].includes(s.step_type))return c.tag||'Choose tag';if(['create_opportunity','update_opportunity','create_appointment','update_appointment'].includes(s.step_type))return c.title||find(ACTIONS,s.step_type)?.description;return find(ACTIONS,s.step_type)?.description||''}
function Catalog({title,list,integrations}){return <div className={styles.panel}><h3>{title}</h3><p className={styles.muted}>Green means the action or trigger can run now. Red means the workflow definition exists but a separate outside provider or permission is still required.</p>{groups(list).map(g=><div key={g}><div className={styles.sectionTitle}>{g}</div>{list.filter(x=>x.category===g).map((x,i)=>{const ok=ready(x,integrations);return <div className={styles.integrationCard} key={`${x.id}-${i}`}><span className={ok?styles.dotOn:styles.dotOff}/><div><strong>{x.label}</strong><div className={styles.muted}>{x.description}</div><div className={styles.tiny}>{ok?'AVAILABLE NOW':`REQUIRES ${String(x.requires||'EXTERNAL MODULE').toUpperCase()}`}</div></div></div>})}</div>)}</div>}
function Picker({data,add,workflow,enrollContact,setEnrollContact,onEnroll}){return <><h3>Add an Action</h3><p className={styles.muted}>Green actions execute now. Red actions stay visible until their outside provider/API is connected.</p>{groups(ACTIONS).map(g=><div key={g}><div className={styles.sectionTitle}>{g}</div><div className={styles.library}>{ACTIONS.filter(x=>x.category===g).map((x,i)=>{const ok=ready(x,data.integrations);return <button className={styles.libraryButton} disabled={!ok} style={{opacity:ok?1:.48}} key={`${x.id}-${i}`} onClick={()=>ok&&add(x.id)}><span className={ok?styles.dotOn:styles.dotOff}/><span>{x.label}<div className={styles.tiny}>{ok?x.description:`${x.description} · connect ${x.requires||'provider'}`}</div></span></button>})}</div></div>)}{workflow.id&&<><div className={styles.sectionTitle}>TEST / MANUAL ENROLL</div><select className={styles.select} value={enrollContact} onChange={e=>setEnrollContact(e.target.value)}><option value="">Choose contact…</option>{(data.contacts||[]).map(c=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.email||c.phone}</option>)}</select><button className={styles.primary} disabled={!enrollContact} onClick={onEnroll}>Enroll Contact</button></>}</>}
function TriggerEditor({workflow,setWorkflow,tags,integrations}){const x=find(TRIGGERS,workflow.trigger_type);return <><h3>Workflow Trigger</h3><label className={styles.label}>Trigger<select className={styles.select} value={workflow.trigger_type||'manual'} onChange={e=>{const next=find(TRIGGERS,e.target.value);if(!ready(next,integrations))return alert(`${next.label} requires ${next.requires||'an outside provider'}.`);setWorkflow({...workflow,trigger_type:e.target.value,trigger_config:{}})}}>{groups(TRIGGERS).map(g=><optgroup label={g} key={g}>{TRIGGERS.filter(x=>x.category===g).map((x,i)=><option key={`${x.id}-${i}`} value={x.id} disabled={!ready(x,integrations)}>{x.label}{!ready(x,integrations)?' — connect first':''}</option>)}</optgroup>)}</select></label>{x&&!ready(x,integrations)&&<div className={styles.message}>This trigger is defined, but {x.requires||'its outside provider'} must be connected before events can arrive.</div>}{workflow.trigger_type==='status_changed'&&<select className={styles.select} value={workflow.trigger_config?.status||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,status:e.target.value}})}><option value="">Any status</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select>}{['tag_added','tag_removed'].includes(workflow.trigger_type)&&<select className={styles.select} value={workflow.trigger_config?.tag||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,tag:e.target.value}})}><option value="">Any tag</option>{tags.map(t=><option key={t.id} value={t.name}>{t.name}</option>)}</select>}{workflow.trigger_type==='scheduled'&&<><select className={styles.select} value={workflow.trigger_config?.recurrence||'daily'} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,recurrence:e.target.value}})}><option value="once">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><input className={styles.input} type="datetime-local" value={workflow.trigger_config?.run_at||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,run_at:e.target.value}})}/></>}{workflow.trigger_type==='stale_opportunities'&&<input className={styles.input} type="number" min="1" value={workflow.trigger_config?.days||7} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,days:Number(e.target.value)}})}/>} {workflow.trigger_type==='vote_received'&&<input className={styles.input} type="number" min="1" value={workflow.trigger_config?.min_votes||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,min_votes:Number(e.target.value)||null}})} placeholder="Minimum votes (optional)"/>}</>}
function StepEditor({step,tags,workflows,onChange}){const c=step.step_config||{},type=step.step_type;return <><h3>{find(ACTIONS,type)?.label||type}</h3><p className={styles.muted}>{find(ACTIONS,type)?.description}</p><div className={styles.form}>
 {type==='send_sms'&&<textarea className={styles.textarea} rows={6} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/>} {type==='send_email'&&<><input className={styles.input} value={c.subject||''} onChange={e=>onChange({subject:e.target.value})} placeholder="Subject"/><textarea className={styles.textarea} rows={6} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></>} {type==='internal_email'&&<><input className={styles.input} value={c.to||''} onChange={e=>onChange({to:e.target.value})} placeholder="Team email"/><input className={styles.input} value={c.subject||''} onChange={e=>onChange({subject:e.target.value})}/><textarea className={styles.textarea} rows={5} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></>}
 {type==='if_else'&&<IfElse c={c} tags={tags} onChange={onChange}/>} {type==='wait'&&<><input className={styles.input} type="number" min="1" value={c.amount||1} onChange={e=>onChange({amount:Number(e.target.value)})}/><select className={styles.select} value={c.unit||'hours'} onChange={e=>onChange({unit:e.target.value})}><option>minutes</option><option>hours</option><option>days</option></select></>} {type==='wait_until'&&<input className={styles.input} type="datetime-local" value={c.datetime||''} onChange={e=>onChange({datetime:e.target.value})}/>} {type==='go_to'&&<input className={styles.input} type="number" min="0" value={c.step_index||0} onChange={e=>onChange({step_index:Number(e.target.value)})}/>} 
 {['add_tag','remove_tag'].includes(type)&&<select className={styles.select} value={c.tag||''} onChange={e=>onChange({tag:e.target.value})}><option value="">Choose tag…</option>{tags.map(t=><option key={t.id} value={t.name}>{t.name}</option>)}</select>} {type==='update_status'&&<select className={styles.select} value={c.status||'active'} onChange={e=>onChange({status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select>} {type==='update_contact'&&<><select className={styles.select} value={c.field||'genre'} onChange={e=>onChange({field:e.target.value})}>{FIELDS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input className={styles.input} value={c.value||''} onChange={e=>onChange({value:e.target.value})}/></>} {type==='assign_user'&&<input className={styles.input} value={c.user||''} onChange={e=>onChange({user:e.target.value})} placeholder="Assigned user"/>} {type==='set_dnd'&&<select className={styles.select} value={String(c.value??true)} onChange={e=>onChange({value:e.target.value==='true'})}><option value="true">Enable DND</option><option value="false">Disable DND</option></select>} {type==='engagement_score'&&<input className={styles.input} type="number" value={c.value||0} onChange={e=>onChange({value:Number(e.target.value)})}/>} {type==='add_note'&&<textarea className={styles.textarea} rows={5} value={c.note||''} onChange={e=>onChange({note:e.target.value})}/>} {type==='create_task'&&<><input className={styles.input} value={c.title||''} onChange={e=>onChange({title:e.target.value})}/><textarea className={styles.textarea} rows={4} value={c.notes||''} onChange={e=>onChange({notes:e.target.value})}/><input className={styles.input} type="number" value={c.due_hours||24} onChange={e=>onChange({due_hours:Number(e.target.value)})}/></>}
 {type==='copy_contact'&&<><input className={styles.input} value={c.artist_name||''} onChange={e=>onChange({artist_name:e.target.value})} placeholder="New contact name"/><input className={styles.input} value={c.email||''} onChange={e=>onChange({email:e.target.value})} placeholder="New email"/><input className={styles.input} value={c.phone||''} onChange={e=>onChange({phone:e.target.value})} placeholder="New phone"/></>} {type==='update_custom_value'&&<><input className={styles.input} value={c.key||''} onChange={e=>onChange({key:e.target.value})} placeholder="Custom field key"/><input className={styles.input} value={c.value||''} onChange={e=>onChange({value:e.target.value})} placeholder="Value"/></>} {type==='text_formatter'&&<><textarea className={styles.textarea} rows={4} value={c.input||''} onChange={e=>onChange({input:e.target.value})}/><select className={styles.select} value={c.operation||'trim'} onChange={e=>onChange({operation:e.target.value})}><option value="trim">Trim</option><option value="uppercase">Uppercase</option><option value="lowercase">Lowercase</option><option value="titlecase">Title Case</option></select></>}
 {['enroll_workflow','remove_from_workflow'].includes(type)&&<select className={styles.select} value={c.workflow_id||''} onChange={e=>onChange({workflow_id:e.target.value})}><option value="">Choose workflow…</option>{workflows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>} {type==='outbound_webhook'&&<><input className={styles.input} value={c.url||''} onChange={e=>onChange({url:e.target.value})} placeholder="https://..."/><select className={styles.select} value={c.method||'POST'} onChange={e=>onChange({method:e.target.value})}><option>POST</option><option>PUT</option><option>PATCH</option></select><textarea className={styles.textarea} rows={4} value={c.body_template||''} onChange={e=>onChange({body_template:e.target.value})} placeholder={'{"artist":"{{artist_name}}"}'}/></>}
 {type.startsWith('ai_')&&<><textarea className={styles.textarea} rows={5} value={c.input||''} onChange={e=>onChange({input:e.target.value})}/><textarea className={styles.textarea} rows={3} value={c.instruction||''} onChange={e=>onChange({instruction:e.target.value})}/>{type==='ai_translate'&&<input className={styles.input} value={c.language||'Spanish'} onChange={e=>onChange({language:e.target.value})}/>}<select className={styles.select} value={c.save_to||'notes'} onChange={e=>onChange({save_to:e.target.value})}><option value="notes">Save to notes</option><option value="source">Save to source</option><option value="status">Save to status</option></select></>}
 {['create_appointment','update_appointment'].includes(type)&&<><input className={styles.input} value={c.title||''} onChange={e=>onChange({title:e.target.value})} placeholder="Appointment title"/><input className={styles.input} type="datetime-local" value={c.starts_at||''} onChange={e=>onChange({starts_at:e.target.value})}/><input className={styles.input} value={c.status||''} onChange={e=>onChange({status:e.target.value})} placeholder="Status"/></>} {['create_opportunity','update_opportunity'].includes(type)&&<><input className={styles.input} value={c.title||''} onChange={e=>onChange({title:e.target.value})} placeholder="Opportunity title"/><input className={styles.input} value={c.stage||''} onChange={e=>onChange({stage:e.target.value})} placeholder="Pipeline stage"/><input className={styles.input} value={c.status||''} onChange={e=>onChange({status:e.target.value})} placeholder="Status"/><input className={styles.input} type="number" value={c.amount||''} onChange={e=>onChange({amount:e.target.value})} placeholder="Amount"/></>}
 <div className={styles.tiny}>Merge fields: {'{{artist_name}}'}, {'{{first_name}}'}, {'{{genre}}'}, {'{{city}}'}, {'{{email}}'}, {'{{phone}}'}, {'{{notes}}'}</div></div></>}
function IfElse({c,tags,onChange}){const branch=(key,label)=>{const list=Array.isArray(c[key])?c[key]:[],allowed=ACTIONS.filter(x=>['send_sms','send_email','add_tag','remove_tag','update_status','update_contact','add_note','create_task','outbound_webhook','create_appointment','create_opportunity','update_opportunity'].includes(x.id));return <div className={styles.panel} style={{padding:10}}><strong>{label}</strong>{list.map((s,i)=><div key={i} className={styles.row}><span>{find(ACTIONS,s.step_type)?.label}</span><button className={styles.danger} onClick={()=>onChange({[key]:list.filter((_,n)=>n!==i)})}>Remove</button></div>)}<select className={styles.select} value="" onChange={e=>{if(e.target.value)onChange({[key]:[...list,{step_type:e.target.value,step_config:cfg(e.target.value)}]})}}><option value="">＋ Add branch action</option>{allowed.map((x,i)=><option key={`${x.id}-${i}`} value={x.id}>{x.label}</option>)}</select></div>};return <><select className={styles.select} value={c.field||'status'} onChange={e=>onChange({field:e.target.value,value:''})}>{COND.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select className={styles.select} value={c.operator||'equals'} onChange={e=>onChange({operator:e.target.value})}>{OPS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>{!['exists','not_exists'].includes(c.operator)&&<input className={styles.input} value={c.value??''} onChange={e=>onChange({value:e.target.value})}/>} {branch('yes_steps','YES — condition matches')}{branch('no_steps','NO — condition does not match')}</>}
