'use client';

import {useEffect,useMemo,useState} from 'react';
import styles from './AutomationBuilder.module.css';

const TRIGGERS=[
 ['manual','Manual Enrollment','Start when you manually add a contact'],
 ['contact_created','Contact Added','Start when a new CRM contact is created'],
 ['status_changed','Contact Status Changed','Start when a contact moves to a selected status'],
 ['tag_added','Tag Added','Start when a selected tag is added'],
 ['sms_reply','Customer Replied by SMS','Start when TextGrid receives a reply'],
 ['battle_submission_approved','Battle Submission Approved','Start after an artist is approved for Phase One']
];
const ACTIONS=[
 ['send_sms','Send SMS','Text an opted-in contact with TextGrid','SMS'],
 ['send_email','Send Email','Send an email through Indie Cut','✉'],
 ['wait','Wait','Pause before the next step','◷'],
 ['add_tag','Add Tag','Add a CRM tag to the contact','#'],
 ['update_status','Update Status','Move the contact to another CRM status','↻'],
 ['create_task','Create Task','Create a follow-up task','✓']
];
const GENRES=['Hip-Hop','R&B','Gospel','Southern Soul','Pop','Rock','Country','Afrobeats','Reggae / Dancehall','Latin','Electronic / Dance','Jazz','Soul','Alternative','Blues','Folk'];
const STATUSES=['lead','pending','approved','active','rejected','inactive'];
const emptyWorkflow={name:'Untitled Workflow',description:'',trigger_type:'manual',trigger_config:{},status:'draft'};
const emptySmsTemplate={name:'',body:'',active:true};
const emptySmsCampaign={name:'',body:'',filter_status:'',filter_genre:'',scheduled_at:''};

async function request(action:string,extra:any={}){const r=await fetch('/api/admin/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Automation request failed');return j}
function triggerLabel(type:string){return TRIGGERS.find(x=>x[0]===type)?.[1]||type}
function actionMeta(type:string){return ACTIONS.find(x=>x[0]===type)||[type,type,'','•']}
function stepSummary(step:any){const c=step.step_config||{};if(step.step_type==='send_sms')return c.message||'Compose SMS message';if(step.step_type==='send_email')return c.subject||'Compose email';if(step.step_type==='wait')return `${c.amount||1} ${c.unit||'hours'}`;if(step.step_type==='add_tag')return c.tag?`Tag: ${c.tag}`:'Choose tag';if(step.step_type==='update_status')return c.status?`Set status to ${c.status}`:'Choose status';if(step.step_type==='create_task')return c.title||'Create a follow-up task';return ''}

export default function AutomationBuilder(){
 const [data,setData]=useState<any>({workflows:[],steps:[],smsTemplates:[],smsCampaigns:[],contacts:[],enrollments:[],smsStats:{},integrations:{}});
 const [tab,setTab]=useState<'builder'|'sms'|'history'>('builder');
 const [workflow,setWorkflow]=useState<any>({...emptyWorkflow});const [steps,setSteps]=useState<any[]>([]);const [selectedStep,setSelectedStep]=useState<number|null>(null);const [insertAt,setInsertAt]=useState(0);
 const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const [smsTemplate,setSmsTemplate]=useState<any>({...emptySmsTemplate});const [smsCampaign,setSmsCampaign]=useState<any>({...emptySmsCampaign});
 const [directSms,setDirectSms]=useState({contactId:'',message:''});const [enrollContact,setEnrollContact]=useState('');
 async function load(){try{const r=await fetch('/api/admin/automation',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load automation');setData(j);if(!workflow.id&&j.workflows?.length)openWorkflow(j.workflows[0],j)}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 function openWorkflow(w:any,source=data){const loaded=(source.steps||[]).filter((x:any)=>x.workflow_id===w.id).sort((a:any,b:any)=>a.step_order-b.step_order).map((x:any)=>({step_type:x.step_type,step_config:x.step_config||{}}));setWorkflow({...w,trigger_config:w.trigger_config||{}});setSteps(loaded);setSelectedStep(null);setInsertAt(loaded.length)}
 function newWorkflow(){setWorkflow({...emptyWorkflow});setSteps([]);setSelectedStep(null);setInsertAt(0)}
 async function run(key:string,action:string,extra:any={}){setBusy(key);setMessage('');try{const j=await request(action,extra);setData(j);setMessage('Saved.');return j}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function saveWorkflow(){const j=await run('save','save_workflow',{workflow,steps});if(j){const match=(j.workflows||[]).find((x:any)=>x.name===workflow.name)||j.workflows?.[0];if(match)openWorkflow(match,j)}}
 async function publish(){if(!workflow.id){setMessage('Save the workflow before publishing it.');return}const j=await run('publish','publish_workflow',{workflowId:workflow.id,publish:workflow.status!=='published'});if(j){const next=(j.workflows||[]).find((x:any)=>x.id===workflow.id);if(next)openWorkflow(next,j)}}
 function openActionPicker(index:number){setInsertAt(Math.max(0,Math.min(index,steps.length)));setSelectedStep(null)}
 function addStep(type:string){const config=type==='send_sms'?{message:''}:type==='send_email'?{subject:'',message:''}:type==='wait'?{amount:1,unit:'hours'}:type==='add_tag'?{tag:''}:type==='update_status'?{status:'active'}:{title:'Follow up with {{artist_name}}',notes:'',priority:'normal',due_hours:24};const index=Math.max(0,Math.min(insertAt,steps.length));const next={step_type:type,step_config:config};setSteps(v=>{const copy=[...v];copy.splice(index,0,next);return copy});setSelectedStep(index);setInsertAt(index+1)}
 function updateStep(index:number,patch:any){setSteps(v=>v.map((s,i)=>i===index?{...s,step_config:{...(s.step_config||{}),...patch}}:s))}
 function moveStep(index:number,dir:number){setSteps(v=>{const n=index+dir;if(n<0||n>=v.length)return v;const copy=[...v];[copy[index],copy[n]]=[copy[n],copy[index]];return copy});setSelectedStep(i=>i===index?index+dir:i===index+dir?index:i)}
 function deleteStep(index:number){setSteps(v=>v.filter((_,i)=>i!==index));setSelectedStep(null);setInsertAt(i=>Math.max(0,Math.min(i,Math.max(0,steps.length-1))))}
 async function deleteWorkflow(){if(!workflow.id||!confirm('Delete this workflow?'))return;const j=await run('delete','delete_workflow',{workflowId:workflow.id});if(j)newWorkflow()}
 async function enroll(){if(!workflow.id||!enrollContact)return;const j=await run('enroll','enroll_contact',{workflowId:workflow.id,contactId:enrollContact});if(j)setEnrollContact('')}
 async function sendDirectSms(){if(!directSms.contactId||!directSms.message.trim())return;const j=await run('direct-sms','send_sms',{contactId:directSms.contactId,message:directSms.message});if(j)setDirectSms({contactId:'',message:''})}
 async function saveSmsTemplate(){const j=await run('sms-template','save_sms_template',{template:smsTemplate});if(j)setSmsTemplate({...emptySmsTemplate})}
 async function queueSmsCampaign(){const j=await run('sms-campaign','queue_sms_campaign',{campaign:smsCampaign});if(j)setSmsCampaign({...emptySmsCampaign})}
 const published=workflow.status==='published';const optedContacts=useMemo(()=>(data.contacts||[]).filter((c:any)=>c.sms_opt_in&&c.phone),[data.contacts]);
 const currentStep=selectedStep===null||selectedStep<0?null:steps[selectedStep];
 const insertLabel=insertAt===0?'after the trigger':insertAt>=steps.length?'at the end':`between steps ${insertAt} and ${insertAt+1}`;

 return <section className={styles.shell}>
  <div className={styles.topbar}><div className={styles.topTitle}><h2>Indie Cut Workflows</h2><span className={`${styles.badge} ${!data.integrations?.textgrid?styles.badgeOff:''}`}>{data.integrations?.textgrid?'TEXTGRID CONNECTED':'TEXTGRID NOT CONNECTED'}</span></div><div className={styles.tabs}><button className={`${styles.tab} ${tab==='builder'?styles.tabActive:''}`} onClick={()=>setTab('builder')}>Builder</button><button className={`${styles.tab} ${tab==='sms'?styles.tabActive:''}`} onClick={()=>setTab('sms')}>SMS</button><button className={`${styles.tab} ${tab==='history'?styles.tabActive:''}`} onClick={()=>setTab('history')}>Enrollment History</button></div></div>
  {message&&<div className={styles.message}>{message}</div>}
  {tab==='builder'&&<div className={styles.workspace}>
   <aside className={styles.left}><div className={styles.leftHead}><strong>WORKFLOWS</strong><button className={styles.newButton} onClick={newWorkflow}>＋ New</button></div><div className={styles.workflowList}>{(data.workflows||[]).map((w:any)=><button key={w.id} className={`${styles.workflowItem} ${workflow.id===w.id?styles.workflowActive:''}`} onClick={()=>openWorkflow(w)}><span className={styles.workflowName}>{w.name}</span><span className={styles.workflowMeta}><span>{triggerLabel(w.trigger_type)}</span><span>{w.status}</span></span></button>)}{!(data.workflows||[]).length&&<div className={styles.empty}>Create your first workflow.</div>}</div></aside>
   <main className={styles.canvasWrap}><div className={styles.canvasHead}><div><input className={styles.nameInput} value={workflow.name||''} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/><div className={styles.tiny}>{published?'PUBLISHED — LIVE AUTOMATION':'DRAFT — NOT RUNNING'}</div></div><div className={styles.actions}><button className={styles.ghost} onClick={saveWorkflow}>{busy==='save'?'Saving…':'Save'}</button><button className={styles.primary} onClick={publish}>{published?'Unpublish':'Publish'}</button>{workflow.id&&<button className={styles.danger} onClick={deleteWorkflow}>Delete</button>}</div></div>
    <div className={styles.flow}><div className={`${styles.node} ${styles.nodeTrigger}`} onClick={()=>setSelectedStep(-1)}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={`${styles.icon} ${styles.triggerIcon}`}>⚡</span><div><div className={styles.nodeTitle}>Trigger</div><div className={styles.nodeSub}>{triggerLabel(workflow.trigger_type)}</div></div></div><span>•••</span></div><div className={styles.nodeBody}>{workflow.trigger_type==='sms_reply'?(workflow.trigger_config?.keyword?`Reply contains “${workflow.trigger_config.keyword}”`:'Any SMS reply'):workflow.trigger_type==='status_changed'?(workflow.trigger_config?.status?`Status becomes ${workflow.trigger_config.status}`:'Any status change'):workflow.trigger_type==='tag_added'?(workflow.trigger_config?.tag?`Tag ${workflow.trigger_config.tag} is added`:'Any tag added'):'Starts the workflow when this event occurs.'}</div></div>
     {steps.map((step:any,i:number)=>{const meta=actionMeta(step.step_type);return <div key={i} style={{width:'100%',display:'flex',flexDirection:'column',alignItems:'center'}}><div className={styles.connector}/><button className={styles.plus} title="Add an action here" aria-label={`Add action before step ${i+1}`} onClick={()=>openActionPicker(i)}>+</button><div className={styles.connector}/><div className={`${styles.node} ${styles.nodeAction}`} onClick={()=>{setSelectedStep(i);setInsertAt(i+1)}}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={styles.icon}>{meta[3]}</span><div><div className={styles.nodeTitle}>{meta[1]}</div><div className={styles.nodeSub}>{stepSummary(step)}</div></div></div><div className={styles.stepTools}><button onClick={e=>{e.stopPropagation();moveStep(i,-1)}}>↑</button><button onClick={e=>{e.stopPropagation();moveStep(i,1)}}>↓</button><button onClick={e=>{e.stopPropagation();deleteStep(i)}}>×</button></div></div></div></div>})}
     <div className={styles.connector}/><button className={styles.plus} title="Add an action here" aria-label="Add action at end of workflow" onClick={()=>openActionPicker(steps.length)}>+</button><div className={styles.connector}/><div className={styles.tiny}>END</div>
    </div>
   </main>
   <aside className={styles.right}>{selectedStep===-1?<><h3>Workflow Trigger</h3><p className={styles.muted}>Choose what starts this automation.</p><div className={styles.form}><label className={styles.label}>Trigger<select className={styles.select} value={workflow.trigger_type||'manual'} onChange={e=>setWorkflow({...workflow,trigger_type:e.target.value,trigger_config:{}})}>{TRIGGERS.map(t=><option key={t[0]} value={t[0]}>{t[1]}</option>)}</select></label>{workflow.trigger_type==='sms_reply'&&<label className={styles.label}>Optional keyword<input className={styles.input} value={workflow.trigger_config?.keyword||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,keyword:e.target.value}})} placeholder="vote, yes, interested"/></label>}{workflow.trigger_type==='status_changed'&&<label className={styles.label}>New status<select className={styles.select} value={workflow.trigger_config?.status||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,status:e.target.value}})}><option value="">Any status</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label>}{workflow.trigger_type==='tag_added'&&<label className={styles.label}>Tag<input className={styles.input} value={workflow.trigger_config?.tag||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,tag:e.target.value}})}/></label>}</div></>:currentStep?<><button className={styles.ghost} style={{marginBottom:12}} onClick={()=>openActionPicker(selectedStep!+1)}>＋ Add next action</button><StepEditor step={currentStep} onChange={(patch:any)=>updateStep(selectedStep!,patch)}/></>:<><h3>Add an Action</h3><p className={styles.muted}>Choose what should happen {insertLabel}. Clicking an action adds it immediately to the workflow.</p><div className={styles.sectionTitle}>MESSAGING</div><div className={styles.library}>{ACTIONS.slice(0,2).map(a=><button className={styles.libraryButton} key={a[0]} onClick={()=>addStep(a[0])}><span className={styles.icon}>{a[3]}</span><span>{a[1]}<div className={styles.tiny}>{a[2]}</div></span></button>)}</div><div className={styles.sectionTitle}>WORKFLOW</div><div className={styles.library}>{ACTIONS.slice(2).map(a=><button className={styles.libraryButton} key={a[0]} onClick={()=>addStep(a[0])}><span className={styles.icon}>{a[3]}</span><span>{a[1]}<div className={styles.tiny}>{a[2]}</div></span></button>)}</div>{workflow.id&&<><div className={styles.sectionTitle}>TEST / MANUAL ENROLL</div><label className={styles.label}>Contact<select className={styles.select} value={enrollContact} onChange={e=>setEnrollContact(e.target.value)}><option value="">Choose contact…</option>{(data.contacts||[]).map((c:any)=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.email||c.phone}</option>)}</select></label><button className={styles.primary} style={{marginTop:8}} disabled={!enrollContact} onClick={enroll}>Enroll Contact</button></>}</>}</aside>
  </div>}
  {tab==='sms'&&<div className={styles.smsGrid}><div className={styles.panel}><h3>Direct Text Message</h3><p className={styles.muted}>Send a one-to-one SMS to an opted-in artist through TextGrid.</p><label className={styles.label}>Contact<select className={styles.select} value={directSms.contactId} onChange={e=>setDirectSms({...directSms,contactId:e.target.value})}><option value="">Choose opted-in contact…</option>{optedContacts.map((c:any)=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.phone} · {c.phone}</option>)}</select></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={6} value={directSms.message} onChange={e=>setDirectSms({...directSms,message:e.target.value})} placeholder="Hey {{artist_name}}, voting is now open…"/></label><button className={styles.primary} disabled={!data.integrations?.textgrid||!directSms.contactId||!directSms.message.trim()} onClick={sendDirectSms}>{busy==='direct-sms'?'Sending…':'Send Text'}</button>{!data.integrations?.textgrid&&<div className={styles.message}>Add TEXTGRID_ACCOUNT_SID, TEXTGRID_AUTH_TOKEN and TEXTGRID_FROM_NUMBER in Vercel to activate sending.</div>}</div>
   <div className={styles.panel}><h3>SMS Templates</h3><label className={styles.label}>Template name<input className={styles.input} value={smsTemplate.name||''} onChange={e=>setSmsTemplate({...smsTemplate,name:e.target.value})}/></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={smsTemplate.body||''} onChange={e=>setSmsTemplate({...smsTemplate,body:e.target.value})}/></label><button className={styles.primary} onClick={saveSmsTemplate}>Save Template</button><div style={{marginTop:14}}>{(data.smsTemplates||[]).map((t:any)=><div className={styles.row} key={t.id}><div><strong>{t.name}</strong><div className={styles.tiny}>{t.body}</div></div><div className={styles.actions}><button className={styles.ghost} onClick={()=>setSmsTemplate({...t})}>Edit</button><button className={styles.danger} onClick={()=>run(`del-${t.id}`,'delete_sms_template',{templateId:t.id})}>Delete</button></div></div>)}</div></div>
   <div className={styles.panel}><h3>SMS Campaign</h3><p className={styles.muted}>Only contacts with SMS opt-in are eligible.</p><label className={styles.label}>Campaign name<input className={styles.input} value={smsCampaign.name||''} onChange={e=>setSmsCampaign({...smsCampaign,name:e.target.value})}/></label><label className={styles.label}>Use template<select className={styles.select} value="" onChange={e=>{const t=(data.smsTemplates||[]).find((x:any)=>x.id===e.target.value);if(t)setSmsCampaign({...smsCampaign,body:t.body})}}><option value="">Choose template…</option>{(data.smsTemplates||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={smsCampaign.body||''} onChange={e=>setSmsCampaign({...smsCampaign,body:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label className={styles.label}>Status<select className={styles.select} value={smsCampaign.filter_status||''} onChange={e=>setSmsCampaign({...smsCampaign,filter_status:e.target.value})}><option value="">All statuses</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.label}>Genre<select className={styles.select} value={smsCampaign.filter_genre||''} onChange={e=>setSmsCampaign({...smsCampaign,filter_genre:e.target.value})}><option value="">All genres</option>{GENRES.map(x=><option key={x}>{x}</option>)}</select></label></div><label className={styles.label}>Send at<input className={styles.input} type="datetime-local" value={smsCampaign.scheduled_at||''} onChange={e=>setSmsCampaign({...smsCampaign,scheduled_at:e.target.value})}/></label><button className={styles.primary} onClick={queueSmsCampaign}>Queue SMS Campaign</button></div>
   <div className={styles.panel}><div className={styles.statGrid}><div className={styles.stat}><b>{data.smsStats?.queued||0}</b><span>Queued</span></div><div className={styles.stat}><b>{data.smsStats?.sent||0}</b><span>Sent</span></div><div className={styles.stat}><b>{data.smsStats?.failed||0}</b><span>Failed</span></div></div><h3>Campaign History</h3>{(data.smsCampaigns||[]).map((c:any)=><div className={styles.row} key={c.id}><div><strong>{c.name}</strong><div className={styles.tiny}>{c.status} · {c.sent_count||0} sent · {c.failed_count||0} failed</div></div><span className={styles.tiny}>{c.scheduled_at?new Date(c.scheduled_at).toLocaleString():'—'}</span></div>)}</div>
  </div>}
  {tab==='history'&&<div className={styles.smsGrid}><div className={styles.panel} style={{gridColumn:'1 / -1'}}><h3>Workflow Enrollment History</h3>{(data.enrollments||[]).map((e:any)=><div className={styles.row} key={e.id}><div><strong>{(data.workflows||[]).find((w:any)=>w.id===e.workflow_id)?.name||'Workflow'}</strong><div className={styles.tiny}>{(data.contacts||[]).find((c:any)=>c.id===e.contact_id)?.artist_name||(data.contacts||[]).find((c:any)=>c.id===e.contact_id)?.full_name||'Contact'} · step {Number(e.current_step||0)+1}</div>{e.last_error&&<div className={styles.tiny} style={{color:'#b42318'}}>{e.last_error}</div>}</div><span className={styles.badge}>{e.status}</span></div>)}{!(data.enrollments||[]).length&&<div className={styles.empty}>No workflow enrollments yet.</div>}</div></div>}
 </section>
}

function StepEditor({step,onChange}:{step:any;onChange:(patch:any)=>void}){const c=step.step_config||{};return <><h3>{actionMeta(step.step_type)[1]}</h3><p className={styles.muted}>{actionMeta(step.step_type)[2]}</p><div className={styles.form}>{step.step_type==='send_sms'&&<label className={styles.label}>SMS message<textarea className={styles.textarea} rows={7} value={c.message||''} onChange={e=>onChange({message:e.target.value})} placeholder="Hey {{artist_name}}, your voting page is live…"/></label>}{step.step_type==='send_email'&&<><label className={styles.label}>Subject<input className={styles.input} value={c.subject||''} onChange={e=>onChange({subject:e.target.value})}/></label><label className={styles.label}>Email message<textarea className={styles.textarea} rows={7} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></label></>}{step.step_type==='wait'&&<><label className={styles.label}>Amount<input className={styles.input} type="number" min="1" value={c.amount||1} onChange={e=>onChange({amount:Number(e.target.value)})}/></label><label className={styles.label}>Unit<select className={styles.select} value={c.unit||'hours'} onChange={e=>onChange({unit:e.target.value})}><option>minutes</option><option>hours</option><option>days</option></select></label></>}{step.step_type==='add_tag'&&<label className={styles.label}>Tag<input className={styles.input} value={c.tag||''} onChange={e=>onChange({tag:e.target.value})}/></label>}{step.step_type==='update_status'&&<label className={styles.label}>New status<select className={styles.select} value={c.status||'active'} onChange={e=>onChange({status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label>}{step.step_type==='create_task'&&<><label className={styles.label}>Task title<input className={styles.input} value={c.title||''} onChange={e=>onChange({title:e.target.value})}/></label><label className={styles.label}>Notes<textarea className={styles.textarea} rows={4} value={c.notes||''} onChange={e=>onChange({notes:e.target.value})}/></label><label className={styles.label}>Due in hours<input className={styles.input} type="number" min="0" value={c.due_hours||24} onChange={e=>onChange({due_hours:Number(e.target.value)})}/></label></>}<div className={styles.tiny}>Merge fields: {'{{artist_name}}'}, {'{{first_name}}'}, {'{{genre}}'}, {'{{city}}'}</div></div></>}
