'use client';

import {useEffect,useMemo,useState} from 'react';
import styles from './AutomationBuilder.module.css';

type Item={id:string;label:string;description:string;category:string;icon:string;requires?:string};

const TRIGGERS:Item[]=[
 {id:'manual',label:'Manual Enrollment',description:'Start when you manually add a contact',category:'Contacts',icon:'⚡'},
 {id:'contact_created',label:'Contact Added',description:'New CRM contact is created',category:'Contacts',icon:'+'},
 {id:'contact_updated',label:'Contact Updated',description:'Any tracked contact field changes',category:'Contacts',icon:'↻'},
 {id:'status_changed',label:'Contact Status Changed',description:'Contact moves to a selected status',category:'Contacts',icon:'↻'},
 {id:'tag_added',label:'Tag Added',description:'A selected tag is added',category:'Contacts',icon:'#'},
 {id:'tag_removed',label:'Tag Removed',description:'A selected tag is removed',category:'Contacts',icon:'−'},
 {id:'email_opt_in_changed',label:'Email Opt-In Changed',description:'Email permission changes',category:'Contacts',icon:'✉'},
 {id:'sms_opt_in_changed',label:'SMS Opt-In Changed',description:'SMS permission changes',category:'Contacts',icon:'SMS'},
 {id:'sms_reply',label:'Customer Replied by SMS',description:'TextGrid receives a reply',category:'Messaging',icon:'SMS',requires:'textgrid'},
 {id:'email_reply',label:'Customer Replied by Email',description:'Inbound email reply is received',category:'Messaging',icon:'✉',requires:'inbound_email'},
 {id:'battle_submission_received',label:'Battle Submission Received',description:'Artist submits music to a battle',category:'Indie Cut Battles',icon:'♫'},
 {id:'battle_submission_approved',label:'Battle Submission Approved',description:'Artist is approved for a battle',category:'Indie Cut Battles',icon:'✓'},
 {id:'battle_submission_rejected',label:'Battle Submission Rejected',description:'Artist submission is rejected',category:'Indie Cut Battles',icon:'×'},
 {id:'vote_received',label:'Vote Received',description:'An artist receives a verified battle vote',category:'Indie Cut Battles',icon:'★'},
 {id:'artist_advanced',label:'Artist Advanced',description:'Artist advances to the next round',category:'Indie Cut Battles',icon:'↑'},
 {id:'battle_started',label:'Battle Started',description:'A live battle or round starts',category:'Indie Cut Battles',icon:'▶'},
 {id:'battle_ended',label:'Battle Ended',description:'A live battle or round ends',category:'Indie Cut Battles',icon:'■'},
 {id:'winner_selected',label:'Winner Selected',description:'A battle winner is finalized',category:'Indie Cut Battles',icon:'♛'},
 {id:'form_submitted',label:'Form Submitted',description:'A connected Indie Cut form is submitted',category:'Forms & Web',icon:'▤'},
 {id:'webhook_received',label:'Inbound Webhook',description:'An external system calls a workflow webhook',category:'Forms & Web',icon:'↔'},
 {id:'scheduled',label:'Scheduled',description:'Run on a date/time or recurring schedule',category:'Logic & Time',icon:'◷'},
 {id:'payment_received',label:'Payment Received',description:'A connected payment succeeds',category:'Payments',icon:'$ ',requires:'payments'},
 {id:'payment_failed',label:'Payment Failed',description:'A connected payment fails',category:'Payments',icon:'$',requires:'payments'},
 {id:'refund_issued',label:'Refund Issued',description:'A connected payment is refunded',category:'Payments',icon:'$',requires:'payments'},
 {id:'appointment_created',label:'Appointment Created',description:'A connected calendar appointment is booked',category:'Appointments',icon:'◫',requires:'calendar'},
 {id:'appointment_changed',label:'Appointment Changed',description:'Appointment is rescheduled or canceled',category:'Appointments',icon:'◫',requires:'calendar'},
 {id:'meta_lead',label:'Facebook / Instagram Lead',description:'Meta sends a lead to Indie Cut',category:'Social',icon:'f',requires:'meta'},
 {id:'tiktok_lead',label:'TikTok Lead',description:'TikTok sends a lead to Indie Cut',category:'Social',icon:'♪',requires:'tiktok'},
 {id:'social_message',label:'Social Message Received',description:'A connected social account receives a message',category:'Social',icon:'@',requires:'social_messaging'}
];

const ACTIONS:Item[]=[
 {id:'send_sms',label:'Send SMS',description:'Send a TextGrid SMS',category:'Messaging',icon:'SMS',requires:'textgrid'},
 {id:'send_email',label:'Send Email',description:'Send through Resend',category:'Messaging',icon:'✉',requires:'email'},
 {id:'internal_email',label:'Internal Notification',description:'Email an internal team member',category:'Messaging',icon:'! ',requires:'email'},
 {id:'if_else',label:'If / Else',description:'Split into YES and NO paths',category:'Logic',icon:'◇'},
 {id:'wait',label:'Wait',description:'Pause for minutes, hours or days',category:'Logic',icon:'◷'},
 {id:'wait_until',label:'Wait Until',description:'Pause until a specific date and time',category:'Logic',icon:'◷'},
 {id:'stop_workflow',label:'Stop Workflow',description:'End this enrollment immediately',category:'Logic',icon:'■'},
 {id:'enroll_workflow',label:'Add to Workflow',description:'Enroll contact in another workflow',category:'Logic',icon:'+'},
 {id:'remove_from_workflow',label:'Remove from Workflow',description:'Stop an enrollment in another workflow',category:'Logic',icon:'−'},
 {id:'add_tag',label:'Add Tag',description:'Add a CRM tag',category:'CRM',icon:'#'},
 {id:'remove_tag',label:'Remove Tag',description:'Remove a CRM tag',category:'CRM',icon:'−'},
 {id:'update_status',label:'Update Status',description:'Change CRM status',category:'CRM',icon:'↻'},
 {id:'update_contact',label:'Update Contact Field',description:'Update name, genre, city, source, email or phone',category:'CRM',icon:'✎'},
 {id:'add_note',label:'Add Note',description:'Append a note to the CRM contact',category:'CRM',icon:'▤'},
 {id:'create_task',label:'Create Task',description:'Create a follow-up task',category:'CRM',icon:'✓'},
 {id:'outbound_webhook',label:'Webhook',description:'POST contact/workflow data to another system',category:'Integrations',icon:'↗'},
 {id:'ai_generate',label:'AI Generate Text',description:'Generate workflow text with AI',category:'AI',icon:'AI',requires:'openai'},
 {id:'ai_summarize',label:'AI Summarize',description:'Summarize contact or workflow context',category:'AI',icon:'AI',requires:'openai'},
 {id:'ai_detect_intent',label:'AI Detect Intent',description:'Classify a reply or contact intent',category:'AI',icon:'AI',requires:'openai'},
 {id:'ai_extract',label:'AI Extract Data',description:'Extract structured information from text',category:'AI',icon:'AI',requires:'openai'},
 {id:'ai_translate',label:'AI Translate',description:'Translate workflow text',category:'AI',icon:'AI',requires:'openai'},
 {id:'create_payment_link',label:'Create Payment Link',description:'Create a payment request',category:'Payments',icon:'$',requires:'payments'},
 {id:'refund_payment',label:'Refund Payment',description:'Refund a connected payment',category:'Payments',icon:'$',requires:'payments'},
 {id:'create_appointment',label:'Create Appointment',description:'Book a connected calendar',category:'Appointments',icon:'◫',requires:'calendar'},
 {id:'update_appointment',label:'Update Appointment',description:'Reschedule or cancel an appointment',category:'Appointments',icon:'◫',requires:'calendar'},
 {id:'meta_audience',label:'Meta Audience Action',description:'Add/remove a contact from a connected Meta audience',category:'Advertising',icon:'f',requires:'meta_ads'},
 {id:'tiktok_audience',label:'TikTok Audience Action',description:'Add/remove a contact from a connected TikTok audience',category:'Advertising',icon:'♪',requires:'tiktok_ads'},
 {id:'send_social_message',label:'Send Social Message',description:'Send through a connected social inbox',category:'Social',icon:'@',requires:'social_messaging'},
 {id:'create_opportunity',label:'Create Opportunity',description:'Create a sales/opportunity record',category:'Opportunities',icon:'◆',requires:'opportunities'},
 {id:'move_opportunity',label:'Move Opportunity',description:'Move an opportunity stage',category:'Opportunities',icon:'→',requires:'opportunities'},
 {id:'send_contract',label:'Send Document / Contract',description:'Send a connected document for signature',category:'Documents',icon:'▣',requires:'documents'},
 {id:'voicemail_drop',label:'Voicemail Drop',description:'Send through a connected voice provider',category:'Calls',icon:'☎',requires:'voice'}
];

const CORE_ACTIONS=new Set(['send_sms','send_email','internal_email','if_else','wait','wait_until','stop_workflow','enroll_workflow','remove_from_workflow','add_tag','remove_tag','update_status','update_contact','add_note','create_task','outbound_webhook','ai_generate','ai_summarize','ai_detect_intent','ai_extract','ai_translate']);
const STATUSES=['lead','pending','approved','active','rejected','inactive'];
const GENRES=['Hip-Hop','R&B','Gospel','Southern Soul','Pop','Rock','Country','Afrobeats','Reggae / Dancehall','Latin','Electronic / Dance','Jazz','Soul','Alternative','Blues','Folk'];
const CONTACT_FIELDS=[['artist_name','Artist name'],['full_name','Full name'],['email','Email'],['phone','Phone'],['genre','Genre'],['city','City / State'],['source','Source'],['notes','Notes']];
const COND_FIELDS=[['status','Status'],['genre','Genre'],['tag','Tag'],['city','City / State'],['source','Source'],['email_opt_in','Email opt-in'],['sms_opt_in','SMS opt-in'],['email','Email'],['phone','Phone']];
const OPS=[['equals','Equals'],['not_equals','Does not equal'],['contains','Contains'],['not_contains','Does not contain'],['exists','Exists'],['not_exists','Does not exist']];
const emptyWorkflow={name:'Untitled Workflow',description:'',trigger_type:'manual',trigger_config:{},status:'draft'};

async function api(action:string,extra:any={}){const r=await fetch('/api/admin/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Automation request failed');return j}
function meta(list:Item[],id:string){return list.find(x=>x.id===id)}
function same(a:any,b:any){return String(a??'').trim().toLowerCase()===String(b??'').trim().toLowerCase()}
function available(item:Item,integrations:any){return !item.requires||Boolean(integrations?.[item.requires])}
function defaultConfig(type:string){
 if(type==='send_sms')return{message:''};if(type==='send_email')return{subject:'',message:''};if(type==='internal_email')return{to:'',subject:'Indie Cut workflow notification',message:''};
 if(type==='if_else')return{field:'status',operator:'equals',value:'approved',yes_steps:[],no_steps:[]};if(type==='wait')return{amount:1,unit:'hours'};if(type==='wait_until')return{datetime:''};
 if(type==='add_tag'||type==='remove_tag')return{tag:''};if(type==='update_status')return{status:'active'};if(type==='update_contact')return{field:'genre',value:''};if(type==='add_note')return{note:''};
 if(type==='create_task')return{title:'Follow up with {{artist_name}}',notes:'',priority:'normal',due_hours:24};if(type==='outbound_webhook')return{url:'',method:'POST',secret:'',body_template:''};
 if(type==='enroll_workflow'||type==='remove_from_workflow')return{workflow_id:''};if(type.startsWith('ai_'))return{input:'{{notes}}',instruction:'',save_to:'notes',language:'Spanish'};return{};
}
function summary(step:any){const c=step.step_config||{};switch(step.step_type){case'send_sms':return c.message||'Compose SMS';case'send_email':return c.subject||'Compose email';case'internal_email':return c.to||'Choose recipient';case'if_else':return `If ${c.field||'status'} ${c.operator||'equals'} ${c.value??''}`;case'wait':return `${c.amount||1} ${c.unit||'hours'}`;case'wait_until':return c.datetime||'Choose date/time';case'add_tag':return `Add ${c.tag||'tag'}`;case'remove_tag':return `Remove ${c.tag||'tag'}`;case'update_status':return `Status → ${c.status||'active'}`;case'update_contact':return `${c.field||'field'} → ${c.value||'value'}`;case'add_note':return c.note||'Add CRM note';case'create_task':return c.title||'Create task';case'outbound_webhook':return c.url||'Configure webhook';case'stop_workflow':return'End enrollment';case'enroll_workflow':return'Add to another workflow';case'remove_from_workflow':return'Remove from another workflow';default:return meta(ACTIONS,step.step_type)?.description||step.step_type}}

export default function AutomationBuilderV2(){
 const[data,setData]=useState<any>({workflows:[],steps:[],contacts:[],enrollments:[],smsTemplates:[],smsCampaigns:[],smsStats:{},integrations:{}});const[tags,setTags]=useState<any[]>([]);const[tab,setTab]=useState<'builder'|'tags'|'sms'|'history'|'library'>('builder');
 const[workflow,setWorkflow]=useState<any>({...emptyWorkflow});const[steps,setSteps]=useState<any[]>([]);const[selected,setSelected]=useState<number|null>(null);const[insertAt,setInsertAt]=useState(0);const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[newTag,setNewTag]=useState('');const[historyWorkflow,setHistoryWorkflow]=useState('');
 const[directSms,setDirectSms]=useState({contactId:'',message:''});const[smsTemplate,setSmsTemplate]=useState({name:'',body:'',active:true} as any);const[smsCampaign,setSmsCampaign]=useState({name:'',body:'',filter_status:'',filter_genre:'',scheduled_at:''} as any);const[enrollContact,setEnrollContact]=useState('');
 async function load(){try{const[r,t]=await Promise.all([fetch('/api/admin/automation',{cache:'no-store'}),fetch('/api/admin/tags',{cache:'no-store'})]);const j=await r.json(),tj=await t.json();if(!r.ok)throw new Error(j.error||'Unable to load workflows');setData(j);setTags(tj.tags||[]);if(!workflow.id&&j.workflows?.length)open(j.workflows[0],j)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 function open(w:any,source=data){const list=(source.steps||[]).filter((x:any)=>x.workflow_id===w.id).sort((a:any,b:any)=>a.step_order-b.step_order).map((x:any)=>({step_type:x.step_type,step_config:x.step_config||{}}));setWorkflow({...w,trigger_config:w.trigger_config||{}});setSteps(list);setSelected(null);setInsertAt(list.length)}
 function add(type:string){const item=meta(ACTIONS,type);if(!item||!CORE_ACTIONS.has(type)||!available(item,data.integrations)){setMsg(`${item?.label||type} requires a connected Indie Cut module before it can run.`);return}const i=Math.max(0,Math.min(insertAt,steps.length));const n={step_type:type,step_config:defaultConfig(type)};setSteps(v=>{const c=[...v];c.splice(i,0,n);return c});setSelected(i);setInsertAt(i+1)}
 function patch(i:number,p:any){setSteps(v=>v.map((s,n)=>n===i?{...s,step_config:{...(s.step_config||{}),...p}}:s))}
 async function run(key:string,action:string,extra:any={}){setBusy(key);setMsg('');try{const j=await api(action,extra);setData(j);return j}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 async function save(){const j=await run('save','save_workflow',{workflow,steps});if(j){const w=(j.workflows||[]).find((x:any)=>x.name===workflow.name)||j.workflows?.[0];if(w)open(w,j);setMsg('Workflow saved.')}}
 async function publish(){if(!workflow.id){setMsg('Save this workflow first.');return}const j=await run('publish','publish_workflow',{workflowId:workflow.id,publish:workflow.status!=='published'});if(j){const w=(j.workflows||[]).find((x:any)=>x.id===workflow.id);if(w)open(w,j)}}
 const published=workflow.status==='published',current=selected===null||selected<0?null:steps[selected];const categories=(items:Item[])=>Array.from(new Set(items.map(x=>x.category)));
 const history=useMemo(()=>historyWorkflow?(data.enrollments||[]).filter((e:any)=>e.workflow_id===historyWorkflow):(data.enrollments||[]),[data.enrollments,historyWorkflow]);
 const cBy=(id:string)=>(data.contacts||[]).find((x:any)=>x.id===id),wBy=(id:string)=>(data.workflows||[]).find((x:any)=>x.id===id);
 return <section className={styles.shell}>
  <div className={styles.topbar}><div className={styles.topTitle}><h2>Indie Cut Workflows</h2><span className={`${styles.badge} ${!data.integrations?.textgrid?styles.badgeOff:''}`}>{data.integrations?.textgrid?'TEXTGRID CONNECTED':'TEXTGRID NOT CONNECTED'}</span></div><div className={styles.tabs} style={{flexWrap:'wrap'}}>{[['builder','Builder'],['library','Trigger + Action Library'],['tags',`Tags (${tags.length})`],['sms','SMS'],['history',`Enrollment History (${(data.enrollments||[]).length})`]].map(([id,label])=><button key={id} className={`${styles.tab} ${tab===id?styles.tabActive:''}`} onClick={()=>setTab(id as any)}>{label}</button>)}</div></div>
  {msg&&<div className={styles.message}>{msg}</div>}
  {tab==='builder'&&<div className={styles.workspace}>
   <aside className={styles.left}><div className={styles.leftHead}><strong>WORKFLOWS</strong><button className={styles.newButton} onClick={()=>{setWorkflow({...emptyWorkflow});setSteps([]);setSelected(null)}}>＋ New</button></div><div className={styles.workflowList}>{(data.workflows||[]).map((w:any)=><button key={w.id} className={`${styles.workflowItem} ${workflow.id===w.id?styles.workflowActive:''}`} onClick={()=>open(w)}><span className={styles.workflowName}>{w.name}</span><span className={styles.workflowMeta}><span>{meta(TRIGGERS,w.trigger_type)?.label||w.trigger_type}</span><span>{w.status}</span></span></button>)}</div></aside>
   <main className={styles.canvasWrap}><div className={styles.canvasHead}><div><input className={styles.nameInput} value={workflow.name||''} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/><div className={styles.tiny}>{published?'PUBLISHED — LIVE AUTOMATION':'DRAFT — NOT RUNNING'}</div></div><div className={styles.actions}><button className={styles.ghost} onClick={save}>{busy==='save'?'Saving…':'Save'}</button><button className={styles.primary} onClick={publish}>{published?'Unpublish':'Publish'}</button></div></div><div className={styles.flow}>
    <div className={`${styles.node} ${styles.nodeTrigger}`} onClick={()=>setSelected(-1)}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={`${styles.icon} ${styles.triggerIcon}`}>⚡</span><div><div className={styles.nodeTitle}>Trigger</div><div className={styles.nodeSub}>{meta(TRIGGERS,workflow.trigger_type)?.label||workflow.trigger_type}</div></div></div></div><div className={styles.nodeBody}>Starts this workflow when the selected event happens.</div></div>
    {steps.map((s:any,i:number)=>{const m=meta(ACTIONS,s.step_type);return <div key={i} style={{width:'100%',display:'flex',flexDirection:'column',alignItems:'center'}}><div className={styles.connector}/><button className={styles.plus} onClick={()=>{setInsertAt(i);setSelected(null)}}>+</button><div className={styles.connector}/><div className={`${styles.node} ${styles.nodeAction}`} onClick={()=>{setSelected(i);setInsertAt(i+1)}}><div className={styles.nodeHead}><div className={styles.nodeType}><span className={styles.icon}>{m?.icon||'•'}</span><div><div className={styles.nodeTitle}>{m?.label||s.step_type}</div><div className={styles.nodeSub}>{summary(s)}</div></div></div><div className={styles.stepTools}><button onClick={e=>{e.stopPropagation();setSteps(v=>v.filter((_:any,n:number)=>n!==i));setSelected(null)}}>×</button></div></div>{s.step_type==='if_else'&&<div className={styles.nodeBody}>YES: {(s.step_config?.yes_steps||[]).length} actions · NO: {(s.step_config?.no_steps||[]).length} actions</div>}</div></div>})}
    <div className={styles.connector}/><button className={styles.plus} onClick={()=>{setInsertAt(steps.length);setSelected(null)}}>+</button><div className={styles.connector}/><div className={styles.tiny}>END</div>
   </div></main>
   <aside className={styles.right}>{selected===-1?<TriggerEditor workflow={workflow} setWorkflow={setWorkflow} tags={tags} integrations={data.integrations}/>:current?<StepEditor step={current} tags={tags} workflows={data.workflows||[]} integrations={data.integrations} onChange={(p:any)=>patch(selected!,p)}/>:<ActionPicker actions={ACTIONS} integrations={data.integrations} add={add} categories={categories(ACTIONS)} workflows={data.workflows||[]} enrollContact={enrollContact} setEnrollContact={setEnrollContact} data={data} workflow={workflow} onEnroll={async()=>{if(workflow.id&&enrollContact){await run('enroll','enroll_contact',{workflowId:workflow.id,contactId:enrollContact});setEnrollContact('')}}}/>}</aside>
  </div>}
  {tab==='library'&&<Library triggers={TRIGGERS} actions={ACTIONS} integrations={data.integrations}/>} 
  {tab==='tags'&&<div className={styles.smsGrid}><div className={styles.panel} style={{gridColumn:'1 / -1'}}><h3>CRM Tags</h3><p className={styles.muted}>Create tags once, then use them in triggers, conditions and actions.</p><div style={{display:'flex',gap:8,maxWidth:620}}><input className={styles.input} value={newTag} onChange={e=>setNewTag(e.target.value)} placeholder="e.g. live-battles, finalist, VIP"/><button className={styles.primary} onClick={async()=>{if(!newTag.trim())return;const r=await fetch('/api/admin/tags',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create_tag',name:newTag.trim()})});const j=await r.json();if(r.ok){setTags(j.tags||[]);setNewTag('')}}}>Create Tag</button></div>{tags.map((t:any)=><div className={styles.row} key={t.id}><strong>{t.name}</strong><button className={styles.danger} onClick={async()=>{const r=await fetch('/api/admin/tags',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete_tag',id:t.id})});const j=await r.json();if(r.ok)setTags(j.tags||[])}}>Delete</button></div>)}</div></div>}
  {tab==='sms'&&<div className={styles.smsGrid}><div className={styles.panel}><h3>Direct Text Message</h3><label className={styles.label}>Contact<select className={styles.select} value={directSms.contactId} onChange={e=>setDirectSms({...directSms,contactId:e.target.value})}><option value="">Choose contact…</option>{(data.contacts||[]).filter((c:any)=>c.sms_opt_in&&c.phone).map((c:any)=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.phone}</option>)}</select></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={directSms.message} onChange={e=>setDirectSms({...directSms,message:e.target.value})}/></label><button className={styles.primary} onClick={async()=>{if(directSms.contactId&&directSms.message.trim()){await run('direct','send_sms',{contactId:directSms.contactId,message:directSms.message});setDirectSms({contactId:'',message:''})}}}>Send Text</button></div><div className={styles.panel}><h3>SMS Templates</h3><label className={styles.label}>Name<input className={styles.input} value={smsTemplate.name||''} onChange={e=>setSmsTemplate({...smsTemplate,name:e.target.value})}/></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={smsTemplate.body||''} onChange={e=>setSmsTemplate({...smsTemplate,body:e.target.value})}/></label><button className={styles.primary} onClick={async()=>{await run('template','save_sms_template',{template:smsTemplate});setSmsTemplate({name:'',body:'',active:true})}}>Save Template</button></div><div className={styles.panel}><h3>SMS Campaign</h3><label className={styles.label}>Campaign name<input className={styles.input} value={smsCampaign.name||''} onChange={e=>setSmsCampaign({...smsCampaign,name:e.target.value})}/></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={smsCampaign.body||''} onChange={e=>setSmsCampaign({...smsCampaign,body:e.target.value})}/></label><button className={styles.primary} onClick={async()=>{await run('campaign','queue_sms_campaign',{campaign:smsCampaign});setSmsCampaign({name:'',body:'',filter_status:'',filter_genre:'',scheduled_at:''})}}>Queue Campaign</button></div><div className={styles.panel}><div className={styles.statGrid}><div className={styles.stat}><b>{data.smsStats?.queued||0}</b><span>Queued</span></div><div className={styles.stat}><b>{data.smsStats?.sent||0}</b><span>Sent</span></div><div className={styles.stat}><b>{data.smsStats?.failed||0}</b><span>Failed</span></div></div></div></div>}
  {tab==='history'&&<div className={styles.smsGrid}><div className={styles.panel} style={{gridColumn:'1 / -1'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'end',flexWrap:'wrap'}}><div><h3>Workflow Enrollment History</h3><p className={styles.muted}>See who enrolled, why, progress and errors.</p></div><label className={styles.label}>Workflow<select className={styles.select} value={historyWorkflow} onChange={e=>setHistoryWorkflow(e.target.value)}><option value="">All workflows</option>{(data.workflows||[]).map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div>{history.map((e:any)=>{const c=cBy(e.contact_id),w=wBy(e.workflow_id);return <div className={styles.row} key={e.id}><div><strong>{c?.artist_name||c?.full_name||c?.email||'Unknown contact'}</strong><div className={styles.tiny}>{w?.name||'Workflow'} · {e.context?.trigger_type||w?.trigger_type||'manual'} · step {e.current_step||0}</div>{e.last_error&&<div className={styles.tiny} style={{color:'#b42318'}}>Error: {e.last_error}</div>}</div><span className={styles.badge}>{e.status}</span></div>})}</div></div>}
 </section>
}

function TriggerEditor({workflow,setWorkflow,tags,integrations}:{workflow:any;setWorkflow:(x:any)=>void;tags:any[];integrations:any}){const cats=Array.from(new Set(TRIGGERS.map(x=>x.category)));return <><h3>Workflow Trigger</h3><p className={styles.muted}>Choose what starts this automation.</p><label className={styles.label}>Trigger<select className={styles.select} value={workflow.trigger_type||'manual'} onChange={e=>{const item=meta(TRIGGERS,e.target.value)!;if(!available(item,integrations)){alert(`${item.label} requires ${item.requires}.`);return}setWorkflow({...workflow,trigger_type:e.target.value,trigger_config:{}})}}>{cats.map(cat=><optgroup key={cat} label={cat}>{TRIGGERS.filter(x=>x.category===cat).map(x=><option key={x.id} value={x.id} disabled={!available(x,integrations)}>{x.label}{x.requires&&!available(x,integrations)?' — connect first':''}</option>)}</optgroup>)}</select></label>{workflow.trigger_type==='status_changed'&&<label className={styles.label}>New status<select className={styles.select} value={workflow.trigger_config?.status||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,status:e.target.value}})}><option value="">Any status</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label>}{['tag_added','tag_removed'].includes(workflow.trigger_type)&&<label className={styles.label}>Tag<select className={styles.select} value={workflow.trigger_config?.tag||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,tag:e.target.value}})}><option value="">Any tag</option>{tags.map((t:any)=><option key={t.id} value={t.name}>{t.name}</option>)}</select></label>}{workflow.trigger_type==='sms_reply'&&<label className={styles.label}>Optional keyword<input className={styles.input} value={workflow.trigger_config?.keyword||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,keyword:e.target.value}})} /></label>}{workflow.trigger_type==='scheduled'&&<><label className={styles.label}>Schedule<select className={styles.select} value={workflow.trigger_config?.recurrence||'daily'} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,recurrence:e.target.value}})}><option value="once">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className={styles.label}>Run at<input type="datetime-local" className={styles.input} value={workflow.trigger_config?.run_at||''} onChange={e=>setWorkflow({...workflow,trigger_config:{...workflow.trigger_config,run_at:e.target.value}})}/></label></>}{workflow.trigger_type==='webhook_received'&&<div className={styles.message} style={{margin:0}}>Save the workflow first. The webhook endpoint will be /api/workflows/webhook/{workflow.id||'WORKFLOW_ID'}.</div>}</>}

function ActionPicker({actions,integrations,add,categories,workflow,enrollContact,setEnrollContact,data,onEnroll}:{actions:Item[];integrations:any;add:(x:string)=>void;categories:string[];workflow:any;enrollContact:string;setEnrollContact:(x:string)=>void;data:any;onEnroll:()=>void}){return <><h3>Add an Action</h3><p className={styles.muted}>Connected actions run now. HighLevel-style actions that depend on a module stay visible but disabled until that integration exists.</p>{categories.map(cat=><div key={cat}><div className={styles.sectionTitle}>{cat}</div><div className={styles.library}>{actions.filter(a=>a.category===cat).map(a=>{const ready=CORE_ACTIONS.has(a.id)&&available(a,integrations);return <button className={styles.libraryButton} key={a.id} disabled={!ready} style={{opacity:ready?1:.48,cursor:ready?'pointer':'not-allowed'}} onClick={()=>ready&&add(a.id)}><span className={styles.icon}>{a.icon}</span><span>{a.label}<div className={styles.tiny}>{a.description}{!ready?` · ${a.requires?`Requires ${a.requires}`:'Module not built yet'}`:''}</div></span></button>})}</div></div>)}{workflow.id&&<><div className={styles.sectionTitle}>TEST / MANUAL ENROLL</div><label className={styles.label}>Contact<select className={styles.select} value={enrollContact} onChange={e=>setEnrollContact(e.target.value)}><option value="">Choose contact…</option>{(data.contacts||[]).map((c:any)=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.email||c.phone}</option>)}</select></label><button className={styles.primary} onClick={onEnroll} disabled={!enrollContact}>Enroll Contact</button></>}</>}

function StepEditor({step,tags,workflows,integrations,onChange,nested=false}:{step:any;tags:any[];workflows:any[];integrations:any;onChange:(x:any)=>void;nested?:boolean}){const c=step.step_config||{};const item=meta(ACTIONS,step.step_type);return <>{!nested&&<><h3>{item?.label||step.step_type}</h3><p className={styles.muted}>{item?.description}</p></>}<div className={styles.form}>
 {step.step_type==='send_sms'&&<label className={styles.label}>SMS message<textarea className={styles.textarea} rows={6} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></label>}
 {step.step_type==='send_email'&&<><label className={styles.label}>Subject<input className={styles.input} value={c.subject||''} onChange={e=>onChange({subject:e.target.value})}/></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={6} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></label></>}
 {step.step_type==='internal_email'&&<><label className={styles.label}>Send to<input className={styles.input} value={c.to||''} onChange={e=>onChange({to:e.target.value})} placeholder="team@indiecut.info"/></label><label className={styles.label}>Subject<input className={styles.input} value={c.subject||''} onChange={e=>onChange({subject:e.target.value})}/></label><label className={styles.label}>Message<textarea className={styles.textarea} rows={5} value={c.message||''} onChange={e=>onChange({message:e.target.value})}/></label></>}
 {step.step_type==='wait'&&<><label className={styles.label}>Amount<input className={styles.input} type="number" min="1" value={c.amount||1} onChange={e=>onChange({amount:Number(e.target.value)})}/></label><label className={styles.label}>Unit<select className={styles.select} value={c.unit||'hours'} onChange={e=>onChange({unit:e.target.value})}><option>minutes</option><option>hours</option><option>days</option></select></label></>}
 {step.step_type==='wait_until'&&<label className={styles.label}>Resume at<input className={styles.input} type="datetime-local" value={c.datetime||''} onChange={e=>onChange({datetime:e.target.value})}/></label>}
 {['add_tag','remove_tag'].includes(step.step_type)&&<label className={styles.label}>Tag<select className={styles.select} value={c.tag||''} onChange={e=>onChange({tag:e.target.value})}><option value="">Choose tag…</option>{tags.map((t:any)=><option key={t.id} value={t.name}>{t.name}</option>)}</select></label>}
 {step.step_type==='update_status'&&<label className={styles.label}>New status<select className={styles.select} value={c.status||'active'} onChange={e=>onChange({status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label>}
 {step.step_type==='update_contact'&&<><label className={styles.label}>Field<select className={styles.select} value={c.field||'genre'} onChange={e=>onChange({field:e.target.value})}>{CONTACT_FIELDS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className={styles.label}>Value<input className={styles.input} value={c.value||''} onChange={e=>onChange({value:e.target.value})}/></label></>}
 {step.step_type==='add_note'&&<label className={styles.label}>Note<textarea className={styles.textarea} rows={5} value={c.note||''} onChange={e=>onChange({note:e.target.value})}/></label>}
 {step.step_type==='create_task'&&<><label className={styles.label}>Task title<input className={styles.input} value={c.title||''} onChange={e=>onChange({title:e.target.value})}/></label><label className={styles.label}>Notes<textarea className={styles.textarea} rows={4} value={c.notes||''} onChange={e=>onChange({notes:e.target.value})}/></label><label className={styles.label}>Due in hours<input className={styles.input} type="number" value={c.due_hours||24} onChange={e=>onChange({due_hours:Number(e.target.value)})}/></label></>}
 {['enroll_workflow','remove_from_workflow'].includes(step.step_type)&&<label className={styles.label}>Workflow<select className={styles.select} value={c.workflow_id||''} onChange={e=>onChange({workflow_id:e.target.value})}><option value="">Choose workflow…</option>{workflows.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>}
 {step.step_type==='outbound_webhook'&&<><label className={styles.label}>URL<input className={styles.input} value={c.url||''} onChange={e=>onChange({url:e.target.value})} placeholder="https://..."/></label><label className={styles.label}>Method<select className={styles.select} value={c.method||'POST'} onChange={e=>onChange({method:e.target.value})}><option>POST</option><option>PUT</option><option>PATCH</option></select></label><label className={styles.label}>Optional secret header<input className={styles.input} value={c.secret||''} onChange={e=>onChange({secret:e.target.value})}/></label><label className={styles.label}>Optional body template<textarea className={styles.textarea} rows={5} value={c.body_template||''} onChange={e=>onChange({body_template:e.target.value})} placeholder={'{"artist":"{{artist_name}}"}'}/></label></>}
 {step.step_type.startsWith('ai_')&&<><label className={styles.label}>Input<textarea className={styles.textarea} rows={5} value={c.input||''} onChange={e=>onChange({input:e.target.value})}/></label><label className={styles.label}>Instruction<textarea className={styles.textarea} rows={4} value={c.instruction||''} onChange={e=>onChange({instruction:e.target.value})}/></label>{step.step_type==='ai_translate'&&<label className={styles.label}>Language<input className={styles.input} value={c.language||'Spanish'} onChange={e=>onChange({language:e.target.value})}/></label>}<label className={styles.label}>Save result to<select className={styles.select} value={c.save_to||'notes'} onChange={e=>onChange({save_to:e.target.value})}><option value="notes">CRM Notes</option><option value="source">Source</option><option value="status">Status</option></select></label></>}
 {step.step_type==='if_else'&&<IfElseEditor c={c} tags={tags} workflows={workflows} integrations={integrations} onChange={onChange}/>} 
 {!['if_else','stop_workflow'].includes(step.step_type)&&<div className={styles.tiny}>Merge fields: {'{{artist_name}}'}, {'{{first_name}}'}, {'{{genre}}'}, {'{{city}}'}, {'{{email}}'}, {'{{phone}}'}, {'{{notes}}'}</div>}
 </div></>}

function IfElseEditor({c,tags,workflows,integrations,onChange}:{c:any;tags:any[];workflows:any[];integrations:any;onChange:(x:any)=>void}){const op=c.operator||'equals',field=c.field||'status';const branchTypes=['send_sms','send_email','add_tag','remove_tag','update_status','update_contact','add_note','create_task','outbound_webhook'];const editor=(key:'yes_steps'|'no_steps',label:string)=>{const list=Array.isArray(c[key])?c[key]:[];return <div style={{border:'1px solid #e4e7ec',borderRadius:9,padding:10,marginTop:10}}><strong>{label}</strong>{list.map((s:any,i:number)=><div key={i} style={{borderTop:'1px solid #eef0f3',paddingTop:10,marginTop:10}}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{fontSize:12}}>{meta(ACTIONS,s.step_type)?.label}</b><button className={styles.danger} onClick={()=>onChange({[key]:list.filter((_:any,n:number)=>n!==i)})}>Remove</button></div><StepEditor nested step={s} tags={tags} workflows={workflows} integrations={integrations} onChange={(p:any)=>onChange({[key]:list.map((x:any,n:number)=>n===i?{...x,step_config:{...(x.step_config||{}),...p}}:x)})}/></div>)}<select className={styles.select} style={{marginTop:10}} value="" onChange={e=>{if(!e.target.value)return;onChange({[key]:[...list,{step_type:e.target.value,step_config:defaultConfig(e.target.value)}]})}}><option value="">＋ Add action to {label}</option>{branchTypes.map(id=><option key={id} value={id}>{meta(ACTIONS,id)?.label}</option>)}</select></div>};return <><label className={styles.label}>Field<select className={styles.select} value={field} onChange={e=>onChange({field:e.target.value,value:''})}>{COND_FIELDS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className={styles.label}>Condition<select className={styles.select} value={op} onChange={e=>onChange({operator:e.target.value})}>{OPS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>{!['exists','not_exists'].includes(op)&&<label className={styles.label}>Value{field==='tag'?<select className={styles.select} value={c.value||''} onChange={e=>onChange({value:e.target.value})}><option value="">Choose tag…</option>{tags.map((t:any)=><option key={t.id} value={t.name}>{t.name}</option>)}</select>:field==='status'?<select className={styles.select} value={c.value||''} onChange={e=>onChange({value:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select>:<input className={styles.input} value={c.value??''} onChange={e=>onChange({value:e.target.value})}/>}</label>}{editor('yes_steps','YES — condition matches')}{editor('no_steps','NO — condition does not match')}</>}

function Library({triggers,actions,integrations}:{triggers:Item[];actions:Item[];integrations:any}){const group=(title:string,items:Item[])=><div className={styles.panel}><h3>{title}</h3>{Array.from(new Set(items.map(i=>i.category))).map(cat=><div key={cat}><div className={styles.sectionTitle}>{cat}</div>{items.filter(i=>i.category===cat).map(i=>{const ready=available(i,integrations)&&(title==='Triggers'||CORE_ACTIONS.has(i.id));return <div className={styles.integrationCard} key={i.id}><span className={ready?styles.dotOn:styles.dotOff}/><div><strong>{i.label}</strong><div className={styles.muted}>{i.description}</div><div className={styles.tiny}>{ready?'AVAILABLE NOW':i.requires?`REQUIRES ${i.requires.toUpperCase()}`:'VISIBLE NOW · MODULE CONNECTION NEEDED'}</div></div></div>})}</div>)}</div>;return <div className={styles.smsGrid}>{group('Triggers',triggers)}{group('Actions',actions)}</div>}
