'use client';

import {useEffect,useMemo,useState} from 'react';

type Contest=any;
const GENRES=['Hip-Hop','R&B','Gospel','Southern Soul','Pop','Rock','Country','Afrobeats','Reggae / Dancehall','Latin','Electronic / Dance','Jazz','Soul','Alternative','Blues','Folk'] as const;
const emptyContest={title:'',genre:'',description:'',qualifying_starts_at:'',qualifying_ends_at:'',live_starts_at:'',vote_window_seconds:30};
const emptyEntry={artist_name:'',genre:'',city:'',bio:'',image_url:'',track_title:'',track_url:'',track_cover_url:''};

async function request(action:string,extra:any={}){
 const r=await fetch('/api/admin/battles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})});
 const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Battle update failed');return j;
}
function localDate(v?:string|null){if(!v)return'';const d=new Date(v);const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function iso(v:string){return v?new Date(v).toISOString():null}
async function upload(file?:File){if(!file)return'';const form=new FormData();form.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:form});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Upload failed');return String(j.publicUrl||'')}

export default function BattleManager(){
 const [contests,setContests]=useState<Contest[]>([]);const [form,setForm]=useState<any>({...emptyContest});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function load(){try{const r=await fetch('/api/admin/battles',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load battles');setContests(j.contests||[])}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 async function create(){setBusy(true);setMessage('');try{const j=await request('create_contest',{payload:{...form,qualifying_starts_at:iso(form.qualifying_starts_at),qualifying_ends_at:iso(form.qualifying_ends_at),live_starts_at:iso(form.live_starts_at)}});setContests(j.contests||[]);setForm({...emptyContest});setMessage(`${form.genre} battle created. Only ${form.genre} artists can enter this competition.`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="ic-module-panel"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>Indie Cut Live Battles</h2><p style={{margin:0,maxWidth:760}}>Run fan qualifying, artist profile voting, the three-person DJ battle stage, timed round voting, sponsor breaks, bracket updates and final winner tally from one control room. Each competition is locked to one music genre.</p></div><a href="/battles" target="_blank" style={{fontWeight:900}}>VIEW LIVE BATTLES ↗</a></div>
 <div style={{marginTop:24,padding:20,border:'1px solid #ddd',background:'#fafafa'}}><h3 style={{marginTop:0}}>Create a competition</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}><label>Battle title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Indie Cut R&B Battle #1"/></label><label>Competition genre<select value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}><option value="">Choose genre…</option>{GENRES.map(g=><option key={g} value={g}>{g}</option>)}</select></label><label>Qualifying starts<input type="datetime-local" value={form.qualifying_starts_at} onChange={e=>setForm({...form,qualifying_starts_at:e.target.value})}/></label><label>Qualifying ends<input type="datetime-local" value={form.qualifying_ends_at} onChange={e=>setForm({...form,qualifying_ends_at:e.target.value})}/></label><label>Live battle starts<input type="datetime-local" value={form.live_starts_at} onChange={e=>setForm({...form,live_starts_at:e.target.value})}/></label><label>Live vote window (seconds)<input type="number" min="10" max="300" value={form.vote_window_seconds} onChange={e=>setForm({...form,vote_window_seconds:Number(e.target.value)||30})}/></label></div><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button onClick={create} disabled={busy||!form.title||!form.genre}>{busy?'CREATING…':'CREATE GENRE BATTLE'}</button></div>
 {message&&<div className="ic-message" style={{marginTop:14}}>{message}</div>}
 <div style={{display:'grid',gap:24,marginTop:28}}>{contests.map(c=><ContestPanel key={c.id} contest={c} onChange={rows=>setContests(rows)} setMessage={setMessage}/>)}</div>
 </section>
}

function ContestPanel({contest,onChange,setMessage}:{contest:Contest;onChange:(rows:any[])=>void;setMessage:(s:string)=>void}){
 const [settings,setSettings]=useState<any>({...contest,qualifying_starts_at:localDate(contest.qualifying_starts_at),qualifying_ends_at:localDate(contest.qualifying_ends_at),live_starts_at:localDate(contest.live_starts_at)});
 const [entry,setEntry]=useState<any>({...emptyEntry});const [round,setRound]=useState<any>({title:'',entry_a_id:'',entry_b_id:''});const [busy,setBusy]=useState('');
 const currentRound=contest.rounds?.find((r:any)=>r.id===contest.current_round_id)||null;
 const currentA=currentRound?contest.entries?.find((e:any)=>e.id===currentRound.entry_a_id):null;const currentB=currentRound?contest.entries?.find((e:any)=>e.id===currentRound.entry_b_id):null;
 const origin=typeof window==='undefined'?'':window.location.origin;
 const publicUrl=`${origin}/battles/${contest.slug}`;
 const studioDj=`${origin}/battles/${contest.slug}/studio?slot=dj&token=${contest.host_code}`;
 const studioA=currentA?`${origin}/battles/${contest.slug}/studio?slot=a&token=${currentA.studio_code}`:'';
 const studioB=currentB?`${origin}/battles/${contest.slug}/studio?slot=b&token=${currentB.studio_code}`:'';
 const top=useMemo(()=>[...(contest.entries||[])].sort((a:any,b:any)=>(b.qualifying_votes||0)-(a.qualifying_votes||0)),[contest.entries]);
 async function act(name:string,extra:any={}){setBusy(name);setMessage('');try{const j=await request(name,{contestId:contest.id,...extra});onChange(j.contests||[]);setMessage('Live Battle control room updated.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function saveSettings(){await act('update_contest',{payload:{title:settings.title,genre:settings.genre,description:settings.description,status:settings.status,qualifying_starts_at:iso(settings.qualifying_starts_at),qualifying_ends_at:iso(settings.qualifying_ends_at),live_starts_at:iso(settings.live_starts_at),vote_window_seconds:Number(settings.vote_window_seconds)||30,zoom_session_name:settings.zoom_session_name,zoom_session_passcode:settings.zoom_session_passcode,sponsor_name:settings.sponsor_name,sponsor_logo_url:settings.sponsor_logo_url,sponsor_destination_url:settings.sponsor_destination_url,commercial_url:settings.commercial_url}})}
 async function addEntry(){if(!contest.genre)return setMessage('Set the competition genre first.');await act('add_entry',{payload:{...entry,genre:contest.genre}});setEntry({...emptyEntry})}
 async function addRound(){if(!round.entry_a_id||!round.entry_b_id)return setMessage('Choose Artist A and Artist B.');await act('add_round',{payload:round});setRound({title:'',entry_a_id:'',entry_b_id:''})}
 async function media(kind:'image_url'|'track_url'|'track_cover_url',file?:File){if(!file)return;setBusy(`upload-${kind}`);try{const url=await upload(file);setEntry((x:any)=>({...x,[kind]:url}));setMessage('Upload complete. Save the artist entry when ready.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function settingMedia(kind:'sponsor_logo_url'|'commercial_url',file?:File){if(!file)return;setBusy(`upload-${kind}`);try{const url=await upload(file);setSettings((x:any)=>({...x,[kind]:url}));setMessage('Upload complete. Click SAVE SHOW SETTINGS.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(`${label} copied.`)}catch{setMessage(value)}}
 return <article style={{border:'2px solid #111',background:'#fff'}}><header style={{padding:18,background:'#111',color:'#fff',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,letterSpacing:1.4,fontWeight:900,color:'#ff5566'}}>{String(contest.status).toUpperCase()} · {contest.genre?String(contest.genre).toUpperCase():'GENRE NOT SET'} · {String(contest.current_segment).replace('_',' ').toUpperCase()}</div><h2 style={{margin:'5px 0 0'}}>{contest.title}</h2></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>copy(publicUrl,'Public battle link')}>COPY PUBLIC LINK</button><button onClick={()=>act('update_contest',{payload:{status:'qualifying'}})} disabled={!!busy||!contest.genre}>OPEN QUALIFYING</button><button onClick={()=>act('update_contest',{payload:{status:'scheduled'}})} disabled={!!busy||!contest.genre}>SCHEDULE</button></div></header>
 <div style={{padding:18,display:'grid',gap:22}}>
  <details><summary style={{fontWeight:900,cursor:'pointer'}}>1. SHOW SETTINGS + SPONSOR</summary><div style={{display:'grid',gap:12,marginTop:16}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:10}}><label>Title<input value={settings.title||''} onChange={e=>setSettings({...settings,title:e.target.value})}/></label><label>Competition genre<select value={settings.genre||''} onChange={e=>setSettings({...settings,genre:e.target.value})}><option value="">Choose genre…</option>{GENRES.map(g=><option key={g} value={g}>{g}</option>)}</select></label></div><label>Description<textarea rows={3} value={settings.description||''} onChange={e=>setSettings({...settings,description:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label>Qualifying starts<input type="datetime-local" value={settings.qualifying_starts_at||''} onChange={e=>setSettings({...settings,qualifying_starts_at:e.target.value})}/></label><label>Qualifying ends<input type="datetime-local" value={settings.qualifying_ends_at||''} onChange={e=>setSettings({...settings,qualifying_ends_at:e.target.value})}/></label><label>Battle starts<input type="datetime-local" value={settings.live_starts_at||''} onChange={e=>setSettings({...settings,live_starts_at:e.target.value})}/></label><label>Vote seconds<input type="number" value={settings.vote_window_seconds||30} onChange={e=>setSettings({...settings,vote_window_seconds:e.target.value})}/></label></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Zoom Video SDK session name<input value={settings.zoom_session_name||''} onChange={e=>setSettings({...settings,zoom_session_name:e.target.value})}/></label><label>Session passcode (optional)<input value={settings.zoom_session_passcode||''} onChange={e=>setSettings({...settings,zoom_session_passcode:e.target.value})}/></label></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><label>Sponsor name<input value={settings.sponsor_name||''} onChange={e=>setSettings({...settings,sponsor_name:e.target.value})}/></label><label>Sponsor click URL<input value={settings.sponsor_destination_url||''} onChange={e=>setSettings({...settings,sponsor_destination_url:e.target.value})}/></label><label>Sponsor logo URL<input value={settings.sponsor_logo_url||''} onChange={e=>setSettings({...settings,sponsor_logo_url:e.target.value})}/><input type="file" accept="image/*" onChange={e=>settingMedia('sponsor_logo_url',e.target.files?.[0])}/></label></div><label>Commercial image/video URL<input value={settings.commercial_url||''} onChange={e=>setSettings({...settings,commercial_url:e.target.value})}/><input type="file" accept="image/*,video/*" onChange={e=>settingMedia('commercial_url',e.target.files?.[0])}/></label><button onClick={saveSettings} disabled={!!busy||!settings.genre}>SAVE SHOW SETTINGS</button></div></details>
  <details open><summary style={{fontWeight:900,cursor:'pointer'}}>2. ARTISTS + QUALIFYING LINKS</summary><div style={{marginTop:16,display:'grid',gap:14}}><div style={{padding:10,background:'#f5f5f5',fontSize:13}}><strong>{contest.genre||'No genre selected'} artists only.</strong> Artists from a different genre cannot be added to this competition.</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><label>Artist name<input value={entry.artist_name} onChange={e=>setEntry({...entry,artist_name:e.target.value})}/></label><label>Genre<input value={contest.genre||''} readOnly placeholder="Set competition genre first"/></label><label>City<input value={entry.city} onChange={e=>setEntry({...entry,city:e.target.value})}/></label><label>Track title<input value={entry.track_title} onChange={e=>setEntry({...entry,track_title:e.target.value})}/></label></div><label>Artist bio<textarea rows={3} value={entry.bio} onChange={e=>setEntry({...entry,bio:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}><label>Artist photo<input value={entry.image_url} onChange={e=>setEntry({...entry,image_url:e.target.value})}/><input type="file" accept="image/*" onChange={e=>media('image_url',e.target.files?.[0])}/></label><label>Music track<input value={entry.track_url} onChange={e=>setEntry({...entry,track_url:e.target.value})}/><input type="file" accept="audio/*" onChange={e=>media('track_url',e.target.files?.[0])}/></label><label>Track cover<input value={entry.track_cover_url} onChange={e=>setEntry({...entry,track_cover_url:e.target.value})}/><input type="file" accept="image/*" onChange={e=>media('track_cover_url',e.target.files?.[0])}/></label></div><button onClick={addEntry} disabled={!!busy||!entry.artist_name||!contest.genre}>ADD {contest.genre?String(contest.genre).toUpperCase():''} ARTIST TO COMPETITION</button><div style={{borderTop:'1px solid #ddd'}}>{top.map((e:any,i:number)=><div key={e.id} style={{display:'grid',gridTemplateColumns:'42px 1fr auto',gap:10,alignItems:'center',padding:'12px 0',borderBottom:'1px solid #eee'}}><strong>#{i+1}</strong><div><strong>{e.artist_name}</strong><div style={{fontSize:12,color:'#666'}}>{e.qualifying_votes||0} qualifying votes · {e.genre||'No genre'} · {e.track_title||'No track title'}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'end'}}><button onClick={()=>copy(`${origin}/battles/${contest.slug}/artists/${e.slug}`,`${e.artist_name} voting link`)}>COPY FAN LINK</button><button onClick={()=>act('delete_entry',{entryId:e.id})}>DELETE</button></div></div>)}</div></div></details>
  <details open><summary style={{fontWeight:900,cursor:'pointer'}}>3. LIVE ROUND BUILDER</summary><div style={{marginTop:16,display:'grid',gap:12}}><p style={{margin:0,color:'#666'}}>After qualifying, pick the two finalists. Both artists must match the competition genre. Each round can use the artists' uploaded tracks or a different track URL.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}><label>Round title<input value={round.title} onChange={e=>setRound({...round,title:e.target.value})} placeholder={`Round ${(contest.rounds?.length||0)+1}`}/></label><label>Artist A<select value={round.entry_a_id} onChange={e=>setRound({...round,entry_a_id:e.target.value})}><option value="">Choose…</option>{top.map((e:any)=><option key={e.id} value={e.id}>{e.artist_name}</option>)}</select></label><label>Artist B<select value={round.entry_b_id} onChange={e=>setRound({...round,entry_b_id:e.target.value})}><option value="">Choose…</option>{top.map((e:any)=><option key={e.id} value={e.id}>{e.artist_name}</option>)}</select></label></div><button onClick={addRound} disabled={!!busy}>ADD + ACTIVATE ROUND</button><div style={{display:'grid',gap:10}}>{(contest.rounds||[]).map((r:any)=>{const a=contest.entries.find((e:any)=>e.id===r.entry_a_id);const b=contest.entries.find((e:any)=>e.id===r.entry_b_id);const active=r.id===contest.current_round_id;return <div key={r.id} style={{padding:14,border:active?'2px solid #d71920':'1px solid #ddd',background:active?'#fff8f8':'#fafafa'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}><div><strong>{r.title||`Round ${r.round_number}`}</strong><div style={{fontSize:12,color:'#666'}}>{a?.artist_name} vs {b?.artist_name} · {r.status} · {r.votes_a}–{r.votes_b}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button onClick={()=>act('set_segment',{roundId:r.id,segment:'lobby'})}>ACTIVATE</button><button onClick={()=>act('set_segment',{roundId:r.id,segment:'artist_a'})}>PLAY A</button><button onClick={()=>act('set_segment',{roundId:r.id,segment:'artist_b'})}>PLAY B</button><button onClick={()=>act('set_segment',{roundId:r.id,segment:'voting'})}>OPEN {contest.vote_window_seconds}s VOTE</button><button onClick={()=>act('close_round',{roundId:r.id})}>CLOSE + TALLY</button><button onClick={()=>act('delete_round',{roundId:r.id})}>DELETE</button></div></div></div>})}</div></div></details>
  <details open><summary style={{fontWeight:900,cursor:'pointer'}}>4. LIVE CONTROL + PRIVATE STUDIO LINKS</summary><div style={{marginTop:16,display:'grid',gap:12}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>act('set_segment',{roundId:contest.current_round_id,segment:'lobby'})}>LOBBY</button><button onClick={()=>act('set_segment',{roundId:contest.current_round_id,segment:'commercial'})} disabled={!contest.commercial_url}>RUN COMMERCIAL</button><button onClick={()=>act('set_segment',{roundId:contest.current_round_id,segment:'results'})}>SHOW RESULTS</button><button onClick={()=>act('finalize_contest')}>FINALIZE + CROWN WINNER</button></div>{currentRound?<div style={{padding:14,background:'#111',color:'#fff'}}><strong>PRIVATE STUDIO LINKS — current round</strong><p style={{fontSize:12,color:'#bbb'}}>Send one link to each person. The DJ link has host privileges. Do not publish these links.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>copy(studioA,`${currentA?.artist_name||'Artist A'} studio link`)}>COPY ARTIST A STUDIO</button><button onClick={()=>copy(studioDj,'DJ studio link')}>COPY DJ STUDIO</button><button onClick={()=>copy(studioB,`${currentB?.artist_name||'Artist B'} studio link`)}>COPY ARTIST B STUDIO</button></div></div>:<div style={{padding:14,background:'#fff7dd'}}>Add or activate a live round to generate the Artist A / DJ / Artist B studio links.</div>}<div style={{fontSize:12,color:'#666'}}>Public battle: {publicUrl}</div></div></details>
  <div style={{display:'flex',justifyContent:'space-between',gap:10,borderTop:'1px solid #ddd',paddingTop:16}}><span style={{fontSize:12,color:'#777'}}>Battle ID: {contest.id}</span><button onClick={()=>{if(confirm('Delete this entire battle, all entries, rounds and votes?'))act('delete_contest')}} style={{color:'#b00020'}}>DELETE ENTIRE BATTLE</button></div>
 </div></article>
}