'use client';

import {useEffect,useMemo,useState} from 'react';

export default function BattleSubmissionsManager(){
 const [rows,setRows]=useState<any[]>([]);const [contests,setContests]=useState<any[]>([]);const [targets,setTargets]=useState<Record<string,string>>({});const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 async function load(){try{const r=await fetch('/api/admin/battle-submissions',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load submissions');setRows(j.submissions||[]);setContests(j.contests||[])}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 const pending=useMemo(()=>rows.filter(x=>x.status==='pending'),[rows]);const recent=useMemo(()=>rows.filter(x=>x.status!=='pending').slice(0,20),[rows]);
 async function act(action:string,row:any){setBusy(row.id+action);setMessage('');try{const r=await fetch('/api/admin/battle-submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,submissionId:row.id,contestId:targets[row.id]||contests[0]?.id||''})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Update failed');setRows(j.submissions||[]);setContests(j.contests||[]);setMessage(action==='approve'?`${row.artist_name} was added to the competition. Fan profile is ready.`:'Submission updated.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 function card(row:any,history=false){return <article key={row.id} style={{border:'1px solid #ddd',padding:16,background:'#fff',display:'grid',gridTemplateColumns:row.image_url?'110px 1fr':'1fr',gap:16}}>{row.image_url&&<img src={row.image_url} alt="" style={{width:110,height:110,objectFit:'cover'}}/>}<div><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong style={{fontSize:20}}>{row.artist_name}</strong><div style={{fontSize:13,color:'#666'}}>{row.track_title}{row.genre?` · ${row.genre}`:''}{row.city?` · ${row.city}`:''}</div><div style={{fontSize:12,color:'#888',marginTop:4}}>{row.email}{row.social_handle?` · ${row.social_handle}`:''}</div></div><span style={{fontWeight:900,fontSize:12,textTransform:'uppercase'}}>{row.status}</span></div>{row.bio&&<p style={{margin:'10px 0',color:'#555'}}>{row.bio}</p>}{row.track_url&&<audio controls preload="none" src={row.track_url} style={{width:'100%',margin:'8px 0'}}/>}{!history?<div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',marginTop:10}}><select value={targets[row.id]||contests[0]?.id||''} onChange={e=>setTargets({...targets,[row.id]:e.target.value})} style={{minWidth:220}}><option value="">Choose competition…</option>{contests.map(c=><option key={c.id} value={c.id}>{c.title} · {c.status}</option>)}</select><button onClick={()=>act('approve',row)} disabled={!!busy||!contests.length}>APPROVE TO PHASE ONE</button><button onClick={()=>act('reject',row)} disabled={!!busy}>REJECT</button></div>:<div style={{display:'flex',gap:8,marginTop:10}}>{row.status==='rejected'&&<button onClick={()=>act('reopen',row)} disabled={!!busy}>RETURN TO PENDING</button>}<button onClick={()=>act('delete',row)} disabled={!!busy}>DELETE RECORD</button></div>}</div></article>}
 return <section className="ic-module-panel" style={{marginBottom:24}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>Phase One Artist Submissions</h2><p style={{margin:0,maxWidth:760}}>Artists who submit from the public Live Battles page land here. Review the song, choose a competition and approve it to generate the artist's fan-voting profile.</p></div><strong>{pending.length} PENDING</strong></div>{message&&<div className="ic-message" style={{marginTop:14}}>{message}</div>}<div style={{display:'grid',gap:12,marginTop:18}}>{pending.length?pending.map(r=>card(r)):<div style={{padding:24,border:'1px dashed #ccc',textAlign:'center',color:'#777'}}>No pending artist submissions.</div>}</div>{recent.length>0&&<details style={{marginTop:18}}><summary style={{fontWeight:900,cursor:'pointer'}}>RECENTLY REVIEWED ({recent.length})</summary><div style={{display:'grid',gap:10,marginTop:12}}>{recent.map(r=>card(r,true))}</div></details>}</section>
}
