'use client';

import {useEffect,useMemo,useState} from 'react';

export default function BattleSubmissionsManager(){
 const [rows,setRows]=useState<any[]>([]);const [contests,setContests]=useState<any[]>([]);const [targets,setTargets]=useState<Record<string,string>>({});const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 async function load(){try{const r=await fetch('/api/admin/battle-submissions',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load submissions');setRows(j.submissions||[]);setContests(j.contests||[])}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 const pending=useMemo(()=>rows.filter(x=>x.status==='pending'),[rows]);const recent=useMemo(()=>rows.filter(x=>x.status!=='pending').slice(0,30),[rows]);
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(`${label} copied.`)}catch{setMessage(value)}}
 async function act(action:string,row:any){setBusy(row.id+action);setMessage('');try{const r=await fetch('/api/admin/battle-submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,submissionId:row.id,contestId:targets[row.id]||contests[0]?.id||''})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Update failed');setRows(j.submissions||[]);setContests(j.contests||[]);if(action==='approve'){const path=j.entry?.fan_path||'';setMessage(`${row.artist_name} is approved for Phase One.${path?' Fan-voting page created: '+window.location.origin+path:''}`)}else setMessage('Submission updated.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}}
 function card(row:any,history=false){const fanUrl=row.fan_path?`${typeof window==='undefined'?'':window.location.origin}${row.fan_path}`:'';return <article key={row.id} style={{border:'1px solid #ddd',padding:16,background:'#fff',display:'grid',gridTemplateColumns:row.image_url?'110px 1fr':'1fr',gap:16}}>{row.image_url&&<img src={row.image_url} alt="" style={{width:110,height:110,objectFit:'cover'}}/>}<div><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong style={{fontSize:20}}>{row.artist_name}</strong><div style={{fontSize:13,color:'#666'}}>{row.track_title}{row.genre?` · ${row.genre}`:''}{row.city?` · ${row.city}`:''}</div><div style={{fontSize:12,color:'#555',marginTop:6}}><strong>EMAIL:</strong> {row.email||'—'}{row.phone?<><span> · </span><strong>PHONE:</strong> {row.phone}</>:null}</div>{row.social_handle&&<div style={{fontSize:12,color:'#888',marginTop:3}}>{row.social_handle}</div>}</div><span style={{fontWeight:900,fontSize:12,textTransform:'uppercase'}}>{row.status}</span></div>{row.bio&&<p style={{margin:'10px 0',color:'#555'}}>{row.bio}</p>}{row.track_url&&<div style={{margin:'12px 0',padding:'12px 14px',background:'#f5f5f5',border:'1px solid #e5e5e5'}}><div style={{fontSize:11,fontWeight:900,letterSpacing:1,marginBottom:7}}>SUBMITTED SONG — LISTEN BEFORE APPROVING</div><audio controls preload="none" src={row.track_url} style={{width:'100%'}}/></div>}{!history?<div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',marginTop:10}}><select value={targets[row.id]||contests[0]?.id||''} onChange={e=>setTargets({...targets,[row.id]:e.target.value})} style={{minWidth:220}}><option value="">Choose competition…</option>{contests.map(c=><option key={c.id} value={c.id}>{c.title} · {c.status}</option>)}</select><button onClick={()=>act('approve',row)} disabled={!!busy||!contests.length}>APPROVE + CREATE FAN PAGE</button><button onClick={()=>act('reject',row)} disabled={!!busy}>REJECT</button></div>:<div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}>{row.status==='approved'&&fanUrl&&<><a href={fanUrl} target="_blank" rel="noreferrer" style={{display:'inline-block',padding:'9px 12px',background:'#111',color:'#fff',textDecoration:'none',fontWeight:900,fontSize:12}}>OPEN FAN PAGE ↗</a><button onClick={()=>copy(fanUrl,`${row.artist_name} fan link`)}>COPY FAN LINK</button></>}{row.status==='rejected'&&<button onClick={()=>act('reopen',row)} disabled={!!busy}>RETURN TO PENDING</button>}<button onClick={()=>act('delete',row)} disabled={!!busy}>DELETE RECORD</button></div>}</div></article>}
 return <section className="ic-module-panel" style={{marginBottom:24}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 6px'}}>Phase One Artist Submissions</h2><p style={{margin:0,maxWidth:800}}>Every upload lands here as <strong>Pending Review</strong>. Listen to the submitted song, review the artist and contact details, then approve or reject it. Approval creates the artist's Phase One fan-voting profile and shareable link.</p></div><strong>{pending.length} PENDING</strong></div>{message&&<div className="ic-message" style={{marginTop:14}}>{message}</div>}<div style={{display:'grid',gap:12,marginTop:18}}>{pending.length?pending.map(r=>card(r)):<div style={{padding:24,border:'1px dashed #ccc',textAlign:'center',color:'#777'}}>No pending artist submissions.</div>}</div>{recent.length>0&&<details style={{marginTop:18}}><summary style={{fontWeight:900,cursor:'pointer'}}>RECENTLY REVIEWED ({recent.length})</summary><div style={{display:'grid',gap:10,marginTop:12}}>{recent.map(r=>card(r,true))}</div></details>}</section>
}
