'use client';
import {useEffect,useState} from 'react';
type Lead={creator_name:string;creator_type:string;field?:string;city?:string;independence_status:string;independence_note?:string;why_now?:string;momentum_score?:number;sources?:string[];story_angle?:string;image_url?:string;website?:string;instagram?:string;youtube?:string};
export default function IndieSpotlightAgent(){
 const [focus,setFocus]=useState('Independent music artists, filmmakers and creators with meaningful current momentum');
 const [count,setCount]=useState(10);const [days,setDays]=useState(30);const [leads,setLeads]=useState<Lead[]>([]);const [busy,setBusy]=useState(false);const [action,setAction]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/indie-spotlight/scan').then(r=>r.json()).then(j=>{if(j.scan?.creators)setLeads(j.scan.creators)}).catch(()=>{})},[]);
 async function scan(){setBusy(true);setMessage('Searching and verifying independent creators…');try{const r=await fetch('/api/indie-spotlight/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({focus,count,days})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Scan failed');setLeads(j.creators||[]);setMessage(`${(j.creators||[]).length} verified/qualified creator lead(s) found.`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function draft(x:Lead,i:number){setAction(String(i));setMessage(`Writing a verified spotlight draft for ${x.creator_name}…`);try{const r=await fetch('/api/indie-spotlight/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creator:x})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Draft failed');setMessage(j.message)}catch(e:any){setMessage(e.message)}finally{setAction('')}}
 return <section className="ic-module-panel"><div className="ic-admin-eyebrow">INDEPENDENT CREATOR DISCOVERY</div><h2>Indie Spotlight AI Agent</h2><p>This agent is separate from the main AI Content Agent. It searches specifically for independent music artists, filmmakers and other creators, verifies independence and current momentum, and prepares review-ready Indie Spotlight drafts.</p><div className="ic-two"><label>Discovery focus<input value={focus} onChange={e=>setFocus(e.target.value)}/></label><label>Momentum window<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option><option value={60}>60 days</option></select></label></div><label>Maximum creators<input type="number" min="3" max="20" value={count} onChange={e=>setCount(Math.min(20,Math.max(3,Number(e.target.value)||10)))}/></label><div className="ic-actions"><button onClick={scan} disabled={busy}>{busy?'SEARCHING…':'FIND INDEPENDENT CREATORS'}</button><a className="ic-link-button" href="/indie-spotlight">VIEW INDIE SPOTLIGHT →</a></div>{message&&<div className="ic-message">{message}</div>}<div className="ic-agent-results" style={{display:'grid',gap:14,marginTop:18}}>{leads.map((x,i)=><article className="ic-agent-card" key={x.creator_name+i}>{x.image_url&&<img className="ic-agent-thumb" src={x.image_url} alt={x.creator_name}/>}<div style={{flex:1}}><span className="ic-status-pill">{String(x.creator_type||'creator').toUpperCase()} · {String(x.independence_status||'').replaceAll('_',' ').toUpperCase()}</span><h3>{x.creator_name}</h3>{x.field&&<p><strong>{x.field}</strong>{x.city?` · ${x.city}`:''}</p>}{x.why_now&&<p>{x.why_now}</p>}{x.independence_note&&<p><small><strong>Independence check:</strong> {x.independence_note}</small></p>}{x.story_angle&&<p><strong>Story angle:</strong> {x.story_angle}</p>}<div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{(x.sources||[]).slice(0,4).map((u,n)=><a key={u+n} href={u} target="_blank" rel="noreferrer">Source {n+1} ↗</a>)}</div><button style={{marginTop:12}} disabled={!!action} onClick={()=>draft(x,i)}>{action===String(i)?'WRITING…':'CREATE SPOTLIGHT DRAFT'}</button></div></article>)}</div></section>
}