'use client';

import {useEffect,useMemo,useState} from 'react';
import styles from './PressReleaseManager.module.css';

const blank:any={contact_id:'',artist_name:'',release_title:'',release_type:'single',release_date:'',genre:'',city:'',country:'United States',music_url:'',artwork_url:'',youtube_url:'',artist_website:'',media_contact_name:'',media_contact_email:'',key_facts:'',article_headline:'',article_subheadline:'',article_body:'',press_title:'',press_summary:'',press_content:'',press_categories:[],distribution_plan:'basic'};

type Tab='create'|'copy'|'distribution'|'history';

async function jsonCall(body:any){const r=await fetch('/api/admin/press-releases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Press release request failed.');return j}
function words(v:any){return String(v||'').replace(/<[^>]+>/g,' ').trim().split(/\s+/).filter(Boolean).length}
function dateText(v:any){if(!v)return '—';try{return new Date(v).toLocaleString()}catch{return String(v)}}
function providerUrls(release:any){const value=release?.provider_links;const all:Array<{url:string;label:string}>=[];const visit=(x:any,label='Placement')=>{if(!x)return;if(typeof x==='string'&&/^https?:\/\//.test(x))all.push({url:x,label});else if(Array.isArray(x))x.forEach((y,i)=>visit(y,`${label} ${i+1}`));else if(typeof x==='object')for(const [k,v] of Object.entries(x))visit(v,k)};visit(value);return all.slice(0,50)}

export default function PressReleaseManager(){
 const [tab,setTab]=useState<Tab>('create');const [form,setForm]=useState<any>({...blank});const [releases,setReleases]=useState<any[]>([]);const [contacts,setContacts]=useState<any[]>([]);const [provider,setProvider]=useState<any>({connected:false});const [categories,setCategories]=useState<string[]>([]);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [isError,setIsError]=useState(false);
 const current=useMemo(()=>releases.find(x=>x.id===form.id)||form,[releases,form]);const links=useMemo(()=>providerUrls(current),[current]);
 async function load(selectId?:string){try{const [pr,crm]=await Promise.all([fetch('/api/admin/press-releases',{cache:'no-store'}),fetch('/api/admin/crm',{cache:'no-store'})]);const a=await pr.json();const b=await crm.json();if(!pr.ok)throw new Error(a.error||'Unable to load press releases.');setReleases(a.releases||[]);setProvider(a.provider||{connected:false});setCategories(a.categories||[]);if(crm.ok)setContacts(b.contacts||[]);if(selectId){const found=(a.releases||[]).find((x:any)=>x.id===selectId);if(found)setForm({...blank,...found,release_date:found.release_date||''});}}catch(e:any){setMessage(e.message);setIsError(true)}}
 useEffect(()=>{load()},[]);
 function flash(text:string,error=false){setMessage(text);setIsError(error)}
 function chooseContact(id:string){const c=contacts.find(x=>x.id===id);if(!c){setForm({...form,contact_id:''});return}setForm({...form,contact_id:id,artist_name:c.artist_name||c.full_name||form.artist_name,genre:c.genre||form.genre,city:c.city||form.city,artist_website:c.website_url||form.artist_website,media_contact_name:c.full_name||form.media_contact_name,media_contact_email:c.email||form.media_contact_email,youtube_url:c.youtube_url||form.youtube_url})}
 async function upload(file:File|undefined,field:string){if(!file)return;setBusy(`upload-${field}`);flash('');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed.');setForm((v:any)=>({...v,[field]:j.publicUrl}));flash(`${field==='music_url'?'Music':'Artwork'} uploaded.`)}catch(e:any){flash(e.message,true)}finally{setBusy('')}}
 async function save(){setBusy('save');flash('');try{const j=await jsonCall({action:'save',id:form.id,release:form});setForm({...blank,...j.release,release_date:j.release.release_date||''});await load(j.release.id);flash('Press release project saved.')}catch(e:any){flash(e.message,true)}finally{setBusy('')}}
 async function generate(){setBusy('generate');flash('');try{const j=await jsonCall({action:'generate',id:form.id,release:form});setForm({...blank,...j.release,release_date:j.release.release_date||''});await load(j.release.id);setTab('copy');flash('IndieCut article and press release generated. Review both before using them.')}catch(e:any){flash(e.message,true)}finally{setBusy('')}}
 async function updateAction(action:string,success:string){if(!form.id){flash('Save or generate this project first.',true);return}setBusy(action);flash('');try{const j=await jsonCall({action,id:form.id,release:form});if(j.release)setForm({...blank,...j.release,release_date:j.release.release_date||''});await load(form.id);flash(success)}catch(e:any){flash(e.message,true)}finally{setBusy('')}}
 async function remove(id:string){if(!confirm('Delete this local press release draft?'))return;setBusy(`delete-${id}`);try{await jsonCall({action:'delete',id});if(form.id===id)setForm({...blank});await load();flash('Draft deleted.')}catch(e:any){flash(e.message,true)}finally{setBusy('')}}
 function newProject(){setForm({...blank});setTab('create');flash('')}
 function editRelease(r:any){setForm({...blank,...r,release_date:r.release_date||''});setTab('create');flash('')}
 function toggleCategory(c:string){setForm((v:any)=>({...v,press_categories:(v.press_categories||[]).includes(c)?v.press_categories.filter((x:string)=>x!==c):[...(v.press_categories||[]),c].slice(0,5)}))}
 const submitted=Boolean(form.provider_release_id||form.provider_slug_id);
 return <section className={styles.shell}>
  <header className={styles.head}><div><div className={styles.kicker}>ARTIST CRM · PRESS & MEDIA</div><h2>Press Release Studio</h2><p>Upload the artist package, generate an IndieCut-ready editorial draft plus a professional press release, send the article to IndieCut drafts, and distribute the approved release through PRNow.</p></div><div className={styles.connection}><div><span className={provider.connected?styles.dotOn:styles.dotOff}/><strong>{provider.connected?'PRNow connected':'PRNow not connected'}</strong></div><div style={{marginTop:5,color:'#c7d7e1'}}>{provider.connected?(provider.account?.company||provider.account?.email||'API verified'):(provider.reason||'API key required')}</div>{provider.connected&&provider.account?.credits!==undefined&&<div style={{marginTop:5}}>Credits: <b>{provider.account.credits}</b></div>}</div></header>
  <nav className={styles.tabs}><button className={`${styles.tab} ${tab==='create'?styles.tabActive:''}`} onClick={()=>setTab('create')}>1. Artist package</button><button className={`${styles.tab} ${tab==='copy'?styles.tabActive:''}`} onClick={()=>setTab('copy')}>2. Generated copy</button><button className={`${styles.tab} ${tab==='distribution'?styles.tabActive:''}`} onClick={()=>setTab('distribution')}>3. Distribution</button><button className={`${styles.tab} ${tab==='history'?styles.tabActive:''}`} onClick={()=>setTab('history')}>History</button></nav>
  <div className={styles.content}>
   {message&&<div className={`${styles.notice} ${isError?styles.error:''}`}>{message}</div>}
   {tab==='create'&&<div className={styles.split}><div>
    <div className={styles.panel}><h3>Artist & release</h3><p>Select a CRM contact to prefill what we already know, then add the release details.</p>
     <label className={styles.label}>Artist CRM contact<select className={styles.select} value={form.contact_id||''} onChange={e=>chooseContact(e.target.value)}><option value="">Manual / not in CRM</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.artist_name||c.full_name||c.email||'Unnamed'}{c.genre?` · ${c.genre}`:''}</option>)}</select></label>
     <div className={styles.grid2}><label className={styles.label}>Artist name<input className={styles.input} value={form.artist_name||''} onChange={e=>setForm({...form,artist_name:e.target.value})}/></label><label className={styles.label}>Release title<input className={styles.input} value={form.release_title||''} onChange={e=>setForm({...form,release_title:e.target.value})}/></label></div>
     <div className={styles.grid3}><label className={styles.label}>Type<select className={styles.select} value={form.release_type||'single'} onChange={e=>setForm({...form,release_type:e.target.value})}><option value="single">Single</option><option value="album">Album</option><option value="ep">EP</option><option value="video">Music video</option><option value="tour">Tour / live announcement</option><option value="other">Other</option></select></label><label className={styles.label}>Release date<input type="date" className={styles.input} value={form.release_date||''} onChange={e=>setForm({...form,release_date:e.target.value})}/></label><label className={styles.label}>Genre<input className={styles.input} value={form.genre||''} onChange={e=>setForm({...form,genre:e.target.value})}/></label></div>
     <div className={styles.grid2}><label className={styles.label}>City<input className={styles.input} value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Required for PR distribution"/></label><label className={styles.label}>Country<input className={styles.input} value={form.country||''} onChange={e=>setForm({...form,country:e.target.value})}/></label></div>
    </div>
    <div className={styles.panel}><h3>Music, artwork & links</h3><p>The music upload is stored as part of the artist package. AI copy is based on the supplied facts and verifiable public information; it does not pretend to hear or review the song.</p>
     <label className={styles.label}>Music file or public music URL<div className={styles.uploadRow}><input className={styles.input} value={form.music_url||''} onChange={e=>setForm({...form,music_url:e.target.value})} placeholder="Spotify, SoundCloud, or uploaded audio URL"/><label className={styles.button}>{busy==='upload-music_url'?'Uploading…':'Upload'}<input type="file" accept="audio/*" hidden onChange={e=>upload(e.target.files?.[0],'music_url')}/></label></div></label>
     <label className={styles.label}>Artwork<div className={styles.uploadRow}><input className={styles.input} value={form.artwork_url||''} onChange={e=>setForm({...form,artwork_url:e.target.value})}/><label className={styles.button}>{busy==='upload-artwork_url'?'Uploading…':'Upload'}<input type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0],'artwork_url')}/></label></div></label>
     <div className={styles.grid2}><label className={styles.label}>YouTube / video URL<input className={styles.input} value={form.youtube_url||''} onChange={e=>setForm({...form,youtube_url:e.target.value})}/></label><label className={styles.label}>Artist website<input className={styles.input} value={form.artist_website||''} onChange={e=>setForm({...form,artist_website:e.target.value})}/></label></div>
    </div>
    <div className={styles.panel}><h3>Story facts & media contact</h3><div className={styles.grid2}><label className={styles.label}>Media contact name<input className={styles.input} value={form.media_contact_name||''} onChange={e=>setForm({...form,media_contact_name:e.target.value})}/></label><label className={styles.label}>Media contact email<input className={styles.input} value={form.media_contact_email||''} onChange={e=>setForm({...form,media_contact_email:e.target.value})}/></label></div><label className={styles.label}>Key facts / artist story<textarea rows={9} className={styles.textarea} value={form.key_facts||''} onChange={e=>setForm({...form,key_facts:e.target.value})} placeholder="Background, what is being announced, collaborators, producer, label, verified milestones, quotes you own, why this release matters, etc."/></label><div className={styles.actions}><button className={styles.button} disabled={!!busy} onClick={save}>{busy==='save'?'Saving…':'Save project'}</button><button className={`${styles.button} ${styles.primary}`} disabled={!!busy||!form.artist_name||!form.release_title} onClick={generate}>{busy==='generate'?'Researching & writing…':'Generate article + press release'}</button></div></div>
   </div><aside className={styles.sidebar}><h4>Current project</h4><div className={styles.metric}><span>Status</span><b><span className={styles.status}>{form.status||'new'}</span></b></div><div className={styles.metric}><span>Artist</span><b>{form.artist_name||'—'}</b></div><div className={styles.metric}><span>Release</span><b>{form.release_title||'—'}</b></div><div className={styles.metric}><span>IndieCut draft</span><b>{form.article_id?'Created':'Not created'}</b></div><div className={styles.metric}><span>PRNow</span><b>{form.provider_status||'Not submitted'}</b></div>{form.artwork_url&&<img src={form.artwork_url} alt="Artwork" style={{width:'100%',marginTop:12,display:'block'}}/>}</aside></div>}
   {tab==='copy'&&<div className={styles.split}><div><div className={styles.panel}><h3>IndieCut editorial draft</h3><p>This stays a draft until an editor reviews and publishes it.</p><label className={styles.label}>Headline<input className={styles.input} value={form.article_headline||''} onChange={e=>setForm({...form,article_headline:e.target.value})}/></label><label className={styles.label}>Subheadline<input className={styles.input} value={form.article_subheadline||''} onChange={e=>setForm({...form,article_subheadline:e.target.value})}/></label><label className={styles.label}>Article body<textarea rows={20} className={styles.textarea} value={form.article_body||''} onChange={e=>setForm({...form,article_body:e.target.value})}/></label><div className={styles.actions}><button className={styles.button} disabled={!!busy} onClick={save}>Save edits</button><button className={`${styles.button} ${styles.dark}`} disabled={!!busy||!form.id||!form.article_body} onClick={()=>updateAction('article_draft','IndieCut article draft created. Open Articles to review and publish it.')}>{busy==='article_draft'?'Creating draft…':form.article_id?'IndieCut draft created':'Send to IndieCut drafts'}</button></div></div>
    <div className={styles.panel}><h3>Distribution press release</h3><label className={styles.label}>Press headline<input className={styles.input} value={form.press_title||''} onChange={e=>setForm({...form,press_title:e.target.value})}/></label><label className={styles.label}>Summary<textarea rows={3} className={styles.textarea} value={form.press_summary||''} onChange={e=>setForm({...form,press_summary:e.target.value})}/></label><label className={styles.label}>Press release HTML<textarea rows={22} className={styles.textarea} value={form.press_content||''} onChange={e=>setForm({...form,press_content:e.target.value})}/></label><div className={styles.small}>PRNow body word count: {words(form.press_content)} / 250–1,200 required</div><div className={styles.actions}><button className={styles.button} disabled={!!busy} onClick={save}>Save edits</button><button className={`${styles.button} ${styles.primary}`} onClick={()=>setTab('distribution')}>Continue to distribution →</button></div></div></div><aside className={styles.sidebar}><h4>Editorial checks</h4><div className={styles.metric}><span>Article words</span><b>{words(form.article_body)}</b></div><div className={styles.metric}><span>Press words</span><b>{words(form.press_content)}</b></div><div className={styles.metric}><span>Headline words</span><b>{words(form.press_title)}</b></div><div className={styles.metric}><span>Categories</span><b>{(form.press_categories||[]).length}</b></div><p className={styles.small} style={{marginTop:12}}>Generated material should be reviewed for names, dates, quotes and claims before publication or paid distribution.</p></aside></div>}
   {tab==='distribution'&&<div className={styles.split}><div><div className={styles.panel}><h3>PRNow distribution</h3><p>Choose the distribution level, category, and submit only after the release is final. PRNow does not allow edits after submission once processing starts.</p><div className={styles.plan}><button className={form.distribution_plan==='basic'?styles.active:''} onClick={()=>setForm({...form,distribution_plan:'basic'})}><strong>Basic · $15/release</strong><span>400+ publishers · same-day distribution</span></button><button className={form.distribution_plan==='standard'?styles.active:''} onClick={()=>setForm({...form,distribution_plan:'standard'})}><strong>Standard · $29/release</strong><span>500+ publishers + premium TV/radio network</span></button></div></div>
    <div className={styles.panel}><h3>Categories</h3><p>Choose up to five categories accepted by the distribution provider.</p>{categories.length?<div className={styles.categoryGrid}>{categories.map(c=><label className={styles.category} key={c}><input type="checkbox" checked={(form.press_categories||[]).includes(c)} disabled={!(form.press_categories||[]).includes(c)&&(form.press_categories||[]).length>=5} onChange={()=>toggleCategory(c)}/>{c}</label>)}</div>:<div className={styles.empty}>Provider categories will appear when the PRNow reference endpoint is available.</div>}</div>
    <div className={styles.panel}><h3>Final submission</h3><div className={styles.grid3}><div><span className={styles.small}>City</span><div>{form.city||'Missing'}</div></div><div><span className={styles.small}>Country</span><div>{form.country||'Missing'}</div></div><div><span className={styles.small}>Press words</span><div>{words(form.press_content)}</div></div></div><div className={styles.actions}><button className={styles.button} onClick={save} disabled={!!busy}>Save changes</button><button className={`${styles.button} ${styles.primary}`} disabled={!!busy||submitted||!provider.connected} onClick={()=>updateAction('submit','Release submitted to PRNow. Use Refresh status to track review and placements.')}>{busy==='submit'?'Submitting…':submitted?'Already submitted':'Distribute now'}</button>{submitted&&<button className={styles.button} disabled={!!busy} onClick={()=>updateAction('refresh','Distribution status refreshed.')}>{busy==='refresh'?'Refreshing…':'Refresh status'}</button>}{form.provider_status==='pending'&&<button className={`${styles.button} ${styles.danger}`} disabled={!!busy} onClick={()=>updateAction('retract','Release retracted and provider credits returned.')}>{busy==='retract'?'Retracting…':'Retract pending release'}</button>}</div>{!provider.connected&&<div className={`${styles.notice} ${styles.error}`} style={{marginTop:12}}>The studio is built, but live third-party distribution is disabled until the server has a valid PRNOW_API_KEY.</div>}</div>
   </div><aside className={styles.sidebar}><h4>Distribution status</h4><div className={styles.metric}><span>Local status</span><b>{form.status||'draft'}</b></div><div className={styles.metric}><span>Provider status</span><b>{form.provider_status||'—'}</b></div><div className={styles.metric}><span>Provider ID</span><b>{form.provider_slug_id||form.provider_release_id||'—'}</b></div><div className={styles.metric}><span>Submitted</span><b>{dateText(form.submitted_at)}</b></div>{form.provider_status_reason&&<div className={`${styles.notice} ${styles.error}`} style={{marginTop:10}}>{form.provider_status_reason}</div>}{links.length>0&&<div className={styles.providerLinks}><strong>Placement links</strong>{links.map((l,i)=><a key={`${l.url}-${i}`} href={l.url} target="_blank" rel="noreferrer">{l.label}: {l.url}</a>)}</div>}</aside></div>}
   {tab==='history'&&<div><div className={styles.actions} style={{marginBottom:12}}><button className={`${styles.button} ${styles.primary}`} onClick={newProject}>+ New press release</button><button className={styles.button} onClick={()=>load()}>Refresh</button></div>{releases.length?<div style={{overflow:'auto'}}><table className={styles.history}><thead><tr><th>Artist / Release</th><th>Status</th><th>IndieCut</th><th>PRNow</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{releases.map(r=><tr key={r.id}><td><strong>{r.artist_name}</strong><br/><span className={styles.small}>{r.release_title}</span></td><td><span className={styles.status}>{r.status}</span></td><td>{r.article_id?'Draft created':'—'}</td><td>{r.provider_status||'—'}</td><td>{dateText(r.updated_at)}</td><td><div className={styles.actions} style={{marginTop:0}}><button className={styles.button} onClick={()=>editRelease(r)}>Open</button>{(r.provider_release_id||r.provider_slug_id)&&<button className={styles.button} onClick={()=>{setForm({...blank,...r,release_date:r.release_date||''});setTimeout(()=>updateAction('refresh','Distribution status refreshed.'),0)}}>Refresh PR</button>}{!r.provider_release_id&&!r.provider_slug_id&&<button className={`${styles.button} ${styles.danger}`} disabled={busy===`delete-${r.id}`} onClick={()=>remove(r.id)}>Delete</button>}</div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No press release projects yet.</div>}</div>}
  </div>
 </section>
}
