'use client';import {useEffect,useState} from 'react';
export default function RadioProgramming(){const [d,setD]=useState<any>({media:[],schedule:[],rotations:[]}),[msg,setMsg]=useState('');const [media,setMedia]=useState<any>({kind:'music'}),[event,setEvent]=useState<any>({event_type:'show',recurrence:'none'}),[rotation,setRotation]=useState<any>({weight:1});
 const load=()=>fetch('/api/admin/radio-programming',{cache:'no-store'}).then(r=>r.json()).then(setD);useEffect(()=>{load()},[]);
 const send=async(action:string,payload?:any,id?:string)=>{setMsg('Saving…');const r=await fetch('/api/admin/radio-programming',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload,id})});const j=await r.json();setMsg(r.ok?'Saved.':j.error||'Failed');if(r.ok)load()};
 const inp=(obj:any,set:any,k:string,label:string,type='text')=><label style={{display:'grid',gap:6,fontWeight:800}}>{label}<input type={type} value={obj[k]||''} onChange={e=>set({...obj,[k]:e.target.value})} style={{padding:11,border:'1px solid #ccc'}}/></label>;
 return <section style={{maxWidth:1050,margin:'18px auto 50px',padding:'0 24px'}}><div className="panel" style={{padding:24}}><div className="kicker">PROGRAMMING DESK</div><h2>24/7 Broadcast Programming</h2><p>Build the station library, schedule shows and commercial breaks, and control the automation clock.</p>{msg&&<div className="ic-message">{msg}</div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18,marginTop:20}}>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Add Audio</h3><label>Type<select value={media.kind} onChange={e=>setMedia({...media,kind:e.target.value})}><option value="music">Music</option><option value="commercial">Commercial</option><option value="show">Show / Podcast</option><option value="station_id">Station ID / Promo</option></select></label>{inp(media,setMedia,'title','Title')}{inp(media,setMedia,'artist_or_host','Artist / Host')}{inp(media,setMedia,'audio_url','Audio URL')}{inp(media,setMedia,'artwork_url','Artwork URL')}<button onClick={()=>send('media',media)}>ADD TO LIBRARY</button></div>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Schedule Broadcast</h3><label>Type<select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}><option value="show">Show</option><option value="podcast">Podcast</option><option value="commercial_break">Commercial Break</option><option value="music_block">Music Block</option><option value="live">Live Show</option></select></label>{inp(event,setEvent,'title','Program title')}{inp(event,setEvent,'starts_at','Start date & time','datetime-local')}{inp(event,setEvent,'ends_at','End date & time','datetime-local')}<label>Audio / episode<select value={event.media_id||''} onChange={e=>setEvent({...event,media_id:e.target.value})}><option value="">Automation / live</option>{d.media.map((m:any)=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Repeat<select value={event.recurrence} onChange={e=>setEvent({...event,recurrence:e.target.value})}><option value="none">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><button onClick={()=>send('schedule',event)}>SCHEDULE PROGRAM</button></div>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Music Rotation</h3>{inp(rotation,setRotation,'name','Rotation name')}{inp(rotation,setRotation,'description','Description')}{inp(rotation,setRotation,'weight','Priority weight','number')}<button onClick={()=>send('rotation',rotation)}>CREATE ROTATION</button><div style={{marginTop:15}}>{d.rotations.map((r:any)=><div key={r.id} style={{padding:'9px 0',borderTop:'1px solid #eee'}}><b>{r.name}</b><br/><small>{r.description||'24/7 music rotation'} · weight {r.weight}</small></div>)}</div></div></div></div>
 <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">PROGRAM LOG</div><h2>Upcoming Schedule</h2>{!d.schedule.length?<p>No scheduled programming yet. Music automation fills unscheduled time.</p>:d.schedule.map((s:any)=><div key={s.id} style={{display:'grid',gridTemplateColumns:'180px 1fr auto',gap:15,padding:'14px 0',borderTop:'1px solid #ddd',alignItems:'center'}}><div><b>{new Date(s.starts_at).toLocaleDateString()}</b><br/><small>{new Date(s.starts_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} – {new Date(s.ends_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div><div><b>{s.title}</b><br/><small>{s.event_type.replaceAll('_',' ')} · {s.recurrence}</small></div><button onClick={()=>send('delete_schedule',null,s.id)}>REMOVE</button></div>)}</div>
 <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">MEDIA LIBRARY</div><h2>Music, Commercials & Shows</h2>{d.media.map((m:any)=><div key={m.id} style={{padding:'12px 0',borderTop:'1px solid #ddd'}}><b>{m.title}</b> <small>— {m.kind} {m.artist_or_host?'· '+m.artist_or_host:''}</small></div>)}</div></section>}