'use client';import {useEffect,useState} from 'react';import RadioProgramming from './RadioProgramming';import RadioLiveStudio from './RadioLiveStudio';import RadioImagingMixer from './RadioImagingMixer';
const d={enabled:false,station_name:'Indie Cut Radio',tagline:'Independent music. Culture. Live voices.',stream_url:'',now_playing:'Indie Cut Radio',artwork_url:'',accent:'#d7ff38'};
type Stats={configured:boolean;source:string;listeners_live:number|null;peak_listeners:number|null;total_sessions:number|null;average_listen_minutes:number|null;updated_at:string|null;message?:string};
export default function RadioManager(){const [x,setX]=useState<any>(d),[msg,setMsg]=useState(''),[stats,setStats]=useState<Stats>({configured:false,source:'',listeners_live:null,peak_listeners:null,total_sessions:null,average_listen_minutes:null,updated_at:null});
 const loadStats=()=>fetch('/api/admin/radio/stats',{cache:'no-store'}).then(r=>r.json()).then(setStats).catch(()=>{});
 useEffect(()=>{fetch('/api/admin/radio').then(r=>r.json()).then(j=>setX({...d,...j}));loadStats();const t=setInterval(loadStats,15000);return()=>clearInterval(t)},[]);
 const save=async()=>{setMsg('Saving…');const r=await fetch('/api/admin/radio',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(x)});const j=await r.json();setMsg(r.ok?'Radio settings saved.':j.error||'Save failed.')};
 const field=(k:string,label:string,placeholder='')=><label style={{display:'grid',gap:7,fontWeight:800}}>{label}<input value={x[k]||''} placeholder={placeholder} onChange={e=>setX({...x,[k]:e.target.value})} style={{padding:12,border:'1px solid #ccc',fontSize:14}}/></label>;
 const card=(label:string,value:string|number,sub:string)=><article style={{background:'#111',color:'#fff',padding:20,minHeight:125}}><div style={{fontSize:11,fontWeight:900,letterSpacing:'.1em',color:'#aaa'}}>{label}</div><strong style={{display:'block',fontSize:36,margin:'10px 0 4px'}}>{value}</strong><small style={{color:'#aaa'}}>{sub}</small></article>;
 return <section style={{maxWidth:1050,margin:'0 auto 50px',padding:'0 24px'}}>
  <div className="panel" style={{padding:24}}><div className="kicker">LIVE AUDIENCE</div><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'end',flexWrap:'wrap'}}><div><h2 style={{marginBottom:6}}>Radio Analytics</h2><p style={{margin:0}}>Streaming-server audience data. Refreshes every 15 seconds.</p></div><button onClick={loadStats} style={{padding:'10px 14px',fontWeight:900}}>REFRESH</button></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:20}}>{card('LISTENERS LIVE',stats.listeners_live??'—',stats.configured?'Connected to '+stats.source:'Awaiting provider connection')}{card('PEAK LISTENERS',stats.peak_listeners??'—','Concurrent listener peak')}{card('TOTAL SESSIONS',stats.total_sessions??'—','Provider-reported sessions')}{card('AVG. LISTEN TIME',stats.average_listen_minutes!=null?stats.average_listen_minutes+' min':'—','Average session duration')}</div>
   {!stats.configured&&<div style={{marginTop:14,padding:14,background:'#fff7d6',fontSize:13}}><strong>Listener analytics not connected yet.</strong> {stats.message||'Add the streaming provider analytics connection to show verified live listener counts.'}</div>}
   {stats.updated_at&&<small style={{display:'block',marginTop:10,color:'#777'}}>Last provider update: {new Date(stats.updated_at).toLocaleString()}</small>}
  </div>
  <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">INDIE CUT RADIO</div><h2>Station Control</h2><p>Connect the 24/7 station stream to Indie Cut. The player will follow listeners around the site.</p><label style={{display:'flex',gap:10,alignItems:'center',fontWeight:900,margin:'20px 0'}}><input type="checkbox" checked={x.enabled} onChange={e=>setX({...x,enabled:e.target.checked})}/> Radio player enabled</label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}>{field('station_name','Station name')}{field('tagline','Station tagline')}{field('stream_url','Live stream URL','Paste Live365 / Icecast / Shoutcast stream URL')}{field('now_playing','Now playing / show title')}{field('artwork_url','Station artwork URL')}{field('accent','Player accent color','#d7ff38')}</div><div style={{marginTop:22,display:'flex',gap:12,alignItems:'center'}}><button onClick={save} style={{padding:'12px 18px',fontWeight:900}}>SAVE RADIO SETTINGS</button><span>{msg}</span></div></div>
  <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">PROGRAMMING</div><h2>Broadcast System</h2><p>The station shell is ready for a continuous stream, music rotation, commercials, prerecorded talk shows and live programming. Once the streaming provider gives us the station stream URL, paste it above and enable the player.</p></div>
 <RadioLiveStudio/><RadioImagingMixer/><RadioProgramming/></section>}