'use client';
import {useEffect,useState} from 'react';

export default function RadioProgramming(){
 const [d,setD]=useState<any>({media:[],schedule:[],rotations:[]}),[msg,setMsg]=useState(''),[uploading,setUploading]=useState(false);
 const [media,setMedia]=useState<any>({kind:'music'}),[event,setEvent]=useState<any>({event_type:'show',recurrence:'none',timezone:'America/New_York'}),[rotation,setRotation]=useState<any>({weight:1,song_separation_minutes:180,artist_separation_minutes:60,station_id_every_songs:4,commercial_every_songs:6,shuffle:true,media_ids:[]});
 const load=()=>fetch('/api/admin/radio-programming',{cache:'no-store'}).then(r=>r.json()).then(setD);
 useEffect(()=>{load();try{setEvent((v:any)=>({...v,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York'}))}catch{}},[]);
 const send=async(action:string,payload?:any,id?:string)=>{setMsg('Saving…');const r=await fetch('/api/admin/radio-programming',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload,id})});const j=await r.json();setMsg(r.ok?'Saved.':j.error||'Failed');if(r.ok)load();return r.ok};
 const inp=(obj:any,set:any,k:string,label:string,type='text')=><label style={{display:'grid',gap:6,fontWeight:800}}>{label}<input type={type} value={obj[k]||''} onChange={e=>set({...obj,[k]:e.target.value})} style={{padding:11,border:'1px solid #ccc'}}/></label>;
 async function upload(file?:File){
  if(!file)return;setUploading(true);setMsg('Uploading audio…');
  try{
   const form=new FormData();form.append('file',file);
   const r=await fetch('/api/admin/upload',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.error||'Audio upload failed');
   setMedia((v:any)=>({...v,audio_url:j.publicUrl,title:v.title||file.name.replace(/\.[^.]+$/,'')}));setMsg('Audio uploaded. Add the title/artist, then save it to the library.');
  }catch(e:any){setMsg(e?.message||'Audio upload failed.')}finally{setUploading(false)}
 }
 async function schedule(){if(!event.starts_at||!event.ends_at)return setMsg('Choose a start and end time.');const payload={...event,starts_at:new Date(event.starts_at).toISOString(),ends_at:new Date(event.ends_at).toISOString(),timezone:event.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York'};await send('schedule',payload)}
 return <section style={{maxWidth:1050,margin:'18px auto 50px',padding:'0 24px'}}><div className="panel" style={{padding:24}}><div className="kicker">PROGRAMMING DESK</div><h2>24/7 Broadcast Programming</h2><p>Upload station audio, schedule one-time or recurring shows, and control the automation clock.</p>{msg&&<div className="ic-message">{msg}</div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18,marginTop:20}}>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Add Audio</h3><label>Type<select value={media.kind} onChange={e=>setMedia({...media,kind:e.target.value})}><option value="music">Music</option><option value="commercial">Commercial</option><option value="show">Show / Podcast</option><option value="station_id">Station ID / Promo</option></select></label><label style={{display:'grid',gap:6,fontWeight:800,margin:'10px 0'}}>Upload audio<input type="file" accept="audio/*" disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label>{inp(media,setMedia,'title','Title')}{inp(media,setMedia,'artist_or_host','Artist / Host')}{inp(media,setMedia,'audio_url','Audio URL')}{inp(media,setMedia,'artwork_url','Artwork URL')}<button disabled={uploading} onClick={async()=>{if(await send('media',media))setMedia({kind:'music'})}}>ADD TO LIBRARY</button></div>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Schedule Broadcast</h3><label>Type<select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}><option value="show">Show</option><option value="podcast">Podcast</option><option value="commercial_break">Commercial Break</option><option value="music_block">Music Block</option><option value="live">Live Show</option></select></label>{inp(event,setEvent,'title','Program title')}{inp(event,setEvent,'starts_at','Start date & time','datetime-local')}{inp(event,setEvent,'ends_at','End date & time','datetime-local')}<label>Audio / episode<select value={event.media_id||''} onChange={e=>setEvent({...event,media_id:e.target.value})}><option value="">Automation / live</option>{d.media.map((m:any)=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Repeat<select value={event.recurrence} onChange={e=>setEvent({...event,recurrence:e.target.value})}><option value="none">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><small>Timezone: {event.timezone}</small><button onClick={schedule}>SCHEDULE PROGRAM</button></div>
 <div style={{border:'1px solid #ddd',padding:18}}><h3>Music Rotation</h3>{inp(rotation,setRotation,'name','Rotation name')}{inp(rotation,setRotation,'description','Description')}{inp(rotation,setRotation,'weight','Priority weight','number')}{inp(rotation,setRotation,'song_separation_minutes','Do not repeat same song for (minutes)','number')}{inp(rotation,setRotation,'artist_separation_minutes','Do not repeat same artist for (minutes)','number')}{inp(rotation,setRotation,'station_id_every_songs','Station ID every X songs','number')}{inp(rotation,setRotation,'commercial_every_songs','Commercial break every X songs','number')}<label style={{display:'flex',gap:8,alignItems:'center',margin:'10px 0'}}><input type="checkbox" checked={rotation.shuffle!==false} onChange={e=>setRotation({...rotation,shuffle:e.target.checked})}/> Shuffle eligible songs</label><div style={{fontWeight:800,marginTop:10}}>Songs in this rotation</div><div style={{maxHeight:180,overflow:'auto',border:'1px solid #ddd',padding:8,margin:'6px 0 12px'}}>{d.media.filter((m:any)=>m.kind==='music').map((m:any)=><label key={m.id} style={{display:'flex',gap:8,padding:'5px 0'}}><input type="checkbox" checked={(rotation.media_ids||[]).includes(m.id)} onChange={e=>setRotation({...rotation,media_ids:e.target.checked?[...(rotation.media_ids||[]),m.id]:(rotation.media_ids||[]).filter((id:string)=>id!==m.id)})}/>{m.title} {m.artist_or_host?'— '+m.artist_or_host:''}</label>)}</div><button onClick={()=>send('rotation',rotation)}>CREATE ROTATION</button><div style={{marginTop:15}}>{d.rotations.map((r:any)=><div key={r.id} style={{padding:'9px 0',borderTop:'1px solid #eee',display:'flex',justifyContent:'space-between',gap:10}}><div><b>{r.name}</b><br/><small>{r.description||'24/7 music rotation'} · {r.radio_rotation_items?.length||0} songs · song separation {r.song_separation_minutes}m · artist separation {r.artist_separation_minutes}m · ID every {r.station_id_every_songs} · ads every {r.commercial_every_songs}</small></div><button onClick={()=>send('delete_rotation',null,r.id)}>REMOVE</button></div>)}</div></div></div></div>
 <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">PROGRAM LOG</div><h2>Upcoming Schedule</h2>{!d.schedule.length?<p>No scheduled programming yet. Music automation fills unscheduled time.</p>:d.schedule.map((s:any)=><div key={s.id} style={{display:'grid',gridTemplateColumns:'180px 1fr auto',gap:15,padding:'14px 0',borderTop:'1px solid #ddd',alignItems:'center'}}><div><b>{new Date(s.starts_at).toLocaleDateString()}</b><br/><small>{new Date(s.starts_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} – {new Date(s.ends_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div><div><b>{s.title}</b><br/><small>{s.event_type.replaceAll('_',' ')} · {s.recurrence} · {s.timezone||'America/New_York'}</small></div><button onClick={()=>send('delete_schedule',null,s.id)}>REMOVE</button></div>)}</div>
 <div className="panel" style={{padding:24,marginTop:18}}><div className="kicker">MEDIA LIBRARY</div><h2>Music, Commercials & Shows</h2>{d.media.map((m:any)=><div key={m.id} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'12px 0',borderTop:'1px solid #ddd'}}><div><b>{m.title}</b> <small>— {m.kind} {m.artist_or_host?'· '+m.artist_or_host:''}</small></div><button onClick={()=>send('delete_media',null,m.id)}>REMOVE</button></div>)}</div></section>
}