'use client';

import {useEffect,useState} from 'react';
import {compressImage} from '../../lib/compressImage';

type AnyRow=Record<string,any>;
const defaults:Record<string,AnyRow>={
 articles:{headline:'',subheadline:'',category:'culture',subject_name:'',body:'',featured_media_url:'',author_name:'Indie Cut Editorial',sources:'',verification_status:'verified',status:'draft'},
 artists:{name:'',kind:'artist',bio:'',image_url:'',website_url:'',instagram_url:'',featured:false},
 music:{title:'',media_type:'music',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'video-media':{title:'',media_type:'video',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'media-library':{title:'',media_type:'image',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 advertising:{advertiser:'',title:'',creative_url:'',creative_media_type:'',destination_url:'',placement:'right-rail',start_date:'',end_date:'',active:true},
 authors:{name:'',role:'Writer',bio:'',headshot_url:'',social_url:'',active:true},
 subscribers:{email:'',source:'admin',status:'subscribed'},
 homepage:{hero_eyebrow:'ENTERTAINMENT · CULTURE · INDEPENDENT VOICES',hero_headline:'The stories moving film, television, music and culture.',hero_subheadline:'Verified entertainment news, emerging creators and independent voices.',hero_media_url:'',accent_color:'#d71920'},
 settings:{publication_name:'Indie Cut',tagline:'Entertainment · Culture · Independent Voices',instagram:'',youtube:'',tiktok:'',footer_copy:'Indie Cut'}
};

export default function SectionManager({section}:{section:string}){
 const [rows,setRows]=useState<AnyRow[]>([]);const [form,setForm]=useState<AnyRow>(defaults[section]||{});const [editingId,setEditingId]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [topic,setTopic]=useState('Find the strongest trending verified entertainment story involving Black culture, film, television, music, celebrities or independent creators.');const [agentCount,setAgentCount]=useState(3);const [agentResult,setAgentResult]=useState<any>(null);const [previews,setPreviews]=useState<AnyRow>({});
 useEffect(()=>{setEditingId(null);setForm(defaults[section]||{});setPreviews({});load()},[section]);
 async function load(){if(section==='content-agent'||section==='analytics')return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}`);const text=await r.text();let j:any={};try{j=text?JSON.parse(text):{}}catch{j={error:text||'Unable to load section'}}if(r.ok){setRows(j.rows||[]);if((section==='homepage'||section==='settings')&&j.rows?.[0])setForm({...defaults[section],...j.rows[0]})}else setMessage(j.error||'Unable to load section')}
 function articleToForm(r:AnyRow){return {...r,sources:Array.isArray(r.sources)?r.sources.join('\n'):String(r.sources||'')}}
 async function save(){setBusy(true);setMessage('');try{let payload={...form};if(section==='articles')payload.sources=String(form.sources||'').split('\n').map((x:string)=>x.trim()).filter(Boolean);if(section==='advertising')payload={advertiser:String(form.advertiser||''),title:String(form.title||''),creative_url:String(form.creative_url||''),creative_media_type:String(form.creative_media_type||previews.creative_url?.type||''),destination_url:String(form.destination_url||''),placement:String(form.placement||'right-rail'),start_date:String(form.start_date||''),end_date:String(form.end_date||''),active:form.active!==false};const method=editingId?'PUT':'POST';const body=editingId?{section,id:editingId,data:payload}:{section,data:payload};const r=await fetch('/api/admin/data',{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});const text=await r.text();let j:any={};try{j=text?JSON.parse(text):{}}catch{j={error:text||`Save failed (${r.status})`}}if(!r.ok)throw new Error(j.error||`Save failed (${r.status})`);setMessage(section==='advertising'?'Advertisement saved and activated.':editingId?'Updated.':'Saved.');setEditingId(null);setPreviews({});if(section!=='homepage'&&section!=='settings')setForm(defaults[section]||{});await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function publish(r:AnyRow){
  const needsVerification=String(r.verification_status||'pending')!=='verified';
  if(needsVerification){
   const ok=confirm('This article is still marked PENDING VERIFICATION. Publish it as verified now? Only continue if you reviewed the flagged facts and sources.');
   if(!ok){setMessage('Article left as pending. Review the verification notes before publishing.');return}
  }
  setBusy(true);setMessage('');
  try{
   const data={...r,status:'published',verification_status:'verified'};
   const res=await fetch('/api/admin/data',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({section:'articles',id:r.id,data})});
   const j=await res.json();if(!res.ok)throw new Error(j.error||'Publish failed');
   setMessage(needsVerification?'Verified and published to Indie Cut.':'Published to Indie Cut.');
   await load();
  }catch(e:any){setMessage(e.message)}finally{setBusy(false)}
 }
 async function verifyPublished(r:AnyRow){
  const ok=confirm('This article is already marked published but is hidden because verification is still pending. Mark it VERIFIED and make it live now?');
  if(!ok)return;
  setBusy(true);setMessage('');
  try{
   const data={...r,status:'published',verification_status:'verified'};
   const res=await fetch('/api/admin/data',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({section:'articles',id:r.id,data})});
   const j=await res.json();if(!res.ok)throw new Error(j.error||'Verification update failed');
   setMessage('Article verified and made live.');
   await load();
  }catch(e:any){setMessage(e.message)}finally{setBusy(false)}
 }
 async function remove(id:string){if(!confirm('Delete this item?'))return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}&id=${encodeURIComponent(id)}`,{method:'DELETE'});const j=await r.json();if(!r.ok){setMessage(j.error||'Delete failed');return}await load()}
 async function upload(field:string,file?:File){if(!file)return;setBusy(true);setMessage('Preparing media…');const localUrl=URL.createObjectURL(file);setPreviews((p:AnyRow)=>({...p,[field]:{url:localUrl,type:file.type}}));try{const prepared=await compressImage(file);const fd=new FormData();fd.append('file',prepared);setMessage(prepared.size!==file.size?'Image optimized. Uploading…':'Uploading…');const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const text=await r.text();let j:any={};try{j=text?JSON.parse(text):{}}catch{j={error:text||`Upload failed (${r.status})`}}if(!r.ok)throw new Error(j.error||'Upload failed');const mediaType=String(prepared.type||file.type||'');setForm((f:AnyRow)=>field==='creative_url'?({...f,[field]:j.publicUrl,creative_media_type:mediaType}):({...f,[field]:j.publicUrl}));setPreviews((p:AnyRow)=>({...p,[field]:{url:j.publicUrl,type:mediaType}}));setMessage('Upload complete — preview shown below. Click SAVE to activate this ad.');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function runAgent(){setBusy(true);setAgentResult(null);setMessage('');try{const r=await fetch('/api/content-agent/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic,count:agentCount})});const j=await r.json();setAgentResult(j);if(!r.ok)setMessage(j.error||'Agent failed')}finally{setBusy(false)}}
 if(section==='content-agent')return <section className="ic-module-panel"><h2>Verified Entertainment Research</h2><p>Ask for current stories. Verified stories are automatically saved to <strong>Articles → Drafts</strong> for review. Choose how many different articles you want created in one run. Nothing is published automatically.</p><label>Research assignment</label><textarea rows={6} value={topic} onChange={e=>setTopic(e.target.value)}/><label>How many articles?<input type="number" min="1" max="12" value={agentCount} onChange={e=>setAgentCount(Math.min(12,Math.max(1,Number(e.target.value)||1)))}/><small style={{display:'block',marginTop:6,color:'#666'}}>Create 1–12 different verified article drafts per run.</small></label><button onClick={runAgent} disabled={busy}>{busy?`RESEARCHING ${agentCount} ARTICLE${agentCount===1?'':'S'}…`:`CREATE ${agentCount} VERIFIED ARTICLE${agentCount===1?'':'S'}`}</button>{agentResult&&<div className="ic-agent-results"><h3>Research complete</h3><p>{(agentResult.created||[]).length} of {agentResult.requested||agentCount} requested article(s) were created as drafts.</p>{(agentResult.created||[]).length===0&&<p>No drafts were created.</p>}{(agentResult.created||[]).map((r:any,i:number)=><article className="ic-agent-card" key={r.slug||i}>{r.image&&<img src={r.image} alt="Story image candidate" className="ic-agent-thumb"/>}<div><span className="ic-status-pill">{String(r.verification_status||'verified').toUpperCase()} DRAFT</span><h3>{r.headline}</h3><p>{r.category} · {r.sources} source(s) · {r.image?'image found':'no image found'}</p></div><a className="ic-link-button" href="/admin/articles">REVIEW IN ARTICLES →</a></article>)}{(agentResult.rejected||[]).length>0&&<details><summary>{agentResult.rejected.length} rejected result(s)</summary>{agentResult.rejected.map((r:any,i:number)=><p key={i}><strong>{r.headline}</strong>: {r.reason}</p>)}</details>}</div>}</section>;
 if(section==='analytics')return <section className="ic-module-panel"><h2>Analytics</h2><p>Publication analytics will populate as Indie Cut receives traffic and content activity.</p></section>;
 const renderPreview=(field:string)=>{const p=previews[field];const src=p?.url||form[field];if(!src)return null;const type=String(p?.type||form.creative_media_type||'');return <div className="ic-current-media"><strong>Media preview</strong>{type.startsWith('video/')?<video src={src} controls playsInline/>:<img src={src} alt="Media preview"/>}</div>};
 const uploadControl=(label:string,field:string,accept:string)=><div><label>{label}</label><input type="file" accept={accept} onChange={e=>upload(field,e.target.files?.[0])}/>{renderPreview(field)}</div>;
 const text=(label:string,key:string,type='text')=><label>{label}<input type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const area=(label:string,key:string,rows=5)=><label>{label}<textarea rows={rows} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 let fields:any=null;
 if(section==='articles')fields=<>{text('Headline','headline')}{text('Subheadline','subheadline')}<div className="ic-two"><label>Category<select value={form.category||'culture'} onChange={e=>setForm({...form,category:e.target.value})}><option>movies</option><option>tv</option><option>music</option><option>culture</option><option>independent</option><option>celebrity</option></select></label>{text('Subject / Person','subject_name')}</div>{uploadControl('Upload or replace featured image/video','featured_media_url','image/*,video/*')}{area('Article body','body',12)}{area('Source URLs — one per line','sources',4)}<div className="ic-two"><label>Verification<select value={form.verification_status||'pending'} onChange={e=>setForm({...form,verification_status:e.target.value})}><option value="pending">Pending verification</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label><label>Status<select value={form.status||'draft'} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div>{text('Author / Byline','author_name')}</>;
 if(section==='artists')fields=<>{text('Name','name')}<label>Type<select value={form.kind||'artist'} onChange={e=>setForm({...form,kind:e.target.value})}><option value="actor">Actor</option><option value="musician">Musician</option><option value="filmmaker">Filmmaker</option><option value="creator">Creator</option><option value="artist">Artist</option></select></label>{uploadControl('Upload headshot / profile image','image_url','image/*')}{area('Bio','bio',7)}{text('Website','website_url')}{text('Instagram','instagram_url')}</>;
 if(section==='music')fields=<>{text('Title','title')}{text('Artist','artist_name')}{uploadControl('Upload audio or music video','media_url','audio/*,video/*')}{uploadControl('Upload cover artwork','cover_url','image/*')}{area('Description','description',5)}</>;
 if(section==='video-media'||section==='media-library')fields=<>{text('Title','title')}{text('Artist / Person','artist_name')}{uploadControl(section==='video-media'?'Upload image or video':'Upload media file','media_url','image/*,video/*,audio/*')}{uploadControl('Upload thumbnail / cover','cover_url','image/*')}{area('Caption / Description','description',4)}</>;
 if(section==='advertising')fields=<>{text('Advertiser','advertiser')}{text('Campaign / Ad title','title')}{uploadControl('Upload ad image or video','creative_url','image/*,video/*')}{text('Destination URL','destination_url','url')}<label>Placement<select value={form.placement||'right-rail'} onChange={e=>setForm({...form,placement:e.target.value})}><option value="right-rail">Right rail</option><option value="homepage">Homepage</option><option value="article-inline">Article inline</option><option value="article-top">Article top</option><option value="sponsored-feature">Sponsored feature</option></select></label><div className="ic-two">{text('Start date','start_date','date')}{text('End date','end_date','date')}</div><label className="ic-check"><input type="checkbox" checked={form.active!==false} onChange={e=>setForm({...form,active:e.target.checked})}/> Active campaign</label></>;
 if(section==='authors')fields=<>{text('Name','name')}{text('Role','role')}{uploadControl('Upload headshot','headshot_url','image/*')}{area('Bio','bio',6)}{text('Social / Website','social_url')}</>;
 if(section==='subscribers')fields=<>{text('Email','email','email')}{text('Source','source')}<label>Status<select value={form.status||'subscribed'} onChange={e=>setForm({...form,status:e.target.value})}><option>subscribed</option><option>unsubscribed</option></select></label></>;
 if(section==='homepage')fields=<>{text('Hero eyebrow','hero_eyebrow')}{text('Hero headline','hero_headline')}{area('Hero subheadline','hero_subheadline',3)}<label>Trending banner / accent color<input type="color" value={form.accent_color||'#d71920'} onChange={e=>setForm({...form,accent_color:e.target.value})}/><small style={{display:'block',marginTop:6,color:'#666'}}>Controls the Trending banner and red editorial accents on the homepage.</small></label>{uploadControl('Upload homepage hero image or video','hero_media_url','image/*,video/*')}</>;
 if(section==='settings')fields=<>{text('Publication name','publication_name')}{text('Tagline','tagline')}{text('Instagram','instagram')}{text('YouTube','youtube')}{text('TikTok','tiktok')}{text('Footer copy','footer_copy')}</>;
 return <><section className="ic-module-panel"><h2>{section==='articles'?(editingId?'Edit Article':'Create Article'):section==='advertising'?'Create Advertisement':section==='artists'?'Add Artist or Person':section==='music'?'Add Music':section==='video-media'?'Upload Video or Media':section==='authors'?'Add Author or Editor':section==='subscribers'?'Add Subscriber':section==='homepage'?'Homepage Settings':section==='settings'?'Site Settings':'Add Media'}</h2>{fields}<div className="ic-actions"><button onClick={save} disabled={busy}>{busy?'SAVING…':editingId?'UPDATE ARTICLE':'SAVE'}</button>{editingId&&<button className="ic-secondary" onClick={()=>{setEditingId(null);setForm(defaults.articles);setPreviews({})}}>CANCEL EDIT</button>}</div>{message&&<div className="ic-message">{message}</div>}</section>{rows.length>0&&section!=='homepage'&&section!=='settings'&&<section className="ic-module-panel"><h2>{section==='articles'?'Articles':'Existing'}</h2><div className="ic-admin-list">{rows.map((r:any)=>{const isPending=section==='articles'&&String(r.verification_status||'pending')!=='verified';return <article key={r.id||r._id}>{section==='articles'&&r.featured_media_url&&<img src={r.featured_media_url} alt="" className="ic-list-thumb"/>}<div><strong>{r.headline||r.name||r.title||r.advertiser||r.email||'Item'}</strong><small>{section==='articles'?`${String(r.status||'draft').toUpperCase()} · ${r.category||''} · ${String(r.verification_status||'pending').toUpperCase()}`:(r.category||r.kind||r.media_type||r.placement||r.status||'')}</small></div><div className="ic-row-actions">{section==='articles'&&<button onClick={()=>{setEditingId(r.id);setForm(articleToForm(r));setPreviews({});window.scrollTo({top:0,behavior:'smooth'})}}>Review / Edit</button>}{section==='articles'&&r.status!=='published'&&<button onClick={()=>publish(r)}>{isPending?'VERIFY & PUBLISH':'PUBLISH'}</button>}{section==='articles'&&r.status==='published'&&isPending&&<button onClick={()=>verifyPublished(r)}>VERIFY & MAKE LIVE</button>}<button onClick={()=>remove(r.id||r._id)}>Delete</button></div></article>})}</div></section>}</>;
}