'use client';

import {useEffect,useState} from 'react';
import {createClient} from '../../lib/supabase/browser';

type AnyRow=Record<string,any>;
const defaults:Record<string,AnyRow>={
 articles:{headline:'',subheadline:'',category:'culture',subject_name:'',body:'',featured_media_url:'',author_name:'Indie Cut Editorial',sources:'',verification_status:'verified',status:'draft'},
 artists:{name:'',kind:'artist',bio:'',image_url:'',website_url:'',instagram_url:'',featured:false},
 music:{title:'',media_type:'music',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'video-media':{title:'',media_type:'video',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'media-library':{title:'',media_type:'image',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 advertising:{advertiser:'',title:'',creative_url:'',destination_url:'',placement:'right-rail',start_date:'',end_date:'',active:true},
 authors:{name:'',role:'Writer',bio:'',headshot_url:'',social_url:'',active:true},
 subscribers:{email:'',source:'admin',status:'subscribed'},
 homepage:{hero_eyebrow:'ENTERTAINMENT · CULTURE · INDEPENDENT VOICES',hero_headline:'The stories moving film, television, music and culture.',hero_subheadline:'Verified entertainment news, emerging creators and independent voices.',hero_media_url:''},
 settings:{publication_name:'Indie Cut',tagline:'Entertainment · Culture · Independent Voices',instagram:'',youtube:'',tiktok:'',footer_copy:'Indie Cut'}
};

export default function SectionManager({section}:{section:string}){
 const [rows,setRows]=useState<AnyRow[]>([]);const [form,setForm]=useState<AnyRow>(defaults[section]||{});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [topic,setTopic]=useState('Find the strongest trending verified entertainment story involving Black culture, film, television, music, celebrities or independent creators.');const [agentResult,setAgentResult]=useState<any>(null);
 useEffect(()=>{load()},[section]);
 async function load(){if(section==='content-agent'||section==='analytics')return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}`);const j=await r.json();if(r.ok){setRows(j.rows||[]);if((section==='homepage'||section==='settings')&&j.rows?.[0])setForm({...defaults[section],...j.rows[0]})}else setMessage(j.error||'Unable to load section')}
 async function save(){setBusy(true);setMessage('');try{const payload={...form};if(section==='articles')payload.sources=String(form.sources||'').split('\n').map((x:string)=>x.trim()).filter(Boolean);const r=await fetch('/api/admin/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({section,data:payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');setMessage('Saved.');if(section!=='homepage'&&section!=='settings')setForm(defaults[section]||{});await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this item?'))return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}&id=${encodeURIComponent(id)}`,{method:'DELETE'});const j=await r.json();if(!r.ok){setMessage(j.error||'Delete failed');return}await load()}
 async function upload(field:string,file?:File){if(!file)return;setBusy(true);setMessage('Uploading…');try{const r=await fetch('/api/admin/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,type:file.type})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare upload');const supabase=createClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,file,{contentType:file.type});if(error)throw error;setForm((f:AnyRow)=>({...f,[field]:j.publicUrl}));setMessage('Upload complete.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function runAgent(){setBusy(true);setAgentResult(null);try{const r=await fetch('/api/content-agent/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic,count:3})});const j=await r.json();setAgentResult(j);if(!r.ok)setMessage(j.error||'Agent failed')}finally{setBusy(false)}}
 if(section==='content-agent')return <section className="ic-module-panel"><h2>Verified Entertainment Research</h2><p>Ask for a current story. The agent searches the web, rejects rumor-based claims, requires credible sourcing, and saves verified results as drafts.</p><label>Research assignment</label><textarea rows={6} value={topic} onChange={e=>setTopic(e.target.value)}/><button onClick={runAgent} disabled={busy}>{busy?'RESEARCHING…':'RUN VERIFIED RESEARCH'}</button>{agentResult&&<pre className="ic-result">{JSON.stringify(agentResult,null,2)}</pre>}</section>;
 if(section==='analytics')return <section className="ic-module-panel"><h2>Analytics</h2><p>Publication analytics will populate as Indie Cut receives traffic and content activity.</p></section>;
 const uploadControl=(label:string,field:string,accept:string)=><div><label>{label}</label><input type="file" accept={accept} onChange={e=>upload(field,e.target.files?.[0])}/>{form[field]&&<div className="ic-upload-preview">Uploaded ✓</div>}</div>;
 const text=(label:string,key:string,type='text')=><label>{label}<input type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const area=(label:string,key:string,rows=5)=><label>{label}<textarea rows={rows} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 let fields:any=null;
 if(section==='articles')fields=<>{text('Headline','headline')}{text('Subheadline','subheadline')}<div className="ic-two"><label>Category<select value={form.category||'culture'} onChange={e=>setForm({...form,category:e.target.value})}><option>movies</option><option>tv</option><option>music</option><option>culture</option><option>independent</option><option>celebrity</option></select></label>{text('Subject / Person','subject_name')}</div>{uploadControl('Upload featured image or video','featured_media_url','image/*,video/*')}{area('Article body','body',12)}{area('Source URLs — one per line','sources',4)}<div className="ic-two"><label>Status<select value={form.status||'draft'} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>{text('Author / Byline','author_name')}</div></>;
 if(section==='artists')fields=<>{text('Name','name')}<label>Type<select value={form.kind||'artist'} onChange={e=>setForm({...form,kind:e.target.value})}><option value="actor">Actor</option><option value="musician">Musician</option><option value="filmmaker">Filmmaker</option><option value="creator">Creator</option><option value="artist">Artist</option></select></label>{uploadControl('Upload headshot / profile image','image_url','image/*')}{area('Bio','bio',7)}{text('Website','website_url')}{text('Instagram','instagram_url')}</>;
 if(section==='music')fields=<>{text('Title','title')}{text('Artist','artist_name')}{uploadControl('Upload audio or music video','media_url','audio/*,video/*')}{uploadControl('Upload cover artwork','cover_url','image/*')}{area('Description','description',5)}</>;
 if(section==='video-media'||section==='media-library')fields=<>{text('Title','title')}{text('Artist / Person','artist_name')}{uploadControl(section==='video-media'?'Upload image or video':'Upload media file','media_url','image/*,video/*,audio/*')}{uploadControl('Upload thumbnail / cover','cover_url','image/*')}{area('Caption / Description','description',4)}</>;
 if(section==='advertising')fields=<>{text('Advertiser','advertiser')}{text('Campaign / Ad title','title')}{uploadControl('Upload ad image or video','creative_url','image/*,video/*')}{text('Destination URL','destination_url','url')}<label>Placement<select value={form.placement||'right-rail'} onChange={e=>setForm({...form,placement:e.target.value})}><option value="right-rail">Right rail</option><option value="homepage">Homepage</option><option value="article-inline">Article inline</option><option value="article-top">Article top</option><option value="sponsored-feature">Sponsored feature</option></select></label><div className="ic-two">{text('Start date','start_date','date')}{text('End date','end_date','date')}</div><label className="ic-check"><input type="checkbox" checked={form.active!==false} onChange={e=>setForm({...form,active:e.target.checked})}/> Active campaign</label></>;
 if(section==='authors')fields=<>{text('Name','name')}{text('Role','role')}{uploadControl('Upload headshot','headshot_url','image/*')}{area('Bio','bio',6)}{text('Social / Website','social_url')}</>;
 if(section==='subscribers')fields=<>{text('Email','email','email')}{text('Source','source')}<label>Status<select value={form.status||'subscribed'} onChange={e=>setForm({...form,status:e.target.value})}><option>subscribed</option><option>unsubscribed</option></select></label></>;
 if(section==='homepage')fields=<>{text('Hero eyebrow','hero_eyebrow')}{text('Hero headline','hero_headline')}{area('Hero subheadline','hero_subheadline',3)}{uploadControl('Upload homepage hero image or video','hero_media_url','image/*,video/*')}</>;
 if(section==='settings')fields=<>{text('Publication name','publication_name')}{text('Tagline','tagline')}{text('Instagram','instagram')}{text('YouTube','youtube')}{text('TikTok','tiktok')}{text('Footer copy','footer_copy')}</>;
 return <><section className="ic-module-panel"><h2>{section==='articles'?'Create Article':section==='advertising'?'Create Advertisement':section==='artists'?'Add Artist or Person':section==='music'?'Add Music':section==='video-media'?'Upload Video or Media':section==='authors'?'Add Author or Editor':section==='subscribers'?'Add Subscriber':section==='homepage'?'Homepage Settings':section==='settings'?'Site Settings':'Add Media'}</h2>{fields}<button onClick={save} disabled={busy}>{busy?'SAVING…':'SAVE'}</button>{message&&<div className="ic-message">{message}</div>}</section>{rows.length>0&&section!=='homepage'&&section!=='settings'&&<section className="ic-module-panel"><h2>Existing</h2><div className="ic-admin-list">{rows.map((r:any)=><article key={r.id||r._id}><div><strong>{r.headline||r.name||r.title||r.advertiser||r.email||'Item'}</strong><small>{r.category||r.kind||r.media_type||r.placement||r.status||''}</small></div><button onClick={()=>remove(r.id||r._id)}>Delete</button></article>)}</div></section>}</>;
}
