'use client';

import {useEffect,useState} from 'react';
import {createClient} from '../../lib/supabase/browser';
import {compressImage} from '../../lib/compressImage';

type AnyRow=Record<string,any>;
const defaults:Record<string,AnyRow>={
 articles:{headline:'',subheadline:'',category:'culture',subject_name:'',body:'',featured_media_url:'',author_name:'Indie Cut Editorial',sources:'',verification_status:'verified',status:'draft'},
 artists:{name:'',kind:'artist',bio:'',image_url:'',website_url:'',instagram_url:'',featured:false},
 music:{title:'',media_type:'music',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'video-media':{title:'',media_type:'video',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 'media-library':{title:'',media_type:'image',artist_name:'',description:'',media_url:'',cover_url:'',featured:false},
 advertising:{advertiser:'',title:'',creative_url:'',destination_url:'',placement:'right-rail',start_date:'',end_date:'',active:true},
 authors:{name:'',role:'Writer',bio:'',headshot_url:'',social_url:'',active:true},
 subscribers:{email:'',source:'admin',status:'subscribed'},
 homepage:{hero_eyebrow:'ENTERTAINMENT · CULTURE · INDEPENDENT VOICES',hero_headline:'The stories moving film, television, music and culture.',hero_subheadline:'Verified entertainment news, emerging creators and independent voices.',hero_media_url:''},
 settings:{publication_name:'Indie Cut',tagline:'Entertainment · Culture · Independent Voices',instagram:'',youtube:'',tiktok:'',footer_copy:'Indie Cut'}
};

export default function SectionManager({section}:{section:string}){
 const [rows,setRows]=useState<AnyRow[]>([]);const [form,setForm]=useState<AnyRow>(defaults[section]||{});const [editingId,setEditingId]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [topic,setTopic]=useState('Find the strongest trending verified entertainment story involving Black culture, film, television, music, celebrities or independent creators.');const [agentResult,setAgentResult]=useState<any>(null);
 useEffect(()=>{setEditingId(null);setForm(defaults[section]||{});load()},[section]);
 async function load(){if(section==='content-agent'||section==='analytics')return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}`);const j=await r.json();if(r.ok){setRows(j.rows||[]);if((section==='homepage'||section==='settings')&&j.rows?.[0])setForm({...defaults[section],...j.rows[0]})}else setMessage(j.error||'Unable to load section')}
 function articleToForm(r:AnyRow){return {...r,sources:Array.isArray(r.sources)?r.sources.join('\n'):String(r.sources||'')}}
 async function save(){setBusy(true);setMessage('');try{const payload={...form};if(section==='articles')payload.sources=String(form.sources||'').split('\n').map((x:string)=>x.trim()).filter(Boolean);const method=editingId?'PUT':'POST';const body=editingId?{section,id:editingId,data:payload}:{section,data:payload};const r=await fetch('/api/admin/data',{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');setMessage(editingId?'Updated.':'Saved.');setEditingId(null);if(section!=='homepage'&&section!=='settings')setForm(defaults[section]||{});await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function publish(r:AnyRow){setBusy(true);setMessage('');try{const data={...r,status:'published'};const res=await fetch('/api/admin/data',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({section:'articles',id:r.id,data})});const j=await res.json();if(!res.ok)throw new Error(j.error||'Publish failed');setMessage('Published to Indie Cut.');await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this item?'))return;const r=await fetch(`/api/admin/data?section=${encodeURIComponent(section)}&id=${encodeURIComponent(id)}`,{method:'DELETE'});const j=await r.json();if(!r.ok){setMessage(j.error||'Delete failed');return}await load()}
 async function upload(field:string,file?:File){if(!file)return;setBusy(true);setMessage('Preparing media…');try{const prepared=await compressImage(file);if(prepared.size!==file.size)setMessage('Image optimized for upload…');const r=await fetch('/api/admin/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:prepared.name,type:prepared.type,size:prepared.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare upload');const supabase=createClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,prepared,{contentType:prepared.type});if(error)throw error;setForm((f:AnyRow)=>({...f,[field]:j.publicUrl}));setMessage('Upload complete.');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function runAgent(){setBusy(true);setAgentResult(null);setMessage('');try{const r=await fetch('/api/content-agent/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic,count:3})});const j=await r.json();setAgentResult(j);if(!r.ok)setMessage(j.error||'Agent failed')}finally{setBusy(false)}}
 if(section==='content-agent')return <section className="ic-module-panel"><h2>Verified Entertainment Research</h2><p>Ask for a current story. Verified stories are automatically saved to <strong>Articles → Drafts</strong> for review. The agent also tries to pull a trustworthy editorial image from an official or credible source. Nothing is published automatically.</p><label>Research assignment</label><textarea rows={6} value={topic} onChange={e=>setTopic(e.target.value)}/><button onClick={runAgent} disabled={busy}>{busy?'RESEARCHING…':'RUN VERIFIED RESEARCH'}</button>{agentResult&&<div className="ic-agent-results"><h3>Research complete</h3>{(agentResult.created||[]).length===0&&<p>No verified drafts were created.</p>}{(agentResult.created||[]).map((r:any,i:number)=><article className="ic-agent-card" key={r.slug||i}>{r.image&&<img src={r.image} alt="Story image candidate" className="ic-agent-thumb"/>}<div><span className="ic-status-pill">VERIFIED DRAFT</span><h3>{r.headline}</h3><p>{r.category} · {r.sources} credible sources · {r.image?'image found':'no image found'}</p></div><a className="ic-link-button" href="/admin/articles">REVIEW IN ARTICLES →</a></article>)}{(agentResult.rejected||[]).length>0&&<details><summary>{agentResult.rejected.length} rejected result(s)</summary>{agentResult.rejected.map((r:any,i:number)=><p key={i}><strong>{r.headline}</strong>: {r.reason}</p>)}</details>}</div>}</section>;
 if(section==='analytics')return <section className="ic-module-panel"><h2>Analytics</h2><p>Publication analytics will populate as Indie Cut receives traffic and content activity.</p></section>;
 const uploadControl=(label:string,field:string,accept:string)=><div><label>{label}</label><input type="file" accept={accept} onChange={e=>upload(field,e.target.files?.[0])}/>{form[field]&&<div className="ic-upload-preview">Media attached ✓</div>}</div>;
 const text=(label:string,key:string,type='text')=><label>{label}<input type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const area=(label:string,key:string,rows=5)=><label>{label}<textarea rows={rows} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 let fields:any=null;
 if(section==='articles')fields=<>{text('Headline','headline')}{text('Subheadline','subheadline')}<div className="ic-two"><label>Category<select value={form.category||'culture'} onChange={e=>setForm({...form,category:e.target.value})}><option>movies</option><option>tv</option><option>music</option><option>culture</option><option>independent</option><option>celebrity</option></select></label>{text('Subject / Person','subject_name')}</div>{form.featured_media_url&&<div className="ic-current-media"><strong>Current featured media</strong><img src={form.featured_media_url} alt="Current featured media"/></div>}{uploadControl('Upload or replace featured image/video','featured_media_url','image/*,video/*')}{area('Article body','body',12)}{area('Source URLs — one per line','sources',4)}<div className="ic-two"><label>Status<select value={form.status||'draft'} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>{text('Author / Byline','author_name')}</div></>;
 if(section==='artists')fields=<>{text('Name','name')}<label>Type<select value={form.kind||'artist'} onChange={e=>setForm({...form,kind:e.target.value})}><option value="actor">Actor</option><option value="musician">Musician</option><option value="filmmaker">Filmmaker</option><option value="creator">Creator</option><option value="artist">Artist</option></select></label>{uploadControl('Upload headshot / profile image','image_url','image/*')}{area('Bio','bio',7)}{text('Website','website_url')}{text('Instagram','instagram_url')}</>;
 if(section==='music')fields=<>{text('Title','title')}{text('Artist','artist_name')}{uploadControl('Upload audio or music video','media_url','audio/*,video/*')}{uploadControl('Upload cover artwork','cover_url','image/*')}{area('Description','description',5)}</>;
 if(section==='video-media'||section==='media-library')fields=<>{text('Title','title')}{text('Artist / Person','artist_name')}{uploadControl(section==='video-media'?'Upload image or video':'Upload media file','media_url','image/*,video/*,audio/*')}{uploadControl('Upload thumbnail / cover','cover_url','image/*')}{area('Caption / Description','description',4)}</>;
 if(section==='advertising')fields=<>{text('Advertiser','advertiser')}{text('Campaign / Ad title','title')}{uploadControl('Upload ad image or video','creative_url','image/*,video/*')}{text('Destination URL','destination_url','url')}<label>Placement<select value={form.placement||'right-rail'} onChange={e=>setForm({...form,placement:e.target.value})}><option value="right-rail">Right rail</option><option value="homepage">Homepage</option><option value="article-inline">Article inline</option><option value="article-top">Article top</option><option value="sponsored-feature">Sponsored feature</option></select></label><div className="ic-two">{text('Start date','start_date','date')}{text('End date','end_date','date')}</div><label className="ic-check"><input type="checkbox" checked={form.active!==false} onChange={e=>setForm({...form,active:e.target.checked})}/> Active campaign</label></>;
 if(section==='authors')fields=<>{text('Name','name')}{text('Role','role')}{uploadControl('Upload headshot','headshot_url','image/*')}{area('Bio','bio',6)}{text('Social / Website','social_url')}</>;
 if(section==='subscribers')fields=<>{text('Email','email','email')}{text('Source','source')}<label>Status<select value={form.status||'subscribed'} onChange={e=>setForm({...form,status:e.target.value})}><option>subscribed</option><option>unsubscribed</option></select></label></>;
 if(section==='homepage')fields=<>{text('Hero eyebrow','hero_eyebrow')}{text('Hero headline','hero_headline')}{area('Hero subheadline','hero_subheadline',3)}{uploadControl('Upload homepage hero image or video','hero_media_url','image/*,video/*')}</>;
 if(section==='settings')fields=<>{text('Publication name','publication_name')}{text('Tagline','tagline')}{text('Instagram','instagram')}{text('YouTube','youtube')}{text('TikTok','tiktok')}{text('Footer copy','footer_copy')}</>;
 return <><section className="ic-module-panel"><h2>{section==='articles'?(editingId?'Edit Article':'Create Article'):section==='advertising'?'Create Advertisement':section==='artists'?'Add Artist or Person':section==='music'?'Add Music':section==='video-media'?'Upload Video or Media':section==='authors'?'Add Author or Editor':section==='subscribers'?'Add Subscriber':section==='homepage'?'Homepage Settings':section==='settings'?'Site Settings':'Add Media'}</h2>{fields}<div className="ic-actions"><button onClick={save} disabled={busy}>{busy?'SAVING…':editingId?'UPDATE ARTICLE':'SAVE'}</button>{editingId&&<button className="ic-secondary" onClick={()=>{setEditingId(null);setForm(defaults.articles)}}>CANCEL EDIT</button>}</div>{message&&<div className="ic-message">{message}</div>}</section>{rows.length>0&&section!=='homepage'&&section!=='settings'&&<section className="ic-module-panel"><h2>{section==='articles'?'Articles':'Existing'}</h2><div className="ic-admin-list">{rows.map((r:any)=><article key={r.id||r._id}>{section==='articles'&&r.featured_media_url&&<img src={r.featured_media_url} alt="" className="ic-list-thumb"/>}<div><strong>{r.headline||r.name||r.title||r.advertiser||r.email||'Item'}</strong><small>{section==='articles'?`${String(r.status||'draft').toUpperCase()} · ${r.category||''}`:(r.category||r.kind||r.media_type||r.placement||r.status||'')}</small></div><div className="ic-row-actions">{section==='articles'&&<button onClick={()=>{setEditingId(r.id);setForm(articleToForm(r));window.scrollTo({top:0,behavior:'smooth'})}}>Review / Edit</button>}{section==='articles'&&r.status!=='published'&&<button onClick={()=>publish(r)}>Publish</button>}<button onClick={()=>remove(r.id||r._id)}>Delete</button></div></article>)}</div></section>}</>;
}
