'use client';
import {useEffect,useState} from 'react';
import {createClient as createBrowserClient} from '../../lib/supabase/browser';

type Row={id?:string;title:string;artist_name:string;description:string;media_url:string;cover_url:string;media_type:string;featured:boolean};
const empty:Row={title:'',artist_name:'',description:'',media_url:'',cover_url:'',media_type:'video',featured:false};
export default function StreamingManager(){
 const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState<Row>({...empty});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [preview,setPreview]=useState('');
 async function load(){const r=await fetch('/api/admin/data?section=video-media');const j=await r.json().catch(()=>({}));if(r.ok)setRows(j.rows||[]);else setMessage(j.error||'Unable to load streaming content')}
 useEffect(()=>{load()},[]);
 async function uploadVideo(file?:File){if(!file)return;setBusy(true);setMessage('Preparing video upload…');setPreview(URL.createObjectURL(file));try{const r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mime:file.type||'video/mp4',size:file.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare upload');setMessage('Uploading video…');const supabase=createBrowserClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,file,{contentType:file.type||'video/mp4'});if(error)throw error;setForm(f=>({...f,media_url:j.publicUrl}));setPreview(j.publicUrl);setMessage('Video uploaded. Add the episode details and click PUBLISH TO WATCH.')}catch(e:any){setMessage(e.message||'Upload failed')}finally{setBusy(false)}}
 async function uploadCover(file?:File){if(!file)return;setBusy(true);try{const r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mime:file.type||'image/jpeg',size:file.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare cover upload');const supabase=createBrowserClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,file,{contentType:file.type||'image/jpeg'});if(error)throw error;setForm(f=>({...f,cover_url:j.publicUrl}));setMessage('Cover uploaded.')}catch(e:any){setMessage(e.message||'Cover upload failed')}finally{setBusy(false)}}
 async function save(){if(!form.title||!form.media_url)return setMessage('Add a title and upload the video first.');setBusy(true);try{const r=await fetch('/api/admin/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({section:'video-media',data:{...form,media_type:'video'}})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Publish failed');setForm({...empty});setPreview('');setMessage('Published to Indie Cut Watch.');await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(id?:string){if(!id||!confirm('Delete this video?'))return;await fetch(`/api/admin/data?section=video-media&id=${encodeURIComponent(id)}`,{method:'DELETE'});await load()}
 return <section className="ic-module-panel"><h2>Streaming / Shows & Episodes</h2><p>Upload hosted Indie Cut programming here. These videos use the Indie Cut Watch player and can run your streaming commercials during playback.</p><div style={{display:'grid',gap:14}}><label>Show / Series name<input value={form.artist_name} onChange={e=>setForm({...form,artist_name:e.target.value})} placeholder="Example: TNG Original Series"/></label><label>Episode / Video title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Episode 1 — The Beginning"/></label><label>Content type<select value={form.media_type} onChange={e=>setForm({...form,media_type:e.target.value})}><option value="video">Episode / Show</option><option value="trailer">Trailer</option><option value="interview">Interview</option><option value="clip">Clip</option></select></label><div><label>Upload video content</label><input type="file" accept="video/*" disabled={busy} onChange={e=>uploadVideo(e.target.files?.[0])}/>{preview&&<video src={preview} controls playsInline style={{display:'block',width:'100%',maxWidth:760,maxHeight:430,background:'#000',marginTop:10}}/>}</div><div><label>Upload poster / thumbnail</label><input type="file" accept="image/*" disabled={busy} onChange={e=>uploadCover(e.target.files?.[0])}/>{form.cover_url&&<img src={form.cover_url} alt="Cover preview" style={{display:'block',maxWidth:240,maxHeight:180,objectFit:'cover',marginTop:10}}/>}</div><label>Description<textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured programming</label><button onClick={save} disabled={busy||!form.media_url} style={{maxWidth:230}}>{busy?'WORKING…':'PUBLISH TO WATCH'}</button>{message&&<div className="ic-message">{message}</div>}</div><div style={{marginTop:34,borderTop:'1px solid #ddd',paddingTop:20}}><h2>Hosted Programming</h2>{rows.length===0?<p>No hosted episodes yet.</p>:rows.map(r=><article key={r.id} style={{display:'grid',gridTemplateColumns:'120px 1fr auto',gap:14,padding:'14px 0',borderBottom:'1px solid #eee',alignItems:'center'}}>{r.cover_url?<img src={r.cover_url} alt="" style={{width:120,height:72,objectFit:'cover'}}/>:<div style={{width:120,height:72,background:'#111'}}/>}<div><strong>{r.title}</strong><div style={{fontSize:13,color:'#666'}}>{r.artist_name||'Indie Cut'} · {r.media_type}</div></div><button onClick={()=>remove(r.id)}>Delete</button></article>)}</div></section>
}
