'use client';
import {useEffect,useState} from 'react';
import {createClient as createBrowserClient} from '../../lib/supabase/browser';

type BreakMode='none'|'interval'|'custom';
type Row={id?:string;title:string;artist_name:string;description:string;media_url:string;cover_url:string;media_type:string;featured:boolean;ad_break_mode:BreakMode;ad_break_interval_minutes:number;custom_ad_breaks:string};
const empty:Row={title:'',artist_name:'',description:'',media_url:'',cover_url:'',media_type:'video',featured:false,ad_break_mode:'interval',ad_break_interval_minutes:6,custom_ad_breaks:''};

export default function StreamingManager(){
 const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState<Row>({...empty});const [videoBusy,setVideoBusy]=useState(false);const [coverBusy,setCoverBusy]=useState(false);const [publishing,setPublishing]=useState(false);const [videoMessage,setVideoMessage]=useState('No video uploaded yet.');const [coverMessage,setCoverMessage]=useState('');const [publishMessage,setPublishMessage]=useState('');const [preview,setPreview]=useState('');const busy=videoBusy||coverBusy||publishing;
 async function load(){const r=await fetch('/api/admin/data?section=video-media');const j=await r.json().catch(()=>({}));if(r.ok)setRows((j.rows||[]).map((x:any)=>({...empty,...x})));else setPublishMessage(j.error||'Unable to load streaming content')}
 useEffect(()=>{load()},[]);
 async function uploadVideo(file?:File){if(!file)return;setVideoBusy(true);setPublishMessage('');setVideoMessage(`Preparing ${file.name}…`);const local=URL.createObjectURL(file);setPreview(local);try{const r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mime:file.type||'video/mp4',size:file.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare upload');setVideoMessage(j.provider==='r2'?'Uploading video directly to Cloudflare R2…':'Uploading video…');if(j.provider==='r2'){/* The R2 presigned URL is signed with host only. Do not add Content-Type here: adding a non-required request header forces an additional CORS preflight header check and was causing Chrome to surface only "Failed to fetch" even after the server-side R2 write check succeeded. */const put=await fetch(j.signedUrl,{method:'PUT',body:file});if(!put.ok)throw new Error(`Cloudflare R2 rejected the video upload (${put.status}).`)}else{const supabase=createBrowserClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,file,{contentType:file.type||'video/mp4'});if(error)throw error}setForm(f=>({...f,media_url:j.publicUrl}));setPreview(j.publicUrl);setVideoMessage('✓ Video uploaded and ready to publish.')}catch(e:any){setForm(f=>({...f,media_url:''}));setVideoMessage(`✕ Video upload failed: ${e?.message||'Unknown error'}`)}finally{setVideoBusy(false)}}
 async function uploadCover(file?:File){if(!file)return;setCoverBusy(true);setCoverMessage('Uploading cover…');try{const r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mime:file.type||'image/jpeg',size:file.size})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to prepare cover upload');if(j.provider==='r2'){const put=await fetch(j.signedUrl,{method:'PUT',body:file});if(!put.ok)throw new Error('Cover upload failed')}else{const supabase=createBrowserClient();const {error}=await supabase.storage.from(j.bucket).uploadToSignedUrl(j.path,j.token,file,{contentType:file.type||'image/jpeg'});if(error)throw error}setForm(f=>({...f,cover_url:j.publicUrl}));setCoverMessage('✓ Cover uploaded.')}catch(e:any){setCoverMessage(`✕ Cover upload failed: ${e?.message||'Unknown error'}`)}finally{setCoverBusy(false)}}
 async function save(){setPublishMessage('');if(!form.title){setPublishMessage('Add a title first.');return}if(!form.media_url){setPublishMessage('The video has not finished uploading. Upload the video successfully before publishing.');return}setPublishing(true);try{const payload={...form,ad_break_interval_minutes:form.ad_break_mode==='interval'?form.ad_break_interval_minutes:null,custom_ad_breaks:form.ad_break_mode==='custom'?form.custom_ad_breaks:''};const r=await fetch('/api/admin/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({section:'video-media',data:payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Publish failed');setForm({...empty});setPreview('');setVideoMessage('No video uploaded yet.');setCoverMessage('');setPublishMessage('✓ Published to the selected Indie Cut Watch category.');await load()}catch(e:any){setPublishMessage(`✕ ${e.message}`)}finally{setPublishing(false)}}
 async function remove(id?:string){if(!id||!confirm('Delete this video?'))return;await fetch(`/api/admin/data?section=video-media&id=${encodeURIComponent(id)}`,{method:'DELETE'});await load()}
 function scheduleLabel(r:Row){if(r.ad_break_mode==='interval')return `Ads every ${r.ad_break_interval_minutes||6} min`;if(r.ad_break_mode==='custom')return `Custom breaks: ${r.custom_ad_breaks||'not set'}`;return 'No commercial breaks'}
 return (
  <section className="ic-module-panel">
   <h2>Streaming / Watch Content</h2><p>Upload programming and choose exactly where it appears on Indie Cut Watch.</p>
   <div style={{display:'grid',gap:14}}>
    <label>Watch category<select value={form.media_type} onChange={e=>setForm({...form,media_type:e.target.value})}><option value="video">Shows & Episodes</option><option value="film">Films</option><option value="trailer">Trailers</option><option value="interview">Interviews</option><option value="music_video">Music Videos</option><option value="clip">Clips</option></select></label>
    <label>Show / Series / Creator name<input value={form.artist_name} onChange={e=>setForm({...form,artist_name:e.target.value})}/></label>
    <label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
    <div><label>Upload video content</label><input type="file" accept="video/*" disabled={videoBusy||publishing} onChange={e=>uploadVideo(e.target.files?.[0])}/>{preview&&<video src={preview} controls playsInline style={{display:'block',width:'100%',maxWidth:760,maxHeight:430,background:'#000',marginTop:10}}/>}<div style={{marginTop:8,fontWeight:800,color:form.media_url?'#18794e':videoMessage.startsWith('✕')?'#b42318':'#555'}}>{videoBusy?'Uploading — keep this page open…':videoMessage}</div></div>
    <div><label>Upload poster / thumbnail</label><input type="file" accept="image/*" disabled={coverBusy||publishing} onChange={e=>uploadCover(e.target.files?.[0])}/>{form.cover_url&&<img src={form.cover_url} alt="Cover preview" style={{display:'block',maxWidth:240,maxHeight:180,objectFit:'cover',marginTop:10}}/>}{coverMessage&&<div style={{marginTop:8,fontWeight:700}}>{coverMessage}</div>}</div>
    <label>Description<textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    <div style={{padding:18,border:'1px solid #ccc',background:'#fafafa',display:'grid',gap:12}}><strong>Commercial Break Schedule</strong><label>Break mode<select value={form.ad_break_mode} onChange={e=>setForm({...form,ad_break_mode:e.target.value as BreakMode})}><option value="none">No commercials</option><option value="interval">Automatic interval</option><option value="custom">Custom timestamps</option></select></label>{form.ad_break_mode==='interval'&&<label>Run a commercial every<input type="number" min="1" max="120" value={form.ad_break_interval_minutes} onChange={e=>setForm({...form,ad_break_interval_minutes:Math.max(1,Number(e.target.value)||6)})}/><span style={{fontSize:12,color:'#666'}}> minutes</span></label>}{form.ad_break_mode==='custom'&&<label>Custom break timestamps<input value={form.custom_ad_breaks} onChange={e=>setForm({...form,custom_ad_breaks:e.target.value})} placeholder="03:00, 06:30, 09:00"/></label>}</div>
    <label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured programming</label>
    <button onClick={save} disabled={busy||!form.media_url} title={!form.media_url?'Upload the video successfully first':''} style={{maxWidth:230,opacity:(busy||!form.media_url)?0.55:1}}>{publishing?'PUBLISHING…':videoBusy?'VIDEO UPLOADING…':'PUBLISH TO WATCH'}</button>
    {!form.media_url&&!videoBusy&&<div style={{fontSize:13,color:'#777'}}>Publish unlocks automatically after the video upload completes.</div>}{publishMessage&&<div className="ic-message">{publishMessage}</div>}
   </div>
   <div style={{marginTop:34,borderTop:'1px solid #ddd',paddingTop:20}}><h2>Published Watch Content</h2>{rows.length===0?<p>No hosted programming yet.</p>:rows.map(r=><article key={r.id} style={{display:'grid',gridTemplateColumns:'120px 1fr auto',gap:14,padding:'14px 0',borderBottom:'1px solid #eee',alignItems:'center'}}>{r.cover_url?<img src={r.cover_url} alt="" style={{width:120,height:72,objectFit:'cover'}}/>:<div style={{width:120,height:72,background:'#111'}}/>}<div><strong>{r.title}</strong><div style={{fontSize:13,color:'#666'}}>{r.artist_name||'Indie Cut'} · {r.media_type.replace('_',' ')}</div><div style={{fontSize:12,fontWeight:800,marginTop:4}}>{scheduleLabel(r)}</div></div><button onClick={()=>remove(r.id)}>Delete</button></article>)}</div>
  </section>
 )
}
