'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
type Room={id:string;title:string;topic:string;status:'draft'|'live'|'ended';listeners:number;speakers:number;created:string};
type Promo={id:string;name:string;image:string;link:string;price:number;minutes:number;startedAt:number;endsAt:number;status:'active'|'ended';test:boolean};
export default function TheCutManager(){
 const [title,setTitle]=useState(''),[topic,setTopic]=useState(''),[rooms,setRooms]=useState<Room[]>([]),[copied,setCopied]=useState(''),[visible,setVisible]=useState(false),[testMode,setTestMode]=useState(true),[promosEnabled,setPromosEnabled]=useState(true),[price,setPrice]=useState(5),[minutes,setMinutes]=useState(10),[promos,setPromos]=useState<Promo[]>([]),[now,setNow]=useState(Date.now());
 useEffect(()=>{setVisible(localStorage.getItem('indiecut-the-cut-visible')==='true');setTestMode(localStorage.getItem('indiecut-promo-test-mode')!=='false');setPromosEnabled(localStorage.getItem('indiecut-promos-enabled')!=='false');setPrice(Number(localStorage.getItem('indiecut-promo-price')||5));setMinutes(Number(localStorage.getItem('indiecut-promo-minutes')||10));try{setPromos(JSON.parse(localStorage.getItem('indiecut-cut-promos')||'[]'))}catch{}const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!promos.length)return;const next=promos.map(p=>p.status==='active'&&p.endsAt<=now?{...p,status:'ended' as const}:p);if(next.some((p,i)=>p.status!==promos[i].status)){setPromos(next);localStorage.setItem('indiecut-cut-promos',JSON.stringify(next));window.dispatchEvent(new Event('indiecut-promos-changed'))}},[now,promos]);
 const live=useMemo(()=>rooms.filter(r=>r.status==='live'),[rooms]),activePromos=promos.filter(p=>p.status==='active'&&p.endsAt>now);
 function visibility(v:boolean){setVisible(v);localStorage.setItem('indiecut-the-cut-visible',String(v))}function setting(key:string,v:boolean){localStorage.setItem(key,String(v));if(key==='indiecut-promo-test-mode')setTestMode(v);else setPromosEnabled(v)}function pricing(p:number,m:number){setPrice(p);setMinutes(m);localStorage.setItem('indiecut-promo-price',String(p));localStorage.setItem('indiecut-promo-minutes',String(m))}
 function createRoom(goLive=false){if(!title.trim())return;const room:Room={id:`cut-${Date.now()}`,title:title.trim(),topic:topic.trim(),status:goLive?'live':'draft',listeners:0,speakers:1,created:new Date().toLocaleString()};setRooms(r=>[room,...r]);setTitle('');setTopic('')}function setStatus(id:string,status:Room['status']){setRooms(r=>r.map(x=>x.id===id?{...x,status}:x))}async function copy(id:string){await navigator.clipboard.writeText(`${window.location.origin}/the-cut?room=${id}`);setCopied(id);setTimeout(()=>setCopied(''),1500)}function endPromo(id:string){const next=promos.map(p=>p.id===id?{...p,status:'ended' as const,endsAt:Date.now()}:p);setPromos(next);localStorage.setItem('indiecut-cut-promos',JSON.stringify(next));window.dispatchEvent(new Event('indiecut-promos-changed'))}
 return <section style={{display:'grid',gap:20}}>
 <div className="panel" style={{padding:24,display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,flexWrap:'wrap'}}><div><div className="kicker">PUBLIC VISIBILITY</div><h2 style={{margin:'6px 0'}}>The Cut is {visible?'visible':'hidden'}</h2><p style={{margin:0,maxWidth:650}}>Keep The Cut hidden while you build and test it.</p></div><div style={{display:'flex',gap:8}}><button onClick={()=>visibility(false)} disabled={!visible}>HIDE THE CUT</button><button onClick={()=>visibility(true)} disabled={visible}>SHOW THE CUT</button></div></div>
 <div className="panel" style={{padding:24}}><div className="kicker">PAID ROOM PROMOTIONS</div><h2 style={{margin:'6px 0'}}>Promotion test center</h2><p>Test the complete promotion experience before Stripe is connected. Test checkout behaves like a successful transaction but does not charge a card.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14,margin:'18px 0'}}><label><b>Promotions</b><select value={promosEnabled?'on':'off'} onChange={e=>setting('indiecut-promos-enabled',e.target.value==='on')}><option value="on">Enabled</option><option value="off">Disabled</option></select></label><label><b>Payment mode</b><select value={testMode?'test':'live'} onChange={e=>setting('indiecut-promo-test-mode',e.target.value==='test')}><option value="test">TEST MODE — no charge</option><option value="live">LIVE MODE — Stripe required</option></select></label><label><b>Price ($)</b><input type="number" min="1" step="1" value={price} onChange={e=>pricing(Math.max(1,Number(e.target.value)),minutes)}/></label><label><b>Duration (minutes)</b><input type="number" min="1" value={minutes} onChange={e=>pricing(price,Math.max(1,Number(e.target.value)))}/></label></div><div style={{padding:14,background:testMode?'#fff5c7':'#eee',fontWeight:800}}>{testMode?'TEST MODE ACTIVE — simulated payments are clearly marked and no money is collected.':'LIVE MODE SELECTED — checkout stays blocked until Stripe is wired.'}</div><h3 style={{marginTop:24}}>Active promotions ({activePromos.length})</h3>{activePromos.length===0?<p>No active promotions. Open a Cut room and use Promote Profile to run an end-to-end test.</p>:activePromos.map(p=><article key={p.id} style={{borderTop:'1px solid #ddd',padding:'14px 0',display:'flex',justifyContent:'space-between',gap:15}}><div><strong>{p.name} {p.test?'· TEST':''}</strong><div>${p.price.toFixed(2)} · {Math.max(0,Math.ceil((p.endsAt-now)/60000))} min remaining</div><small>{p.link}</small></div><button onClick={()=>endPromo(p.id)}>END PROMO</button></article>)}</div>
 <div className="panel" style={{padding:24}}><div className="kicker">ROOM CREATOR</div><h2>Start a room</h2><label>Room title</label><input value={title} onChange={e=>setTitle(e.target.value)}/><label>Topic / description</label><textarea rows={4} value={topic} onChange={e=>setTopic(e.target.value)}/><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:14}}><button disabled={!title.trim()} onClick={()=>createRoom(true)}>GO LIVE</button><button disabled={!title.trim()} onClick={()=>createRoom(false)}>SAVE DRAFT</button><Link href="/the-cut" target="_blank">PREVIEW THE CUT ↗</Link></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14}}><div className="panel"><div className="kicker">LIVE NOW</div><h2>{live.length}</h2><p>Active rooms</p></div><div className="panel"><div className="kicker">LISTENERS</div><h2>{live.reduce((n,r)=>n+r.listeners,0)}</h2><p>Across live rooms</p></div><div className="panel"><div className="kicker">ON STAGE</div><h2>{live.reduce((n,r)=>n+r.speakers,0)}</h2><p>Hosts and speakers</p></div></div>
 <div className="panel" style={{padding:24}}><div className="kicker">ROOM CONTROL</div><h2>Rooms</h2>{rooms.length===0?<p>No rooms yet.</p>:rooms.map(r=><article key={r.id} style={{borderTop:'1px solid #ddd',padding:'18px 0'}}><strong>{r.title}</strong><p>{r.topic||'No description'} · {r.status}</p><div style={{display:'flex',gap:8}}>{r.status!=='live'&&<button onClick={()=>setStatus(r.id,'live')}>GO LIVE</button>}{r.status==='live'&&<button onClick={()=>setStatus(r.id,'ended')}>END ROOM</button>}<button onClick={()=>copy(r.id)}>{copied===r.id?'LINK COPIED':'COPY SHARE LINK'}</button></div></article>)}</div></section>}
