'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
type Room={id:string;title:string;topic:string;status:'draft'|'live'|'ended';listeners:number;speakers:number;created:string};
export default function TheCutManager(){
 const [title,setTitle]=useState(''),[topic,setTopic]=useState(''),[rooms,setRooms]=useState<Room[]>([]),[copied,setCopied]=useState(''),[visible,setVisible]=useState(false);
 useEffect(()=>{setVisible(localStorage.getItem('indiecut-the-cut-visible')==='true')},[]);const live=useMemo(()=>rooms.filter(r=>r.status==='live'),[rooms]);
 function visibility(v:boolean){setVisible(v);localStorage.setItem('indiecut-the-cut-visible',String(v))}
 function createRoom(goLive=false){if(!title.trim())return;const room:Room={id:`cut-${Date.now()}`,title:title.trim(),topic:topic.trim(),status:goLive?'live':'draft',listeners:0,speakers:1,created:new Date().toLocaleString()};setRooms(r=>[room,...r]);setTitle('');setTopic('')}
 function setStatus(id:string,status:Room['status']){setRooms(r=>r.map(x=>x.id===id?{...x,status}:x))}async function copy(id:string){await navigator.clipboard.writeText(`${window.location.origin}/the-cut?room=${id}`);setCopied(id);setTimeout(()=>setCopied(''),1500)}
 return <section style={{display:'grid',gap:20}}>
 <div className="panel" style={{padding:24,display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,flexWrap:'wrap'}}><div><div className="kicker">PUBLIC VISIBILITY</div><h2 style={{margin:'6px 0'}}>The Cut is {visible?'visible':'hidden'}</h2><p style={{margin:0,maxWidth:650}}>Keep The Cut hidden while you build and test it. When you are ready, publish it from here.</p></div><div style={{display:'flex',gap:8}}><button onClick={()=>visibility(false)} disabled={!visible}>HIDE THE CUT</button><button onClick={()=>visibility(true)} disabled={visible}>SHOW THE CUT</button></div></div>
 <div className="panel" style={{padding:24}}><div className="kicker">ROOM CREATOR</div><h2 style={{margin:'6px 0 8px'}}>Start a room</h2><p>Create a live social-audio conversation. Listeners enter quietly and can raise their hand to request the mic.</p><label>Room title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Example: Filmmakers — what is working right now?"/><label>Topic / description</label><textarea rows={4} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Tell listeners what this room is about."/><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:14}}><button disabled={!title.trim()} onClick={()=>createRoom(true)}>GO LIVE</button><button disabled={!title.trim()} onClick={()=>createRoom(false)}>SAVE DRAFT</button><Link href="/the-cut" target="_blank" style={{padding:'10px 14px',border:'1px solid #111',fontWeight:800,textDecoration:'none',color:'#111'}}>PREVIEW THE CUT ↗</Link></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14}}><div className="panel"><div className="kicker">LIVE NOW</div><h2>{live.length}</h2><p>Active rooms</p></div><div className="panel"><div className="kicker">LISTENERS</div><h2>{live.reduce((n,r)=>n+r.listeners,0)}</h2><p>Across live rooms</p></div><div className="panel"><div className="kicker">ON STAGE</div><h2>{live.reduce((n,r)=>n+r.speakers,0)}</h2><p>Hosts and speakers</p></div></div>
 <div className="panel" style={{padding:24}}><div className="kicker">ROOM CONTROL</div><h2>Rooms</h2>{rooms.length===0?<p>No rooms yet. Create your first room above.</p>:rooms.map(r=><article key={r.id} style={{borderTop:'1px solid #ddd',padding:'18px 0'}}><strong>{r.title}</strong><p>{r.topic||'No description'} · {r.status}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{r.status!=='live'&&<button onClick={()=>setStatus(r.id,'live')}>GO LIVE</button>}{r.status==='live'&&<button onClick={()=>setStatus(r.id,'ended')}>END ROOM</button>}<button onClick={()=>copy(r.id)}>{copied===r.id?'LINK COPIED':'COPY SHARE LINK'}</button><Link href={`/the-cut?room=${r.id}`} target="_blank">VIEW ROOM ↗</Link></div></article>)}</div></section>
}
