'use client';
import styles from './AutomationBuilder.module.css';

const TRIGGERS={
 'Contact':['Birthday Reminder','Contact Changed','Contact Created','Contact DND','Contact Tag','Custom Date Reminder','Note Added','Note Changed','Task Added','Task Reminder','Task Completed','Contact Engagement Score'],
 'Events':['Inbound Webhook','Scheduler','Call Details','Email Events','Customer Replied','Conversation AI Trigger','Custom Trigger','Form Submitted','Survey Submitted','Trigger Link Clicked','Facebook Lead Form Submitted','TikTok Form Submitted','Video Tracking','Number Validation','Messaging Error – SMS','LinkedIn Lead Form Submitted','Funnel / Website PageView','Quiz Submitted','New Review Received','Prospect Generated','Click To WhatsApp Ads','External Tracking Event'],
 'Appointments':['Appointment Status','Customer Booked Appointment','Service Booking','Rental Booking'],
 'Opportunities':['Opportunity Status Changed','Opportunity Created','Opportunity Changed','Pipeline Stage Changed','Stale Opportunities'],
 'Affiliate':['Affiliate Created','New Affiliate Sales','Affiliate Enrolled In Campaign','Affiliate Lead Created'],
 'Courses':['Category Started','Category Completed','Lesson Started','Lesson Completed','New Signup','Offer Access Granted','Offer Access Removed','Product Access Granted','Product Access Removed','Product Started','Product Completed','User Login'],
 'Payments':['Invoice','Payment Received','Order Form Submission','Order Submitted','Documents & Contracts','Estimates','Subscription','Refund','Coupon Code Applied','Coupon Redemption Limit Reached','Coupon Code Expired','Coupon Code Redeemed'],
 'Ecommerce Stores':['Shopify Abandoned Cart','Shopify Order Placed','Shopify Order Fulfilled','Order Fulfilled','Product Review Submitted','Abandoned Checkout'],
 'IVR':['Start IVR Trigger'],
 'Facebook / Instagram Events':['Facebook – Comments On A Post','Instagram – Comments On A Post'],
 'Communities':['Group Access Granted','Group Access Revoked','Private Channel Access Granted','Private Channel Access Revoked','Community Group Member Leaderboard Level Changed'],
 'Certificates':['Certificate Issued'],
 'Communication':['TikTok – Comments On A Video','Transcript Generated'],
 'Google Ads':['Google Lead Form Submitted'],
 'Indie Cut':['Battle Submission Received','Battle Submission Approved','Battle Submission Rejected','Vote Received','Artist Advanced','Battle Started','Battle Ended','Winner Selected']
};
const ACTIONS={
 'Contact Actions':['Create Contact','Find Contact','Update Contact Field','Add Contact Tag','Remove Contact Tag','Assign to User','Remove Assigned User','Edit Conversation','Disable / Enable DND','Add Note','Add Task','Copy Contact','Delete Contact','Modify Contact Engagement Score','Add / Remove Contact Followers'],
 'Communication Actions':['Send Email','Send SMS','Send Slack Message','Call','Messenger','Instagram DM','Manual Action','GMB Messaging','Send Internal Notification','Send Review Request','Conversation AI','Facebook Interactive Messenger','Instagram Interactive Messenger','Reply in Comments','WhatsApp','Send Live Chat Message'],
 'Send Data':['Webhook / Custom Webhook','Google Sheets'],
 'Internal Tools':['If / Else','Wait Step','Goal Event','Split','Update Custom Value','Go To','Remove from Workflow','Arrays','Drip Mode','Text Formatter','Custom Code'],
 'Workflow AI':['AI Prompt','AI Agent','AI Decision Maker','AI Intent Detection','AI Summarize','AI Translate','AI Extract Data','AI Image Generation','AI Analyze Image','Update Conversation AI Bot and Status','Invoke Agent Studio Agent'],
 'Appointments':['Update Appointment Status','Generate One Time Booking Link'],
 'Opportunities':['Create / Update Opportunity','Remove Opportunity'],
 'Payments':['Stripe One-Time Charge','Send Invoice','Send Documents and Contracts'],
 'Marketing':['Add to Google Analytics','Add to Google Ads','Add to Custom Audience (Facebook)','Remove from Custom Audience (Facebook)','Facebook Conversion API'],
 'Affiliate':['Add to Affiliate Manager','Update Affiliate','Add / Remove from Affiliate Campaign'],
 'Courses':['Course Grant Offer','Course Revoke Offer'],
 'IVR':['Gather Input on Call','Play Message','Connect to Call','End Call','Record Voicemail'],
 'Communities':['Grant Group Access','Revoke Group Access'],
 'Indie Cut Core':['Stop Workflow','Add to Workflow','Remove Tag','Update Status','Wait Until','Internal Email Notification','Outbound Webhook']
};

const NATIVE=new Set([
 'Birthday Reminder','Contact Changed','Contact Created','Contact DND','Contact Tag','Custom Date Reminder','Note Added','Note Changed','Task Added','Task Reminder','Task Completed','Contact Engagement Score',
 'Inbound Webhook','Scheduler','Customer Replied','Conversation AI Trigger','Custom Trigger','Form Submitted','Survey Submitted','Trigger Link Clicked','Funnel / Website PageView','Quiz Submitted','New Review Received','Prospect Generated','External Tracking Event',
 'Appointment Status','Customer Booked Appointment','Service Booking','Rental Booking','Opportunity Status Changed','Opportunity Created','Opportunity Changed','Pipeline Stage Changed','Stale Opportunities',
 'Affiliate Created','New Affiliate Sales','Affiliate Enrolled In Campaign','Affiliate Lead Created','Category Started','Category Completed','Lesson Started','Lesson Completed','New Signup','Offer Access Granted','Offer Access Removed','Product Access Granted','Product Access Removed','Product Started','Product Completed','User Login',
 'Invoice','Payment Received','Order Form Submission','Order Submitted','Estimates','Subscription','Refund','Coupon Code Applied','Coupon Redemption Limit Reached','Coupon Code Expired','Coupon Code Redeemed','Order Fulfilled','Product Review Submitted','Abandoned Checkout',
 'Group Access Granted','Group Access Revoked','Private Channel Access Granted','Private Channel Access Revoked','Community Group Member Leaderboard Level Changed','Certificate Issued','Transcript Generated',
 'Battle Submission Received','Battle Submission Approved','Battle Submission Rejected','Vote Received','Artist Advanced','Battle Started','Battle Ended','Winner Selected',
 'Create Contact','Find Contact','Update Contact Field','Add Contact Tag','Remove Contact Tag','Assign to User','Remove Assigned User','Edit Conversation','Disable / Enable DND','Add Note','Add Task','Copy Contact','Delete Contact','Modify Contact Engagement Score','Add / Remove Contact Followers',
 'Send Email','Send SMS','Manual Action','Send Internal Notification','Send Review Request','Conversation AI','Webhook / Custom Webhook','If / Else','Wait Step','Goal Event','Split','Update Custom Value','Go To','Remove from Workflow','Arrays','Drip Mode','Text Formatter','AI Prompt','AI Agent','AI Decision Maker','AI Intent Detection','AI Summarize','AI Translate','AI Extract Data','Update Appointment Status','Generate One Time Booking Link','Create / Update Opportunity','Remove Opportunity','Send Invoice','Add to Affiliate Manager','Update Affiliate','Add / Remove from Affiliate Campaign','Course Grant Offer','Course Revoke Offer','Grant Group Access','Revoke Group Access','Stop Workflow','Add to Workflow','Remove Tag','Update Status','Wait Until','Internal Email Notification','Outbound Webhook'
]);
const CONNECTION_HINT:any={
 'Call Details':'voice provider','Email Events':'inbound email provider','Facebook Lead Form Submitted':'Meta lead connection','TikTok Form Submitted':'TikTok lead connection','Video Tracking':'video tracking source','Number Validation':'phone validation provider','Messaging Error – SMS':'TextGrid delivery webhook','LinkedIn Lead Form Submitted':'LinkedIn lead connection','Click To WhatsApp Ads':'WhatsApp / Meta connection','Documents & Contracts':'documents provider','Shopify Abandoned Cart':'Shopify','Shopify Order Placed':'Shopify','Shopify Order Fulfilled':'Shopify','Start IVR Trigger':'voice provider','Facebook – Comments On A Post':'Meta social connection','Instagram – Comments On A Post':'Meta social connection','TikTok – Comments On A Video':'TikTok social connection','Google Lead Form Submitted':'Google Ads lead connection',
 'Send Slack Message':'Slack','Call':'voice provider','Messenger':'Meta messaging','Instagram DM':'Meta messaging','GMB Messaging':'Google Business','Facebook Interactive Messenger':'Meta messaging','Instagram Interactive Messenger':'Meta messaging','Reply in Comments':'social messaging','WhatsApp':'WhatsApp','Send Live Chat Message':'live chat','Google Sheets':'Google Sheets','Custom Code':'secure code runner','AI Image Generation':'image generation service','AI Analyze Image':'vision service','Update Conversation AI Bot and Status':'conversation AI module','Invoke Agent Studio Agent':'agent runtime','Stripe One-Time Charge':'Stripe','Send Documents and Contracts':'documents provider','Add to Google Analytics':'Google Analytics','Add to Google Ads':'Google Ads','Add to Custom Audience (Facebook)':'Meta Ads','Remove from Custom Audience (Facebook)':'Meta Ads','Facebook Conversion API':'Meta Ads','Gather Input on Call':'voice provider','Play Message':'voice provider','Connect to Call':'voice provider','End Call':'voice provider','Record Voicemail':'voice provider'
};
function Group({title,items}:{title:string;items:string[]}){return <div style={{marginBottom:18}}><div className={styles.sectionTitle}>{title}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8}}>{items.map(name=>{const native=NATIVE.has(name),hint=CONNECTION_HINT[name];return <div key={name} style={{border:'1px solid #e5e7eb',borderRadius:8,padding:'10px 12px',background:'#fff',display:'flex',gap:9,alignItems:'center'}}><span style={{width:9,height:9,borderRadius:999,background:native?'#12b76a':'#f79009',flex:'0 0 auto'}}/><div><strong style={{fontSize:12}}>{name}</strong><div className={styles.tiny}>{native?'INDIE CUT ENGINE READY':`ENGINE READY · CONNECT ${String(hint||'SOURCE').toUpperCase()}`}</div></div></div>})}</div></div>}
export default function WorkflowFullCatalog(){return <section className={styles.panel} style={{marginTop:22}}><h2 style={{marginTop:0}}>Complete Workflow Capability Library</h2><p className={styles.muted}>Green means the Indie Cut automation engine can run it now. Amber means the workflow engine is ready, but the outside provider still has to be connected before that external event or action can occur. Nothing here is a fake red placeholder anymore.</p><details open><summary style={{cursor:'pointer',fontWeight:900,padding:'10px 0'}}>All Triggers</summary>{Object.entries(TRIGGERS).map(([k,v])=><Group key={k} title={k} items={v}/>)}</details><details style={{marginTop:8}}><summary style={{cursor:'pointer',fontWeight:900,padding:'10px 0'}}>All Actions</summary>{Object.entries(ACTIONS).map(([k,v])=><Group key={k} title={k} items={v}/>)}</details></section>}
