'use client';

import { useEffect,useRef,useState } from 'react';
import styles from '../../battles.module.css';

export default function StudioClient({slug,slot,accessCode}:{slug:string;slot:string;accessCode:string}){
 const [name,setName]=useState(slot==='dj'?'Indie Cut DJ':slot==='a'?'Artist A':'Artist B');const [joined,setJoined]=useState(false);const [message,setMessage]=useState('');const [muted,setMuted]=useState(false);const [videoOn,setVideoOn]=useState(false);const [battle,setBattle]=useState<any>(null);
 const clientRef=useRef<any>(null);const streamRef=useRef<any>(null);const qualityRef=useRef<any>(2);const aRef=useRef<HTMLDivElement>(null);const djRef=useRef<HTMLDivElement>(null);const bRef=useRef<HTMLDivElement>(null);const musicRef=useRef<HTMLAudioElement>(null);
 function target(user:any){const n=String(user?.displayName||user?.userName||'').toUpperCase();if(n.startsWith('[A]'))return aRef.current;if(n.startsWith('[B]'))return bRef.current;if(n.startsWith('[DJ]'))return djRef.current;return null}
 async function attach(user:any){const stream=streamRef.current;const el=target(user);if(!stream||!el||!user?.bVideoOn)return;try{const video=await stream.attachVideo(user.userId,qualityRef.current);el.innerHTML='';(Array.isArray(video)?video:[video]).forEach((x:any)=>el.appendChild(x))}catch{}}
 async function refreshUsers(){const client=clientRef.current;if(client)client.getAllUser().forEach((u:any)=>{if(u.bVideoOn)attach(u)})}
 async function refreshBattle(){try{const r=await fetch(`/api/battles/${slug}`,{cache:'no-store'});if(r.ok)setBattle(await r.json())}catch{}}
 useEffect(()=>{if(!joined)return;refreshBattle();const id=setInterval(refreshBattle,2000);return()=>clearInterval(id)},[joined,slug]);
 useEffect(()=>{
  if(!joined||!battle)return;const audio=musicRef.current;if(!audio)return;const r=battle.currentRound;let url='';if(battle.contest.current_segment==='artist_a')url=r?.track_a_url||'';if(battle.contest.current_segment==='artist_b')url=r?.track_b_url||'';
  if(!url){audio.pause();return}const elapsed=battle.contest.segment_started_at?Math.max(0,(Date.now()-new Date(battle.contest.segment_started_at).getTime())/1000):0;if(audio.src!==url)audio.src=url;try{if(Math.abs(audio.currentTime-elapsed)>2)audio.currentTime=elapsed}catch{}audio.play().catch(()=>{});
 },[battle?.contest?.current_segment,battle?.contest?.segment_started_at,battle?.currentRound?.id,joined]);
 async function join(){setMessage('');try{
  const r=await fetch(`/api/battles/${slug}/zoom-token`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'studio',slot,accessCode,userName:name})});const auth=await r.json();if(!r.ok)throw new Error(auth.error||'Could not enter studio');
  const sdk=await import('@zoom/videosdk');const ZoomVideo:any=sdk.default;qualityRef.current=(sdk as any).VideoQuality?.Video_720P??3;const client=ZoomVideo.createClient();clientRef.current=client;await client.init('en-US','Global',{patchJsMedia:true,leaveOnPageUnload:true});await client.join(auth.sessionName,auth.token,auth.displayName,auth.passcode||'');const stream=client.getMediaStream();streamRef.current=stream;await stream.startAudio({originalSound:{hifi:true,stereo:true}});await stream.startVideo({hd:true});setVideoOn(true);setJoined(true);
  client.on('peer-video-state-change',async(p:any)=>{const u=client.getAllUser().find((x:any)=>x.userId===p.userId);if(p.action==='Start'&&u)await attach(u);else if(p.action==='Stop')try{await stream.detachVideo(p.userId)}catch{}});client.on('user-added',()=>setTimeout(refreshUsers,120));client.on('user-removed',(p:any)=>{try{stream.detachVideo(p.userId)}catch{}});setTimeout(refreshUsers,200);
 }catch(e:any){setMessage(e.message||'Could not enter studio')}}
 async function toggleMute(){try{if(muted){await streamRef.current?.unmuteAudio();setMuted(false)}else{await streamRef.current?.muteAudio();setMuted(true)}}catch{}}
 async function toggleVideo(){try{if(videoOn){await streamRef.current?.stopVideo();setVideoOn(false)}else{await streamRef.current?.startVideo({hd:true});setVideoOn(true)}}catch{}}
 useEffect(()=>()=>{try{clientRef.current?.leave()}catch{}},[]);
 if(!accessCode||!['a','b','dj'].includes(slot))return <div className={styles.studio}><div className={styles.studioForm}><h1>Invalid studio link</h1><p>Use the private link from the Indie Cut Battle Control Room.</p></div></div>;
 return <main className={styles.studio}><div className={styles.studioPanel}><div className={styles.eyebrow}>INDIE CUT LIVE · PRIVATE STUDIO</div><h1>{slot==='dj'?'DJ / HOST':slot==='a'?'ARTIST A':'ARTIST B'} CONTROL ROOM</h1><p style={{color:'#aaa'}}><strong>Use headphones.</strong> Music is played directly by Indie Cut for clean, consistent sound while Zoom carries your camera and voice.</p><audio ref={musicRef} preload="auto"/>{!joined?<div className={styles.studioForm}><h2>Enter the battle studio</h2><label>Display name</label><input value={name} onChange={e=>setName(e.target.value)}/><button className={styles.enterButton} style={{marginTop:18,width:'100%'}} onClick={join}>JOIN CAMERA + AUDIO</button>{message&&<div className={styles.notice}>{message}</div>}</div>:<><div className={styles.liveBar}><div><strong><span className={styles.liveDot}/>CONNECTED</strong><div className={styles.small}>{battle?.contest?.current_segment?`Show state: ${String(battle.contest.current_segment).replace('_',' ').toUpperCase()}`:'Waiting for control room'}</div></div><div style={{display:'flex',gap:8}}><button className={styles.shareButton} onClick={toggleMute}>{muted?'UNMUTE':'MUTE'}</button><button className={styles.shareButton} onClick={toggleVideo}>{videoOn?'CAMERA OFF':'CAMERA ON'}</button></div></div><div className={styles.studioGrid}><div className={styles.studioVideo}><div ref={aRef}/><span className={styles.studioLabel}>ARTIST A</span></div><div className={styles.studioVideo}><div ref={djRef}/><span className={styles.studioLabel}>DJ / HOST</span></div><div className={styles.studioVideo}><div ref={bRef}/><span className={styles.studioLabel}>ARTIST B</span></div></div>{battle?.contest?.current_segment==='commercial'&&<div className={styles.notice}>Sponsor break is live to the audience. You remain backstage and connected.</div>}</>}</div></main>
}
