import {NextResponse} from 'next/server';import {createClient} from '../../../../lib/supabase/server';import {createClient as service} from '@supabase/supabase-js';import {isAdminEmail} from '../../../../lib/admin';
export const dynamic='force-dynamic';export const maxDuration=300;const KEY='indie_spotlight_agent_latest';
function text(j:any){if(typeof j?.output_text==='string')return j.output_text;return (j?.output||[]).flatMap((x:any)=>(x.content||[]).map((c:any)=>c.text||'')).join('\n')}
function parse(s:string){return JSON.parse(String(s).trim().replace(/^\`\`\`(?:json)?/i,'').replace(/\`\`\`$/,'').trim())}
async function authDb(){const a=createClient();const {data:{user}}=await a.auth.getUser();if(!user||!isAdminEmail(user.email))return null;return service(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function GET(){const db=await authDb();if(!db)return NextResponse.json({error:'Unauthorized'},{status:401});const {data}=await db.from('site_settings').select('setting_value').eq('setting_key',KEY).maybeSingle();let scan=null;try{scan=JSON.parse(data?.setting_value||'null')}catch{}return NextResponse.json({scan})}
export async function POST(req:Request){const db=await authDb();if(!db)return NextResponse.json({error:'Unauthorized'},{status:401});const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:'OPENAI_API_KEY missing'},{status:503});const input=await req.json().catch(()=>({}));const count=Math.min(20,Math.max(3,Number(input.count||10))),days=Math.min(60,Math.max(7,Number(input.days||30))),focus=String(input.focus||'independent music artists, filmmakers and creators').slice(0,1200);
const prompt=`You are the dedicated Indie Cut Indie Spotlight discovery editor. This is NOT the mainstream celebrity news agent. Use live web search to discover up to ${count} genuinely independent creators with meaningful momentum in the last ${days} days. Focus: ${focus}. Search across independent MUSIC ARTISTS, FILMMAKERS, and other CREATORS. Find people with a real current peg: release, film/festival selection, award, screening, notable collaboration, press pickup, audience growth signal, distribution announcement, crowdfunding success, tour/show, or another verifiable development. Do not choose someone merely because they are obscure.

Independence must be verified. Classify independence_status as confirmed_independent, likely_independent, affiliated, or unknown. Confirmed means credible evidence supports unsigned/self-releasing/artist-owned work, genuinely independent label, self-produced film/company, or comparable creator ownership. Major-label, major-studio or clearly controlled talent is affiliated. Never infer independence from follower count. creator_type must be exactly music_artist, filmmaker, or creator. Require multiple credible sources when possible, cross-check names and current facts, and never invent numbers, quotes, credits, awards, affiliations or biography. Return ONLY JSON {"creators":[{"creator_name":"","creator_type":"music_artist|filmmaker|creator","field":"","city":"","independence_status":"confirmed_independent|likely_independent|affiliated|unknown","independence_note":"","why_now":"","momentum_score":0,"story_angle":"","image_url":"","website":"","instagram":"","youtube":"","sources":["https://..."]}]}`;
const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',tools:[{type:'web_search'}],input:prompt,max_output_tokens:24000})});const j=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:j?.error?.message||'Research failed'},{status:502});let p:any;try{p=parse(text(j))}catch{return NextResponse.json({error:'Agent returned invalid JSON'},{status:502})}const creators=(Array.isArray(p.creators)?p.creators:[]).filter((x:any)=>x.creator_name&&['confirmed_independent','likely_independent'].includes(x.independence_status)).slice(0,count).sort((a:any,b:any)=>Number(b.momentum_score||0)-Number(a.momentum_score||0));const scan={scanned_at:new Date().toISOString(),focus,days,creators};await db.from('site_settings').upsert({setting_key:KEY,setting_value:JSON.stringify(scan),updated_at:new Date().toISOString()},{onConflict:'setting_key'});return NextResponse.json(scan)}
