import {sendTextGridSms} from './textgrid';
import {enrollMatchingWorkflows} from './crm-workflows';
import {emitWorkflowEvent,upsertWorkflowObject} from './workflow-events';

function normalized(v:any){return String(v??'').trim().toLowerCase()}
export function mergeWorkflowText(text:string,c:any,context:any={}){const first=String(c?.full_name||c?.artist_name||'').split(/\s+/)[0]||'';const map:any={artist_name:c?.artist_name||c?.full_name||'',first_name:first,full_name:c?.full_name||'',genre:c?.genre||'',city:c?.city||'',email:c?.email||'',phone:c?.phone||'',notes:c?.notes||'',source:c?.source||'',status:c?.status||'',...context};return String(text||'').replace(/{{\s*([a-z0-9_]+)\s*}}/gi,(_:string,k:string)=>String(map[k]??''))}
export function waitUntil(config:any){const amount=Math.max(1,Number(config?.amount)||1),unit=String(config?.unit||'hours'),ms=unit==='minutes'?amount*60000:unit==='days'?amount*86400000:amount*3600000;return new Date(Date.now()+ms).toISOString()}
function fieldValue(c:any,f:string){if(f==='tag')return Array.isArray(c?.tags)?c.tags:[];if(f==='email_opt_in'||f==='sms_opt_in'||f==='dnd')return Boolean(c?.[f]);return c?.[f]??''}
function matchesCondition(cfg:any,c:any){const field=String(cfg?.field||'status'),op=String(cfg?.operator||'equals'),expected=cfg?.value,actual=fieldValue(c,field);if(op==='exists')return Array.isArray(actual)?actual.length>0:Boolean(String(actual??'').trim());if(op==='not_exists')return Array.isArray(actual)?actual.length===0:!String(actual??'').trim();if(field==='tag'){const found=(actual as any[]).some(x=>normalized(x)===normalized(expected));return op==='not_equals'||op==='not_contains'?!found:found}if(['email_opt_in','sms_opt_in','dnd'].includes(field)){const wanted=expected===true||String(expected).toLowerCase()==='true',eq=Boolean(actual)===wanted;return op==='not_equals'||op==='not_contains'?!eq:eq}const a=normalized(actual),b=normalized(expected);if(op==='contains')return a.includes(b);if(op==='not_contains')return!a.includes(b);if(op==='not_equals')return a!==b;if(op==='gt')return Number(actual)>Number(expected);if(op==='gte')return Number(actual)>=Number(expected);if(op==='lt')return Number(actual)<Number(expected);if(op==='lte')return Number(actual)<=Number(expected);return a===b}
async function sendEmail(to:string,subject:string,body:string){const key=process.env.RESEND_API_KEY,from=process.env.INDIECUT_FROM_EMAIL;if(!key||!from)throw new Error('Email integration not configured.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({from,to:[to],subject,text:body})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.message||'Email send failed.')}
function responseText(j:any){if(typeof j?.output_text==='string')return j.output_text;const out:string[]=[];for(const item of j?.output||[])for(const part of item?.content||[])if(typeof part?.text==='string')out.push(part.text);return out.join('\n').trim()}
async function aiText(kind:string,cfg:any,c:any){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY is not configured.');const input=mergeWorkflowText(cfg.input||'{{notes}}',c),instruction=mergeWorkflowText(cfg.instruction||'',c);let task='Generate useful concise text for this CRM workflow.';if(kind==='ai_summarize')task='Summarize the input clearly and concisely.';if(kind==='ai_detect_intent')task='Classify the primary intent in a short label, then one sentence of reasoning.';if(kind==='ai_extract')task='Extract the important facts from the input in concise JSON.';if(kind==='ai_translate')task=`Translate the input into ${cfg.language||'Spanish'} while preserving meaning.`;if(kind==='ai_decision')task='Make the best workflow decision from the input and return a concise decision plus reason.';const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:`${task}\n${instruction?`Additional instruction: ${instruction}\n`:''}Input:\n${input}`,max_output_tokens:1200})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||'AI workflow action failed.');return responseText(j)}
async function queueIntegration(client:any,type:string,contact:any,workflow:any,cfg:any,required:string){await client.from('crm_workflow_integration_queue').insert({action_type:type,contact_id:contact?.id||null,workflow_id:workflow?.id||null,required_connection:required,payload:cfg||{},status:'waiting_for_connection'});await client.from('crm_activity').insert({contact_id:contact?.id||null,activity_type:'workflow_waiting_connection',detail:`${workflow?.name||'Workflow'}: ${type} is waiting for ${required}.`})}
async function objectAction(client:any,type:string,contact:any,workflow:any,cfg:any){
 const objectMap:any={create_opportunity:'opportunity',update_opportunity:'opportunity',create_appointment:'appointment',update_appointment:'appointment',affiliate_add:'affiliate',affiliate_update:'affiliate',course_grant:'course_access',course_revoke:'course_access',community_grant:'community_access',community_revoke:'community_access',issue_certificate:'certificate',create_invoice:'invoice',create_estimate:'estimate',create_order:'order',create_subscription:'subscription',create_review_request:'review_request'};
 const objectType=objectMap[type];if(!objectType)return null;
 const status=type.endsWith('_revoke')?'revoked':String(cfg.status||'active');const obj=await upsertWorkflowObject(client,{object_type:objectType,contact_id:contact.id,id:cfg.object_id||null,external_id:cfg.external_id||null,title:mergeWorkflowText(cfg.title||cfg.name||objectType,contact),status,amount:cfg.amount!==undefined?Number(cfg.amount):null,starts_at:cfg.starts_at||null,due_at:cfg.due_at||null,data:{...cfg,workflow_id:workflow.id}});
 const eventMap:any={create_opportunity:'opportunity_created',update_opportunity:'opportunity_changed',create_appointment:'appointment_created',update_appointment:'appointment_changed',affiliate_add:'affiliate_created',affiliate_update:'affiliate_changed',course_grant:'offer_access_granted',course_revoke:'offer_access_removed',community_grant:'group_access_granted',community_revoke:'group_access_revoked',issue_certificate:'certificate_issued',create_invoice:'invoice',create_estimate:'estimate',create_order:'order_submitted',create_subscription:'subscription',create_review_request:'review_request_created'};
 await emitWorkflowEvent(client,eventMap[type]||`${objectType}_changed`,contact,{object_type:objectType,status,amount:obj.amount,object_id:obj.id},obj.id);return obj;
}

export type WorkflowExecResult={contact:any;stop?:boolean;jumpTo?:number};
export async function executeWorkflowStep(step:any,currentContact:any,workflow:any,client:any,depth=0):Promise<WorkflowExecResult>{
 if(depth>8)throw new Error('Workflow branches are nested too deeply.');const cfg=step?.step_config||{},type=String(step?.step_type||'');
 if(type==='if_else'){const matched=matchesCondition(cfg,currentContact),branch=matched?(Array.isArray(cfg.yes_steps)?cfg.yes_steps:[]):(Array.isArray(cfg.no_steps)?cfg.no_steps:[]);await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_branch',detail:`${workflow.name}: ${matched?'YES':'NO'} branch`});let contact=currentContact;for(const nested of branch){if(['wait','wait_until'].includes(nested?.step_type))throw new Error('Wait actions inside If / Else branches are not supported; place the Wait after the branch.');const result=await executeWorkflowStep(nested,contact,workflow,client,depth+1);contact=result.contact;if(result.stop)return{contact,stop:true};if(result.jumpTo!==undefined)return{contact,jumpTo:result.jumpTo}}return{contact}}
 if(type==='stop_workflow')return{contact:currentContact,stop:true};
 if(type==='go_to')return{contact:currentContact,jumpTo:Math.max(0,Number(cfg.step_index)||0)};
 if(type==='send_sms'){if(currentContact.sms_opt_in&&currentContact.phone){const text=mergeWorkflowText(cfg.message||'',currentContact);const sent=await sendTextGridSms(currentContact.phone,text);await client.from('crm_sms_messages').insert({contact_id:currentContact.id,direction:'outbound',phone:currentContact.phone,body:text,status:'sent',provider_message_id:sent.id||null});await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_sms',detail:`${workflow.name}: ${text.slice(0,160)}`})}return{contact:currentContact}}
 if(type==='send_email'){if(currentContact.email_opt_in&&currentContact.email){await sendEmail(currentContact.email,mergeWorkflowText(cfg.subject||'Indie Cut',currentContact),mergeWorkflowText(cfg.message||'',currentContact));await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_email',detail:`${workflow.name}: ${cfg.subject||'Email'}`})}return{contact:currentContact}}
 if(type==='internal_email'){const to=mergeWorkflowText(cfg.to||'',currentContact).trim();if(!to)throw new Error('Internal notification recipient is missing.');await sendEmail(to,mergeWorkflowText(cfg.subject||'Indie Cut workflow notification',currentContact),mergeWorkflowText(cfg.message||'',currentContact));return{contact:currentContact}}
 if(type==='add_tag'||type==='remove_tag'){const tag=String(cfg.tag||'').trim();if(!tag)return{contact:currentContact};const oldTags=Array.isArray(currentContact.tags)?currentContact.tags:[],had=oldTags.some((x:any)=>normalized(x)===normalized(tag));const tags=type==='add_tag'?Array.from(new Set([...oldTags,tag])):oldTags.filter((x:any)=>normalized(x)!==normalized(tag));await client.from('crm_contacts').update({tags,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,tags};if(type==='add_tag'&&!had)await emitWorkflowEvent(client,'tag_added',next,{tag});if(type==='remove_tag'&&had)await emitWorkflowEvent(client,'tag_removed',next,{tag});return{contact:next}}
 if(type==='update_status'){const status=String(cfg.status||'').trim();if(!status)return{contact:currentContact};const previousStatus=String(currentContact.status||'');await client.from('crm_contacts').update({status,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,status};if(previousStatus!==status)await emitWorkflowEvent(client,'status_changed',next,{status,previousStatus});return{contact:next}}
 if(type==='update_contact'){const allowed=new Set(['artist_name','full_name','email','phone','genre','city','source','notes','birthday','dnd','engagement_score','assigned_user']);const field=String(cfg.field||'');if(!allowed.has(field))throw new Error('Unsupported contact field.');let value:any=mergeWorkflowText(cfg.value??'',currentContact);if(['dnd'].includes(field))value=value===true||String(value).toLowerCase()==='true';if(field==='engagement_score')value=Number(value)||0;const previous=currentContact[field];await client.from('crm_contacts').update({[field]:value,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,[field]:value};await emitWorkflowEvent(client,'contact_updated',next,{field,value,previous});if(field==='dnd'&&previous!==value)await emitWorkflowEvent(client,'contact_dnd',next,{value});return{contact:next}}
 if(type==='assign_user'||type==='remove_assigned_user'){const assigned_user=type==='assign_user'?String(cfg.user||cfg.value||'').trim():null;await client.from('crm_contacts').update({assigned_user,updated_at:new Date().toISOString()}).eq('id',currentContact.id);return{contact:{...currentContact,assigned_user}}}
 if(type==='set_dnd'){const dnd=cfg.value!==false;await client.from('crm_contacts').update({dnd,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,dnd};await emitWorkflowEvent(client,'contact_dnd',next,{value:dnd});return{contact:next}}
 if(type==='engagement_score'){const score=Math.max(0,Number(cfg.value)||0);await client.from('crm_contacts').update({engagement_score:score,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,engagement_score:score};await emitWorkflowEvent(client,'contact_engagement_score',next,{value:score});return{contact:next}}
 if(type==='add_note'){const note=mergeWorkflowText(cfg.note||'',currentContact).trim();if(!note)return{contact:currentContact};const notes=[String(currentContact.notes||'').trim(),note].filter(Boolean).join('\n\n');await client.from('crm_contacts').update({notes,updated_at:new Date().toISOString()}).eq('id',currentContact.id);await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_note',detail:note.slice(0,300)});const next={...currentContact,notes};await emitWorkflowEvent(client,'note_added',next,{note});return{contact:next}}
 if(type==='create_task'){if(cfg.title){const {data:task}=await client.from('crm_tasks').insert({contact_id:currentContact.id,title:mergeWorkflowText(cfg.title,currentContact),notes:mergeWorkflowText(cfg.notes||'',currentContact)||null,status:'open',priority:String(cfg.priority||'normal'),due_at:cfg.due_hours?new Date(Date.now()+Number(cfg.due_hours)*3600000).toISOString():null}).select('*').single();await emitWorkflowEvent(client,'task_added',currentContact,{task_id:task?.id,title:task?.title,due_at:task?.due_at})}return{contact:currentContact}}
 if(type==='copy_contact'){const copy:any={...currentContact};delete copy.id;delete copy.created_at;delete copy.updated_at;copy.email=cfg.email?mergeWorkflowText(cfg.email,currentContact):null;copy.phone=cfg.phone?mergeWorkflowText(cfg.phone,currentContact):null;copy.artist_name=mergeWorkflowText(cfg.artist_name||`${currentContact.artist_name||currentContact.full_name||'Contact'} Copy`,currentContact);copy.source='workflow_copy';const {data:newContact}=await client.from('crm_contacts').insert(copy).select('*').single();if(newContact)await emitWorkflowEvent(client,'contact_created',newContact,{source:'workflow_copy'});return{contact:currentContact}}
 if(type==='delete_contact'){await client.from('crm_contacts').delete().eq('id',currentContact.id);return{contact:currentContact,stop:true}}
 if(type==='enroll_workflow'){const target=String(cfg.workflow_id||'');if(target&&target!==workflow.id){const {data:existing}=await client.from('crm_workflow_enrollments').select('id').eq('workflow_id',target).eq('contact_id',currentContact.id).eq('status','active').limit(1);if(!existing?.length)await client.from('crm_workflow_enrollments').insert({workflow_id:target,contact_id:currentContact.id,current_step:0,status:'active',next_run_at:new Date().toISOString(),context:{trigger_type:'workflow_action',source_workflow_id:workflow.id}})}return{contact:currentContact}}
 if(type==='remove_from_workflow'){const target=String(cfg.workflow_id||'');if(target)await client.from('crm_workflow_enrollments').update({status:'stopped',updated_at:new Date().toISOString()}).eq('workflow_id',target).eq('contact_id',currentContact.id).eq('status','active');return{contact:currentContact}}
 if(type==='outbound_webhook'){const url=String(cfg.url||'').trim();if(!/^https:\/\//i.test(url))throw new Error('Webhook URL must use https://');const method=['POST','PUT','PATCH'].includes(String(cfg.method||'POST').toUpperCase())?String(cfg.method||'POST').toUpperCase():'POST';let payload:any={workflow:{id:workflow.id,name:workflow.name},contact:currentContact};if(cfg.body_template){const rendered=mergeWorkflowText(cfg.body_template,currentContact);try{payload=JSON.parse(rendered)}catch{payload={message:rendered,workflow:{id:workflow.id,name:workflow.name},contact_id:currentContact.id}}}const headers:any={'content-type':'application/json'};if(cfg.secret)headers['x-indiecut-workflow-secret']=String(cfg.secret);const r=await fetch(url,{method,headers,body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Webhook failed with HTTP ${r.status}`);return{contact:currentContact}}
 if(type==='text_formatter'){const input=mergeWorkflowText(cfg.input||'',currentContact);let result=input;const op=String(cfg.operation||'trim');if(op==='uppercase')result=input.toUpperCase();if(op==='lowercase')result=input.toLowerCase();if(op==='titlecase')result=input.replace(/\b\w/g,x=>x.toUpperCase());if(op==='trim')result=input.trim();const field=String(cfg.save_to||'notes');if(['notes','source','status'].includes(field)){await client.from('crm_contacts').update({[field]:result,updated_at:new Date().toISOString()}).eq('id',currentContact.id);return{contact:{...currentContact,[field]:result}}}return{contact:currentContact}}
 if(type==='update_custom_value'){const key=String(cfg.key||'').trim();if(key){const custom_fields={...(currentContact.custom_fields||{}),[key]:mergeWorkflowText(cfg.value||'',currentContact)};await client.from('crm_contacts').update({custom_fields,updated_at:new Date().toISOString()}).eq('id',currentContact.id);return{contact:{...currentContact,custom_fields}}}return{contact:currentContact}}
 if(type.startsWith('ai_')){const result=await aiText(type,cfg,currentContact),saveTo=String(cfg.save_to||'notes');let next=currentContact;if(['notes','source','status'].includes(saveTo)){const value=saveTo==='notes'?[String(currentContact.notes||'').trim(),result].filter(Boolean).join('\n\n'):result.trim().slice(0,saveTo==='status'?80:4000);await client.from('crm_contacts').update({[saveTo]:value,updated_at:new Date().toISOString()}).eq('id',currentContact.id);next={...currentContact,[saveTo]:value}}await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_ai',detail:`${workflow.name}: ${result.slice(0,250)}`});return{contact:next}}
 if(await objectAction(client,type,currentContact,workflow,cfg))return{contact:currentContact};
 const externalMap:any={send_slack:'slack',call:'voice',messenger:'meta_messaging',instagram_dm:'meta_messaging',gmb_message:'google_business',review_request:'reviews',facebook_messenger:'meta_messaging',instagram_messenger:'meta_messaging',reply_comment:'social_messaging',whatsapp:'whatsapp',live_chat:'live_chat',google_sheets:'google_sheets',stripe_charge:'stripe',send_documents:'documents',google_analytics:'google_analytics',google_ads:'google_ads',facebook_audience_add:'meta_ads',facebook_audience_remove:'meta_ads',facebook_capi:'meta_ads',ivr_gather:'voice',ivr_play:'voice',ivr_connect:'voice',ivr_end:'voice',ivr_voicemail:'voice'};
 if(externalMap[type]){await queueIntegration(client,type,currentContact,workflow,cfg,externalMap[type]);return{contact:currentContact}}
 throw new Error(`Unsupported workflow action: ${type}`);
}

export async function runScheduledWorkflowTriggers(client:any,now:Date){
 let enrolled=0;const {data:workflows}=await client.from('crm_workflows').select('*').eq('status','published').in('trigger_type',['scheduled','birthday_reminder','custom_date_reminder','task_reminder','stale_opportunities']).limit(500);
 for(const w of workflows||[]){const cfg=w.trigger_config||{},type=w.trigger_type,last=w.last_triggered_at?new Date(w.last_triggered_at):null;let due=false,contacts:any[]=[];
  if(type==='scheduled'){const runAt=cfg.run_at?new Date(cfg.run_at):null;if(!runAt||Number.isNaN(runAt.getTime())||runAt.getTime()>now.getTime())continue;const recurrence=String(cfg.recurrence||'once');if(!last)due=true;else{const diff=now.getTime()-last.getTime();due=recurrence==='daily'?diff>=23*3600000:recurrence==='weekly'?diff>=6.9*86400000:recurrence==='monthly'?diff>=27*86400000:false}if(due){let q=client.from('crm_contacts').select('*');if(cfg.status)q=q.eq('status',cfg.status);if(cfg.tag)q=q.contains('tags',[cfg.tag]);const r=await q.limit(2000);contacts=r.data||[]}}
  if(type==='birthday_reminder'){const mm=String(now.getUTCMonth()+1).padStart(2,'0'),dd=String(now.getUTCDate()).padStart(2,'0');const {data}=await client.from('crm_contacts').select('*').not('birthday','is',null);contacts=(data||[]).filter((c:any)=>String(c.birthday||'').slice(5,10)===`${mm}-${dd}`);due=!last||now.getTime()-last.getTime()>20*3600000}
  if(type==='custom_date_reminder'){const field=String(cfg.field||'').trim();if(field){const {data}=await client.from('crm_contacts').select('*');contacts=(data||[]).filter((c:any)=>{const v=c.custom_fields?.[field];if(!v)return false;const d=new Date(v);return !Number.isNaN(d.getTime())&&Math.abs(d.getTime()-now.getTime())<30*60000});due=true}}
  if(type==='task_reminder'){const {data}=await client.from('crm_tasks').select('*,crm_contacts(*)').eq('status','open').lte('due_at',new Date(now.getTime()+30*60000).toISOString()).gte('due_at',new Date(now.getTime()-30*60000).toISOString());contacts=(data||[]).map((x:any)=>x.crm_contacts).filter(Boolean);due=true}
  if(type==='stale_opportunities'){const days=Math.max(1,Number(cfg.days)||7),cutoff=new Date(now.getTime()-days*86400000).toISOString();const {data}=await client.from('crm_workflow_objects').select('*,crm_contacts(*)').eq('object_type','opportunity').lt('updated_at',cutoff).neq('status','won').neq('status','lost');contacts=(data||[]).map((x:any)=>x.crm_contacts).filter(Boolean);due=true}
  if(!due||!contacts.length)continue;for(const c of contacts){const result=await enrollMatchingWorkflows(client,c.id,type,{scheduled_at:now.toISOString()});enrolled+=result.enrolled}await client.from('crm_workflows').update({last_triggered_at:now.toISOString(),updated_at:now.toISOString()}).eq('id',w.id)
 }
 return enrolled;
}
