import {NextResponse} from 'next/server';
import {createClient as createServiceClient} from '@supabase/supabase-js';

export const dynamic='force-dynamic';
export const maxDuration=300;
const KEY='music_video_radar_latest';
const MIN_VIEWS=14000;
function textFromResponse(json:any){if(typeof json?.output_text==='string')return json.output_text;const parts:string[]=[];for(const item of json?.output||[]){for(const c of item?.content||[]){if(typeof c?.text==='string')parts.push(c.text)}}return parts.join('\n').trim()}
function parseJson(text:string){return JSON.parse(String(text||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim())}
function validUrl(v:any){const s=String(v||'').trim();return /^https?:\/\//i.test(s)?s:''}
function youtubeId(url:string){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.replace(/^\//,'').split('/')[0];if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.match(/\/shorts\/([^/?]+)/)?.[1]||''}catch{}return ''}

export async function GET(request:Request){
 const secret=process.env.CRON_SECRET;if(!secret)return NextResponse.json({error:'CRON_SECRET is not configured'},{status:503});if(request.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({error:'Unauthorized cron request'},{status:401});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,apiKey=process.env.OPENAI_API_KEY;if(!url||!key||!apiKey)return NextResponse.json({error:'Scheduled music-video environment variables are incomplete'},{status:503});
 const db=createServiceClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const focus='New official music videos across R&B, hip-hop, soul, pop, Afrobeats and adjacent genres, from independent and major artists';const count=12;const days=7;
 const prompt=`You are Indie Cut's TRENDING music-video discovery editor. Use live web search to find up to ${count} official music videos released within the last ${days} days. Focus on ${focus}. HARD RULES: every result must be published within the last ${days} days AND must have at least ${MIN_VIEWS.toLocaleString('en-US')} currently verified YouTube views. If a video has fewer than ${MIN_VIEWS.toLocaleString('en-US')} views, or you cannot verify the view count, OMIT it. Do not return older catalog videos. Include independent and major-label artists. Use only official artist, Vevo, or official label YouTube uploads; no fan uploads, reaction videos, mirrors, or lyric reposts. Rank momentum primarily by verified views relative to release age, then credible press/social attention. Never invent view counts, release dates, labels, quotes, or channel names. Return ONLY valid JSON: {"videos":[{"artist_name":"","song_title":"","video_title":"","genre":"","artist_tier":"independent|major|unknown","official_video_url":"https://www.youtube.com/watch?v=...","channel_name":"","release_date":"YYYY-MM-DD","view_count":14000,"why_feature":"","momentum_score":0,"thumbnail_url":"","sources":["https://..."],"discovered_at":"ISO timestamp"}]}.`;
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',tools:[{type:'web_search'}],input:prompt,max_output_tokens:24000})});const j=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:j?.error?.message||'Scheduled music-video research failed'},{status:502});
 let parsed:any;try{parsed=parseJson(textFromResponse(j))}catch{return NextResponse.json({error:'The music-video model returned invalid JSON'},{status:502})}
 const tiers=new Set(['independent','major','unknown']);const raw=Array.isArray(parsed?.videos)?parsed.videos:[];const cutoff=Date.now()-days*86400000;const seen=new Set<string>();const videos=raw.map((v:any)=>{const official=validUrl(v.official_video_url);const id=youtubeId(official);const views=Math.floor(Number(v.view_count||0));const release=String(v.release_date||'').trim();const releasedAt=release?Date.parse(`${release}T23:59:59Z`):NaN;if(!id||seen.has(id)||!Number.isFinite(views)||views<MIN_VIEWS||!Number.isFinite(releasedAt)||releasedAt<cutoff)return null;seen.add(id);return {artist_name:String(v.artist_name||'').trim(),song_title:String(v.song_title||'').trim(),video_title:String(v.video_title||'').trim(),genre:String(v.genre||'').trim(),artist_tier:tiers.has(String(v.artist_tier))?String(v.artist_tier):'unknown',official_video_url:official,channel_name:String(v.channel_name||'').trim(),release_date:release,view_count:views,why_feature:String(v.why_feature||'').trim(),momentum_score:Math.max(0,Math.min(100,Number(v.momentum_score||0))),thumbnail_url:validUrl(v.thumbnail_url)||`https://img.youtube.com/vi/${id}/hqdefault.jpg`,sources:Array.isArray(v.sources)?v.sources.map(validUrl).filter(Boolean).slice(0,6):[],discovered_at:String(v.discovered_at||new Date().toISOString())}}).filter((v:any)=>v&&v.artist_name&&v.song_title).sort((a:any,b:any)=>b.momentum_score-a.momentum_score||b.view_count-a.view_count).slice(0,count);
 const scan={scanned_at:new Date().toISOString(),focus,days,count,min_views:MIN_VIEWS,videos};await db.from('site_settings').upsert({setting_key:KEY,setting_value:JSON.stringify(scan),updated_at:new Date().toISOString()},{onConflict:'setting_key'});return NextResponse.json({ok:true,...scan});
}
