import {NextResponse} from 'next/server';
import {createClient as createServiceClient} from '@supabase/supabase-js';
import {createClient} from '../../../../lib/supabase/server';
import {isAdminEmail} from '../../../../lib/admin';
import {slugify} from '../../../../lib/battles';
import {enrollMatchingWorkflows} from '../../../../lib/crm-workflows';

const ACTIVE_POOL_STATUSES=['draft','qualifying','scheduled','live'];

async function adminDb(){const auth=createClient();const {data:{user}}=await auth.auth.getUser();if(!user||!isAdminEmail(user.email))return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return {error:NextResponse.json({error:'Supabase service credentials missing'},{status:503})};return {db:createServiceClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
async function readSubmissions(db:any){const {data}=await db.from('site_settings').select('setting_value').eq('setting_key','battle_submissions').maybeSingle();try{return JSON.parse(data?.setting_value||'[]')}catch{return[]}}
async function writeSubmissions(db:any,rows:any[]){return db.from('site_settings').upsert({setting_key:'battle_submissions',setting_value:JSON.stringify(rows),updated_at:new Date().toISOString()},{onConflict:'setting_key'})}
async function publicRows(db:any){const rows:any[]=await readSubmissions(db);const approved=rows.filter((x:any)=>x.status==='approved');for(const item of approved){if(item.fan_path)continue;let entry:any=null;if(item.battle_entry_id){const r=await db.from('battle_entries').select('id,slug,contest_id').eq('id',item.battle_entry_id).maybeSingle();entry=r.data}if(!entry){const q=await db.from('battle_entries').select('id,slug,contest_id').eq('artist_name',item.artist_name).eq('active',true).order('created_at',{ascending:false}).limit(1);entry=q.data?.[0]}if(entry){const {data:contest}=await db.from('battle_contests').select('slug,title').eq('id',entry.contest_id).maybeSingle();if(contest?.slug){item.battle_entry_id=entry.id;item.approved_to_contest_id=entry.contest_id;item.approved_to_contest_title=item.approved_to_contest_title||contest.title;item.fan_path=`/battles/${contest.slug}/artists/${entry.slug}`}}}if(approved.some((x:any)=>x.fan_path)){await writeSubmissions(db,rows)}return rows.map(({ip_hash,...rest}:any)=>rest)}
async function contests(db:any){const {data}=await db.from('battle_contests').select('id,title,slug,status,genre,qualifying_starts_at,qualifying_ends_at').neq('status','completed').order('created_at',{ascending:false});return data||[]}
async function findCrmContact(db:any,item:any){const fields='id,instagram_url,tiktok_url,youtube_url,facebook_url';const email=String(item?.email||'').trim().toLowerCase();if(email){const {data}=await db.from('crm_contacts').select(fields).eq('email',email).maybeSingle();if(data)return data}const phone=String(item?.phone||'').replace(/\D/g,'');if(phone){const {data:contacts}=await db.from('crm_contacts').select(`${fields},phone`);const match=(contacts||[]).find((x:any)=>String(x.phone||'').replace(/\D/g,'')===phone);if(match)return match}return null}
async function uniqueContestSlug(db:any,genre:string){const base=slugify(`${genre}-phase-one`)||'genre-phase-one';let slug=base,n=2;while(true){const {data}=await db.from('battle_contests').select('id').eq('slug',slug).maybeSingle();if(!data)return slug;slug=`${base}-${n++}`}}
async function resolveGenreContest(db:any,item:any,requestedContestId:string){
 const genre=String(item?.genre||'').trim();if(!genre)return {error:'This submission does not have a genre.'};
 if(requestedContestId){const {data:contest}=await db.from('battle_contests').select('id,title,slug,status,genre').eq('id',requestedContestId).maybeSingle();if(!contest)return {error:'Competition not found.'};if(!contest.genre)return {error:'Set the competition genre before approving artists.'};if(String(contest.genre).trim().toLowerCase()!==genre.toLowerCase())return {error:`Genre mismatch: ${item.artist_name} submitted as ${genre}, but this competition is ${contest.genre}.`};return {contest}}
 const {data:active,error:activeError}=await db.from('battle_contests').select('id,title,slug,status,genre').in('status',ACTIVE_POOL_STATUSES).order('created_at',{ascending:false});if(activeError)return {error:activeError.message};
 const match=(active||[]).find((c:any)=>String(c.genre||'').trim().toLowerCase()===genre.toLowerCase());if(match)return {contest:match};
 const slug=await uniqueContestSlug(db,genre);const now=new Date().toISOString();const title=`${genre} Phase One`;const {data:created,error:createError}=await db.from('battle_contests').insert({title,slug,genre,description:`${genre} artists compete only against other ${genre} artists. Fans decide who advances.`,status:'qualifying',qualifying_starts_at:now,vote_window_seconds:30,zoom_session_name:`indiecut-${slug}`}).select('id,title,slug,status,genre').single();if(createError)return {error:createError.message};return {contest:created};
}
export async function GET(){const a=await adminDb();if(a.error)return a.error;const db=a.db!;return NextResponse.json({submissions:await publicRows(db),contests:await contests(db)})}
export async function POST(request:Request){
 const a=await adminDb();if(a.error)return a.error;const db=a.db!;const body=await request.json().catch(()=>({}));const action=String(body.action||''),id=String(body.submissionId||'');const rows:any[]=await readSubmissions(db);const index=rows.findIndex((x:any)=>x.id===id);if(index<0)return NextResponse.json({error:'Submission not found'},{status:404});const item=rows[index];
 if(action==='approve'){
  if(item.status==='approved')return NextResponse.json({error:'This submission is already approved.'},{status:400});const requestedContestId=String(body.contestId||'');const resolved=await resolveGenreContest(db,item,requestedContestId);if(resolved.error)return NextResponse.json({error:resolved.error},{status:400});const contest=resolved.contest;const contestId=contest.id;const crmContact=await findCrmContact(db,item);let base=slugify(item.artist_name)||'artist',slug=base,n=2;while(true){const {data}=await db.from('battle_entries').select('id').eq('contest_id',contestId).eq('slug',slug).maybeSingle();if(!data)break;slug=`${base}-${n++}`}
  const {data:entry,error}=await db.from('battle_entries').insert({contest_id:contestId,artist_name:item.artist_name,slug,genre:item.genre,city:item.city||null,bio:item.bio||null,image_url:item.image_url||null,track_title:item.track_title||null,track_url:item.track_url||null,track_cover_url:item.image_url||null,instagram_url:item.instagram_url||crmContact?.instagram_url||null,tiktok_url:item.tiktok_url||crmContact?.tiktok_url||null,youtube_url:item.youtube_url||crmContact?.youtube_url||null,facebook_url:item.facebook_url||crmContact?.facebook_url||null,active:true}).select('id,slug').single();if(error)return NextResponse.json({error:error.message},{status:400});const fan_path=`/battles/${contest.slug}/artists/${entry.slug}`;rows[index]={...item,status:'approved',approved_to_contest_id:contestId,approved_to_contest_title:contest.title,battle_entry_id:entry.id,fan_path,instagram_url:item.instagram_url||crmContact?.instagram_url||null,tiktok_url:item.tiktok_url||crmContact?.tiktok_url||null,youtube_url:item.youtube_url||crmContact?.youtube_url||null,facebook_url:item.facebook_url||crmContact?.facebook_url||null,updated_at:new Date().toISOString()};const {error:saveError}=await writeSubmissions(db,rows);if(saveError)return NextResponse.json({error:saveError.message},{status:400});if(crmContact?.id){await db.from('crm_contacts').update({battle_entry_id:entry.id,status:'approved',updated_at:new Date().toISOString()}).eq('id',crmContact.id);try{await enrollMatchingWorkflows(db,crmContact.id,'battle_submission_approved',{submissionId:item.id,contestId,contestTitle:contest.title,genre:item.genre,fan_path})}catch(e){console.error('Battle approval workflow trigger failed',e)}}return NextResponse.json({ok:true,submissions:await publicRows(db),contests:await contests(db),entry:{...entry,fan_path},contest})
 }
 if(action==='update_photo'){const imageUrl=String(body.image_url||'').trim();if(item.status!=='approved'||!item.battle_entry_id)return NextResponse.json({error:'Approve this artist before editing the live profile.'},{status:400});if(!imageUrl)return NextResponse.json({error:'Upload a profile image first.'},{status:400});const {error:entryError}=await db.from('battle_entries').update({image_url:imageUrl,updated_at:new Date().toISOString()}).eq('id',item.battle_entry_id);if(entryError)return NextResponse.json({error:entryError.message},{status:400});rows[index]={...item,image_url:imageUrl,updated_at:new Date().toISOString()};const {error:saveError}=await writeSubmissions(db,rows);if(saveError)return NextResponse.json({error:saveError.message},{status:400});return NextResponse.json({ok:true,submissions:await publicRows(db),contests:await contests(db)})}
 if(action==='reject'||action==='reopen'){rows[index]={...item,status:action==='reject'?'rejected':'pending',updated_at:new Date().toISOString()};const {error}=await writeSubmissions(db,rows);if(error)return NextResponse.json({error:error.message},{status:400});if(action==='reject'){try{const contact=await findCrmContact(db,item);if(contact?.id)await enrollMatchingWorkflows(db,contact.id,'battle_submission_rejected',{submissionId:item.id,track_title:item.track_title,genre:item.genre})}catch(e){console.error('Battle rejection workflow trigger failed',e)}}return NextResponse.json({ok:true,submissions:await publicRows(db),contests:await contests(db)})}
 if(action==='delete'){rows.splice(index,1);const {error}=await writeSubmissions(db,rows);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,submissions:await publicRows(db),contests:await contests(db)})}
 return NextResponse.json({error:'Unknown action'},{status:400});
}
