import {NextResponse} from 'next/server';
import {createClient as createServiceClient} from '@supabase/supabase-js';
import {sendTextGridSms} from '../../../../lib/textgrid';
import {enrollMatchingWorkflows} from '../../../../lib/crm-workflows';

export const dynamic='force-dynamic';
export const maxDuration=120;

function db(){return createServiceClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
async function sendEmail(to:string,subject:string,body:string){const key=process.env.RESEND_API_KEY,from=process.env.INDIECUT_FROM_EMAIL;if(!key||!from)throw new Error('Email integration not configured.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({from,to:[to],subject,text:body})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.message||'Email send failed.')}
function waitUntil(config:any){const amount=Math.max(1,Number(config?.amount)||1),unit=String(config?.unit||'hours'),ms=unit==='minutes'?amount*60000:unit==='days'?amount*86400000:amount*3600000;return new Date(Date.now()+ms).toISOString()}
function mergeText(text:string,c:any){const first=String(c.full_name||c.artist_name||'').split(/\s+/)[0]||'';const map:any={artist_name:c.artist_name||c.full_name||'',first_name:first,full_name:c.full_name||'',genre:c.genre||'',city:c.city||'',email:c.email||'',phone:c.phone||'',notes:c.notes||'',source:c.source||'',status:c.status||''};return String(text||'').replace(/{{\s*([a-z_]+)\s*}}/gi,(_:string,k:string)=>String(map[k]??''))}
function normalized(v:any){return String(v??'').trim().toLowerCase()}
function fieldValue(c:any,f:string){if(f==='tag')return Array.isArray(c.tags)?c.tags:[];if(f==='email_opt_in'||f==='sms_opt_in')return Boolean(c[f]);return c?.[f]??''}
function matchesCondition(cfg:any,c:any){const field=String(cfg?.field||'status'),op=String(cfg?.operator||'equals'),expected=cfg?.value,actual=fieldValue(c,field);if(op==='exists')return Array.isArray(actual)?actual.length>0:Boolean(String(actual??'').trim());if(op==='not_exists')return Array.isArray(actual)?actual.length===0:!String(actual??'').trim();if(field==='tag'){const found=(actual as any[]).some(x=>normalized(x)===normalized(expected));return op==='not_equals'||op==='not_contains'?!found:found}if(field==='email_opt_in'||field==='sms_opt_in'){const wanted=expected===true||String(expected).toLowerCase()==='true',eq=Boolean(actual)===wanted;return op==='not_equals'||op==='not_contains'?!eq:eq}const a=normalized(actual),b=normalized(expected);if(op==='contains')return a.includes(b);if(op==='not_contains')return!a.includes(b);if(op==='not_equals')return a!==b;return a===b}
function textFromResponse(j:any){if(typeof j?.output_text==='string')return j.output_text;const out:string[]=[];for(const item of j?.output||[])for(const part of item?.content||[])if(typeof part?.text==='string')out.push(part.text);return out.join('\n').trim()}
async function aiText(kind:string,cfg:any,c:any){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY is not configured.');const input=mergeText(cfg.input||'{{notes}}',c),instruction=mergeText(cfg.instruction||'',c);let task='Generate useful concise text for this CRM workflow.';if(kind==='ai_summarize')task='Summarize the input clearly and concisely.';if(kind==='ai_detect_intent')task='Classify the primary intent in a short label, then one sentence of reasoning.';if(kind==='ai_extract')task='Extract the important facts from the input in concise JSON.';if(kind==='ai_translate')task=`Translate the input into ${cfg.language||'Spanish'} while preserving meaning.`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',input:`${task}\n${instruction?`Additional instruction: ${instruction}\n`:''}Input:\n${input}`,max_output_tokens:1200})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||'AI workflow action failed.');return textFromResponse(j)}

type ExecResult={contact:any;stop?:boolean};
async function executeImmediateStep(step:any,currentContact:any,workflow:any,client:any,depth=0):Promise<ExecResult>{
 if(depth>5)throw new Error('If / Else branches are nested too deeply.');const cfg=step?.step_config||{},type=String(step?.step_type||'');
 if(type==='if_else'){const matched=matchesCondition(cfg,currentContact),branch=matched?(Array.isArray(cfg.yes_steps)?cfg.yes_steps:[]):(Array.isArray(cfg.no_steps)?cfg.no_steps:[]);await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_branch',detail:`${workflow.name}: ${matched?'YES':'NO'} branch — ${String(cfg.field||'status')} ${String(cfg.operator||'equals')} ${String(cfg.value??'')}`.slice(0,300)});let contact=currentContact;for(const nested of branch){if(['wait','wait_until'].includes(nested?.step_type))throw new Error('Wait actions are not supported inside an If / Else branch. Add the Wait after the branch.');const result=await executeImmediateStep(nested,contact,workflow,client,depth+1);contact=result.contact;if(result.stop)return{contact,stop:true}}return{contact}}
 if(type==='stop_workflow')return{contact:currentContact,stop:true};
 if(type==='send_sms'){if(currentContact.sms_opt_in&&currentContact.phone){const text=mergeText(cfg.message||'',currentContact);const sent=await sendTextGridSms(currentContact.phone,text);await client.from('crm_sms_messages').insert({contact_id:currentContact.id,direction:'outbound',phone:currentContact.phone,body:text,status:'sent',provider_message_id:sent.id||null});await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_sms',detail:`${workflow.name}: ${text.slice(0,160)}`})}return{contact:currentContact}}
 if(type==='send_email'){if(currentContact.email_opt_in&&currentContact.email){await sendEmail(currentContact.email,mergeText(cfg.subject||'Indie Cut',currentContact),mergeText(cfg.message||'',currentContact));await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_email',detail:`${workflow.name}: ${cfg.subject||'Email'}`})}return{contact:currentContact}}
 if(type==='internal_email'){const to=mergeText(cfg.to||'',currentContact).trim();if(!to)throw new Error('Internal notification recipient is missing.');await sendEmail(to,mergeText(cfg.subject||'Indie Cut workflow notification',currentContact),mergeText(cfg.message||'',currentContact));return{contact:currentContact}}
 if(type==='add_tag'||type==='remove_tag'){const tag=String(cfg.tag||'').trim();if(!tag)return{contact:currentContact};const oldTags=Array.isArray(currentContact.tags)?currentContact.tags:[],had=oldTags.some((x:any)=>normalized(x)===normalized(tag));const tags=type==='add_tag'?Array.from(new Set([...oldTags,tag])):oldTags.filter((x:any)=>normalized(x)!==normalized(tag));await client.from('crm_contacts').update({tags,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,tags};if(type==='add_tag'&&!had)await enrollMatchingWorkflows(client,currentContact.id,'tag_added',{tag});if(type==='remove_tag'&&had)await enrollMatchingWorkflows(client,currentContact.id,'tag_removed',{tag});return{contact:next}}
 if(type==='update_status'){if(!cfg.status)return{contact:currentContact};const nextStatus=String(cfg.status),previousStatus=String(currentContact.status||'');await client.from('crm_contacts').update({status:nextStatus,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,status:nextStatus};if(previousStatus!==nextStatus)await enrollMatchingWorkflows(client,currentContact.id,'status_changed',{status:nextStatus,previousStatus});return{contact:next}}
 if(type==='update_contact'){const allowed=new Set(['artist_name','full_name','email','phone','genre','city','source','notes']);const field=String(cfg.field||'');if(!allowed.has(field))throw new Error('Unsupported contact field.');const value=mergeText(cfg.value||'',currentContact);await client.from('crm_contacts').update({[field]:value,updated_at:new Date().toISOString()}).eq('id',currentContact.id);const next={...currentContact,[field]:value};await enrollMatchingWorkflows(client,currentContact.id,'contact_updated',{field,value});return{contact:next}}
 if(type==='add_note'){const note=mergeText(cfg.note||'',currentContact).trim();if(!note)return{contact:currentContact};const notes=[String(currentContact.notes||'').trim(),note].filter(Boolean).join('\n\n');await client.from('crm_contacts').update({notes,updated_at:new Date().toISOString()}).eq('id',currentContact.id);await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_note',detail:note.slice(0,300)});return{contact:{...currentContact,notes}}}
 if(type==='create_task'){if(cfg.title)await client.from('crm_tasks').insert({contact_id:currentContact.id,title:mergeText(cfg.title,currentContact),notes:mergeText(cfg.notes||'',currentContact)||null,status:'open',priority:String(cfg.priority||'normal'),due_at:cfg.due_hours?new Date(Date.now()+Number(cfg.due_hours)*3600000).toISOString():null});return{contact:currentContact}}
 if(type==='enroll_workflow'){const target=String(cfg.workflow_id||'');if(target&&target!==workflow.id){const {data:existing}=await client.from('crm_workflow_enrollments').select('id').eq('workflow_id',target).eq('contact_id',currentContact.id).eq('status','active').limit(1);if(!existing?.length)await client.from('crm_workflow_enrollments').insert({workflow_id:target,contact_id:currentContact.id,current_step:0,status:'active',next_run_at:new Date().toISOString(),context:{trigger_type:'workflow_action',source_workflow_id:workflow.id}})}return{contact:currentContact}}
 if(type==='remove_from_workflow'){const target=String(cfg.workflow_id||'');if(target)await client.from('crm_workflow_enrollments').update({status:'stopped',updated_at:new Date().toISOString()}).eq('workflow_id',target).eq('contact_id',currentContact.id).eq('status','active');return{contact:currentContact}}
 if(type==='outbound_webhook'){const url=String(cfg.url||'').trim();if(!/^https:\/\//i.test(url))throw new Error('Webhook URL must use https://');const method=['POST','PUT','PATCH'].includes(String(cfg.method||'POST').toUpperCase())?String(cfg.method||'POST').toUpperCase():'POST';let payload:any={workflow:{id:workflow.id,name:workflow.name},contact:currentContact};if(cfg.body_template){const rendered=mergeText(cfg.body_template,currentContact);try{payload=JSON.parse(rendered)}catch{payload={message:rendered,workflow:{id:workflow.id,name:workflow.name},contact_id:currentContact.id}}}const headers:any={'content-type':'application/json'};if(cfg.secret)headers['x-indiecut-workflow-secret']=String(cfg.secret);const r=await fetch(url,{method,headers,body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Webhook failed with HTTP ${r.status}`);return{contact:currentContact}}
 if(type.startsWith('ai_')){const result=await aiText(type,cfg,currentContact),saveTo=String(cfg.save_to||'notes');let next=currentContact;if(saveTo==='notes'){const notes=[String(currentContact.notes||'').trim(),result].filter(Boolean).join('\n\n');await client.from('crm_contacts').update({notes,updated_at:new Date().toISOString()}).eq('id',currentContact.id);next={...currentContact,notes}}else if(saveTo==='source'){await client.from('crm_contacts').update({source:result,updated_at:new Date().toISOString()}).eq('id',currentContact.id);next={...currentContact,source:result}}else if(saveTo==='status'){const previousStatus=String(currentContact.status||'');const status=result.trim().slice(0,80);await client.from('crm_contacts').update({status,updated_at:new Date().toISOString()}).eq('id',currentContact.id);next={...currentContact,status};if(previousStatus!==status)await enrollMatchingWorkflows(client,currentContact.id,'status_changed',{status,previousStatus})}await client.from('crm_activity').insert({contact_id:currentContact.id,activity_type:'workflow_ai',detail:`${workflow.name}: ${result.slice(0,250)}`});return{contact:next}}
 return{contact:currentContact};
}

async function runScheduledTriggers(client:any,now:Date){
 const {data:workflows}=await client.from('crm_workflows').select('*').eq('status','published').eq('trigger_type','scheduled').limit(100);let enrolled=0;
 for(const w of workflows||[]){const cfg=w.trigger_config||{},runAt=cfg.run_at?new Date(cfg.run_at):null;if(!runAt||Number.isNaN(runAt.getTime())||runAt.getTime()>now.getTime())continue;const recurrence=String(cfg.recurrence||'once'),last=w.last_triggered_at?new Date(w.last_triggered_at):null;let due=!last;if(last){const diff=now.getTime()-last.getTime();due=recurrence==='daily'?diff>=23*3600000:recurrence==='weekly'?diff>=6.9*86400000:recurrence==='monthly'?diff>=27*86400000:false}if(!due)continue;let q=client.from('crm_contacts').select('id');if(cfg.status)q=q.eq('status',cfg.status);if(cfg.tag)q=q.contains('tags',[cfg.tag]);const {data:contacts}=await q.limit(2000);for(const c of contacts||[]){const {data:existing}=await client.from('crm_workflow_enrollments').select('id').eq('workflow_id',w.id).eq('contact_id',c.id).eq('status','active').limit(1);if(!existing?.length){await client.from('crm_workflow_enrollments').insert({workflow_id:w.id,contact_id:c.id,current_step:0,status:'active',next_run_at:now.toISOString(),context:{trigger_type:'scheduled'}});enrolled++}}await client.from('crm_workflows').update({last_triggered_at:now.toISOString(),updated_at:now.toISOString()}).eq('id',w.id)}return enrolled;
}

export async function GET(){
 const client=db(),nowDate=new Date(),now=nowDate.toISOString();let smsSent=0,smsFailed=0,workflowSteps=0,workflowFailed=0;const scheduledEnrolled=await runScheduledTriggers(client,nowDate);
 const {data:smsQueue}=await client.from('crm_sms_queue').select('*').eq('status','queued').lte('scheduled_at',now).order('scheduled_at',{ascending:true}).limit(100);for(const item of smsQueue||[]){try{const sent=await sendTextGridSms(item.phone,item.body);await client.from('crm_sms_queue').update({status:'sent',provider_message_id:sent.id||null,sent_at:new Date().toISOString(),error:null}).eq('id',item.id);await client.from('crm_sms_messages').insert({contact_id:item.contact_id,direction:'outbound',phone:item.phone,body:item.body,status:'sent',provider_message_id:sent.id||null});smsSent++}catch(e:any){await client.from('crm_sms_queue').update({status:'failed',error:String(e?.message||'SMS failed')}).eq('id',item.id);smsFailed++}}
 const campaignIds=Array.from(new Set((smsQueue||[]).map((x:any)=>x.campaign_id).filter(Boolean)));for(const id of campaignIds){const[{count:sent},{count:failed},{count:queued}]=await Promise.all([client.from('crm_sms_queue').select('*',{count:'exact',head:true}).eq('campaign_id',id).eq('status','sent'),client.from('crm_sms_queue').select('*',{count:'exact',head:true}).eq('campaign_id',id).eq('status','failed'),client.from('crm_sms_queue').select('*',{count:'exact',head:true}).eq('campaign_id',id).eq('status','queued')]);await client.from('crm_sms_campaigns').update({sent_count:sent||0,failed_count:failed||0,status:(queued||0)>0?'sending':'completed',updated_at:new Date().toISOString()}).eq('id',id)}
 const {data:enrollments}=await client.from('crm_workflow_enrollments').select('*').eq('status','active').lte('next_run_at',now).order('next_run_at',{ascending:true}).limit(100);
 for(const enrollment of enrollments||[]){try{const[{data:workflow},{data:contact},{data:steps}]=await Promise.all([client.from('crm_workflows').select('*').eq('id',enrollment.workflow_id).maybeSingle(),client.from('crm_contacts').select('*').eq('id',enrollment.contact_id).maybeSingle(),client.from('crm_workflow_steps').select('*').eq('workflow_id',enrollment.workflow_id).order('step_order',{ascending:true})]);if(!workflow||workflow.status!=='published'||!contact){await client.from('crm_workflow_enrollments').update({status:'stopped',updated_at:new Date().toISOString()}).eq('id',enrollment.id);continue}let currentStep=Number(enrollment.current_step||0),currentContact:any=contact,settled=false;for(let guard=0;guard<100;guard++){const step=(steps||[])[currentStep];if(!step){await client.from('crm_workflow_enrollments').update({status:'completed',current_step:currentStep,last_error:null,updated_at:new Date().toISOString()}).eq('id',enrollment.id);settled=true;break}const cfg=step.step_config||{};if(step.step_type==='wait'||step.step_type==='wait_until'){currentStep++;const resume=step.step_type==='wait_until'&&cfg.datetime?new Date(cfg.datetime).toISOString():waitUntil(cfg);await client.from('crm_workflow_enrollments').update({current_step:currentStep,status:'active',next_run_at:resume,last_error:null,updated_at:new Date().toISOString()}).eq('id',enrollment.id);workflowSteps++;settled=true;break}const result=await executeImmediateStep(step,currentContact,workflow,client);currentContact=result.contact;currentStep++;if(result.stop){await client.from('crm_workflow_enrollments').update({current_step:currentStep,status:'stopped',last_error:null,updated_at:new Date().toISOString()}).eq('id',enrollment.id);workflowSteps++;settled=true;break}const done=currentStep>=(steps||[]).length;await client.from('crm_workflow_enrollments').update({current_step:currentStep,status:done?'completed':'active',next_run_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq('id',enrollment.id);workflowSteps++;if(done){settled=true;break}}if(!settled)throw new Error('Workflow exceeded 100 immediate steps.')}catch(e:any){await client.from('crm_workflow_enrollments').update({status:'failed',last_error:String(e?.message||'Workflow failed'),updated_at:new Date().toISOString()}).eq('id',enrollment.id);workflowFailed++}}
 return NextResponse.json({ok:true,smsSent,smsFailed,scheduledEnrolled,workflowSteps,workflowFailed});
}
