import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';
import { isAdminEmail } from '../../../lib/admin';
import SectionManager from '../SectionManager';
import ArticleManager from '../ArticleManager';
import FooterSettings from '../FooterSettings';
import ContentAgentScheduler from '../ContentAgentScheduler';
import SocialAgentSettings from '../SocialAgentSettings';
import SocialAnalytics from '../SocialAnalytics';
import WebsiteAnalytics from '../WebsiteAnalytics';
import BreakingNewsRadar from '../BreakingNewsRadar';
import IndependentMusicRadar from '../IndependentMusicRadar';
import IndieSpotlightAgent from '../IndieSpotlightAgent';
import MusicVideoRadar from '../MusicVideoRadar';
import AdvertisingManager from '../AdvertisingManager';
import StreamingManager from '../StreamingManager';
import BattleManager from '../BattleManager';
import BattleLandingSettings from '../BattleLandingSettings';
import BattleSubmissionsManager from '../BattleSubmissionsManager';
import BattleRoomSponsors from '../BattleRoomSponsors';
import BattleArtistEditor from '../BattleArtistEditor';
import CrmManager from '../CrmManager';
import MusicManager from '../MusicManager';
import AutomationBuilderV5 from '../AutomationBuilderV5';
import TrackingPixelsSettings from '../TrackingPixelsSettings';
import TheCutManager from '../TheCutManager';
import TheCutMusicPreviewSettings from '../TheCutMusicPreviewSettings';
import RadioManager from '../RadioManager';

const sections:Record<string,{title:string;intro:string}>={radio:{title:'Indie Cut Radio',intro:'Run the Indie Cut 24/7 internet radio station, connect the live stream and control the sitewide player.'},homepage:{title:'Homepage',intro:'Control hero content, featured stories and homepage presentation.'},streaming:{title:'Streaming / Shows & Episodes',intro:'Upload and manage Indie Cut hosted shows, episodes, trailers and other programming for Indie Cut Watch.'},articles:{title:'Articles',intro:'Create, edit, verify and publish Indie Cut stories with uploaded media.'},artists:{title:'Artists',intro:'Review artist profile submissions, approve or reject new artists, and edit approved artist profiles.'},music:{title:'Music',intro:'Add songs, releases, performances and music media.'},'the-cut':{title:'The Cut',intro:'Create, launch and moderate Indie Cut live audio rooms, manage speakers and share conversations with the audience.'},'live-battles':{title:'Live Battles',intro:'Control Live Battles, artist submissions, sponsors, voting and results.'},crm:{title:'Artist CRM',intro:'Own the artist relationship database and campaigns.'},workflows:{title:'Workflows & SMS',intro:'Build visual automations, send TextGrid SMS and manage workflow enrollments.'},'independent-music':{title:'Independent Music Radar',intro:'Discover trending independent artists using live web signals.'},'music-video-radar':{title:'Music Video Radar',intro:'Find new official music videos and publish them to Indie Cut Watch.'},'video-media':{title:'Video & Media',intro:'Upload video and photography for stories, artists and homepage placements.'},'breaking-news':{title:'Breaking News Radar',intro:'Scan live sources for newly reported entertainment news.'},'content-agent':{title:'AI Content Agent',intro:'Research current mainstream entertainment stories and create review-ready drafts.'},'indie-spotlight-agent':{title:'Indie Spotlight AI Agent',intro:'Discover and verify independent music artists, filmmakers and creators without affecting the main Content Agent.'},'social-agent':{title:'Social Media Agent',intro:'Automatically turn published stories into platform-ready social posts.'},advertising:{title:'Advertising / Commercials',intro:'Upload and manage Indie Cut display advertising and streaming commercials.'},authors:{title:'Authors & Editors',intro:'Manage editorial profiles, headshots, bios and bylines.'},analytics:{title:'Analytics',intro:'Review Indie Cut website audience plus social performance.'},'tracking-pixels':{title:'Tracking & Pixels',intro:'Connect Meta, Google, TikTok and Google Tag Manager.'},'media-library':{title:'Media Library',intro:'Browse and add reusable image and video assets.'},subscribers:{title:'Email Subscribers',intro:'Manage the Indie Cut reader list.'},settings:{title:'Site Settings',intro:'Control publication-wide brand, navigation, footer and social settings.'}};
export const dynamic='force-dynamic';
export default async function AdminSectionPage({params}:{params:{section:string}}){const section=sections[params.section];if(!section)notFound();const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');if(!isAdminEmail(user.email))redirect('/');const content=params.section==='radio'?<RadioManager/>:params.section==='streaming'?<StreamingManager/>:params.section==='artists'?<><BattleSubmissionsManager/><BattleArtistEditor/></>:params.section==='the-cut'?<><TheCutMusicPreviewSettings/><TheCutManager/></>:params.section==='live-battles'?<><BattleRoomSponsors/><BattleLandingSettings/><BattleSubmissionsManager/><BattleArtistEditor/><BattleManager/></>:params.section==='crm'?<CrmManager/>:params.section==='music'?<MusicManager/>:params.section==='workflows'?<AutomationBuilderV5/>:params.section==='articles'?<ArticleManager/>:params.section==='breaking-news'?<BreakingNewsRadar/>:params.section==='independent-music'?<IndependentMusicRadar/>:params.section==='indie-spotlight-agent'?<IndieSpotlightAgent/>:params.section==='music-video-radar'?<MusicVideoRadar/>:params.section==='social-agent'?<SocialAgentSettings/>:params.section==='analytics'?<><WebsiteAnalytics/><SocialAnalytics/></>:params.section==='tracking-pixels'?<TrackingPixelsSettings/>:params.section==='advertising'?<AdvertisingManager/>:<SectionManager section={params.section}/>;return <main className="ic-module-page"><header className="ic-module-header"><Link href="/admin">← Back Office</Link><div className="ic-admin-eyebrow">INDIE CUT ADMIN</div><h1>{section.title}</h1><p>{section.intro}</p></header>{content}{params.section==='content-agent'&&<ContentAgentScheduler/>}{params.section==='settings'&&<FooterSettings/>}</main>}
