import {NextResponse} from 'next/server';import {createClient as svc} from '@supabase/supabase-js';import {createClient} from '../../../../lib/supabase/server';import {isAdminEmail} from '../../../../lib/admin';
function service(){return svc(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}})}
async function admin(){const a=createClient();const {data:{user}}=await a.auth.getUser();return !!(user&&isAdminEmail(user.email))}
export async function GET(){if(!await admin())return NextResponse.json({error:'Unauthorized'},{status:401});const {data}=await service().from('radio_live_sessions').select('*,radio_live_guests(*)').order('created_at',{ascending:false}).limit(20);return NextResponse.json({sessions:data||[]},{headers:{'cache-control':'no-store'}})}
export async function POST(req:Request){if(!await admin())return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json(),x=service(),action=String(b.action||'');
if(action==='create'){const {data,error}=await x.from('radio_live_sessions').insert({title:String(b.title||'Live Interview').trim(),host_name:b.host_name||null,guest_name:b.guest_name||null,record_enabled:b.record_enabled!==false}).select('*').single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true,session:data})}
if(action==='start'){const now=new Date().toISOString();const {data,error}=await x.from('radio_live_sessions').update({status:'live',started_at:now,updated_at:now}).eq('id',b.id).select('*').single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true,session:data})}
if(action==='end'){const now=new Date().toISOString();const {data,error}=await x.from('radio_live_sessions').update({status:'ended',ended_at:now,updated_at:now}).eq('id',b.id).select('*').single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true,session:data,resume_automation:true})}
if(action==='guest'){const now=new Date().toISOString();const {error}=await x.from('radio_live_guests').update({status:b.status,updated_at:now}).eq('id',b.guest_id);return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true})}
return NextResponse.json({error:'Unknown action'},{status:400})}